### ISSUE TITLE
请问增量预训练大概需要几块GPU呢？

### ISSUE THREAD

**Issue by jason7323** [shibing624/MedicalGPT#1]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
1. 用lora做增量预训练，llama-7b用fp16加载需要14G显存，block size=1024上下文长度，需要24G显存就可以，batch size 适当调整；
2. 用全参训练，llama-7b需要4张32G显卡。

**Comment by YSLLYW** [comment]
> 1. 用lora做增量预训练，llama-7b用fp16加载需要14G显存，block size=1024上下文长度，需要24G显存就可以，batch size 适当调整；
> 2. 用全参训练，llama-7b需要4张32G显卡。

这里您用的全参数训练，请问用了deepspeed吗，没用的话大概需要多少显存

**Comment by shibing624** [comment]
> 1. 24G

没用，24G
