### ISSUE TITLE
Lora是pt方法吗？Lora是微调方法吗？

### ISSUE THREAD

**Issue by chengzhen123** [shibing624/MedicalGPT#100]
### Describe the Question
Please provide a clear and concise description of what the question is.
如题所示，peft表示，Lora是微调的方法和prompt一样，但是项目中的pt方法，用的Lora，我有几个疑惑：
1. Lora可以当做pt方法？ 那prompt是否也可以？
2. Lora和传统的continue pt的方法有什么区别？ 优缺点是什么？
3. 项目为什么要用Lora，而不是传统的continue pt的方法，是因为模型开源程度达不到吗？还是其他原因。
4. 目前开源的base大模型，哪些是模型只能用Lora方法？
谢谢解答

**Comment by shibing624** [comment]
看下lora的paper
