### ISSUE TITLE
llama 2 系列会支持吗？直接微调？

### ISSUE THREAD

**Issue by SaraiQX** [shibing624/MedicalGPT#105]
大佬好！感谢分享！
计划在llama 2 模型上  用垂直领域数据微调，请问建议从原始模型（中文语料少）直接开始吗？还是等社区的通用中文模型出来 再加垂直领域的中文语料呢？新手小白，感谢！

**Comment by shibing624** [comment]
1.已经支持了
2.第二个
3.建议用baichuan-13b-chat，中文能力也不错
