### ISSUE TITLE
新代码chatglm运行PT和sft阶段也出错

### ISSUE THREAD

**Issue by daimazz1** [shibing624/MedicalGPT#108]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

你好我拉了新代码咋test数据下训练chatglm-6b的PT和sft阶段均出错，之前使用旧代码在test数据下跑这两阶段未出现错误，现在的错误显示为：
PT阶段：130004 is not in list
然后在group_text()中加了result = {
k: [t[i: i + block_size] for i in range(0, total_length, block_size) if 130004 in t[i: i + block_size]]
for k, t in concatenated_examples.items()
} 
报错为expected scalar type Half but Float
 sft阶段:
报错为expected scalar type Half but Float

**Comment by shibing624** [comment]
1. 我本地测试chatglm1-6b是可以通过的；
2. 如果你测试还不行，可以恢复到旧代码，指定tag即可；

**Comment by shibing624** [comment]
set template_name vicuna
