### ISSUE TITLE
chatglm2模型运行run_pt.sh问题

### ISSUE THREAD

**Issue by LKAMING97** [shibing624/MedicalGPT#112]
![08a3371cbee544d6bd5f17c0cbbad37](https://github.com/shibing624/MedicalGPT/assets/90093699/ce3c3401-3438-4edf-9c4c-6f0acb5589d1)

使用库中提供的2.4M中文医疗数据集数据，运行的时候就出现这个问题

**Comment by LKAMING97** [comment]
其他部分都没动过就改了模型用chatglm2和数据

**Comment by yysirs** [comment]
你是用的1.1版本代码嘛？ 我也出现这个问题

**Comment by LKAMING97** [comment]
> 

是的，我用的就是最新拉下来的版本

**Comment by LKAMING97** [comment]
> 你是用的1.1版本代码嘛？ 我也出现这个问题

是的，我用的就是最新拉下来的

**Comment by LKAMING97** [comment]
> 你是用的1.1版本代码嘛？ 我也出现这个问题

是的是的，最新拉下来的

**Comment by yysirs** [comment]
可能这个版本有点问题，但是目前还没发现问题出在哪里😂 
我看这个报错说的是OOM可能会引起，但是单卡跑是没有问题的，你可以先用单卡跑起来。

**Comment by LKAMING97** [comment]
> 可能这个版本有点问题，但是目前还没发现问题出在哪里😂 我看这个报错说的是OOM可能会引起，但是单卡跑是没有问题的，你可以先用单卡跑起来。

我就是单卡4090动不了，换了个llama2又好起来了

**Comment by yysirs** [comment]
> > 可能这个版本有点问题，但是目前还没发现问题出在哪里😂 我看这个报错说的是OOM可能会引起，但是单卡跑是没有问题的，你可以先用单卡跑起来。
> 
> 我就是单卡4090动不了，换了个llama2又好起来了

我单卡glm2是可以的
