### ISSUE TITLE
最近两天的更新是不是调整了什么？为什么出的结果比以前少了很多？

### ISSUE THREAD

**Issue by lzy83925** [shibing624/MedicalGPT#114]
### Describe the Question
Please provide a clear and concise description of what the question is.
如题！

**Comment by shibing624** [comment]
什么出的结果少了？

如果是长度，max_length可以指定长度。

**Comment by lzy83925** [comment]
调整了max length为1024，但是每次的输出内容主观上感觉比上周的要精简了很多。而且也没了以前的观点分成1234的这种叙述方式，每次就是一句话就结束了在 2023年7月25日，20:46，Ming Xu ***@***.***> 写道：﻿
什么出的结果少了？
如果是长度，max_length可以指定长度。

**Comment by lzy83925** [comment]
跟模型对话生成的内容少了。
---- 回复的原邮件 ----
| 发件人 | Ming Xu ***@***.***> |
| 发送日期 | 2023年07月25日 20:45 |
| 收件人 | shibing624/MedicalGPT ***@***.***> |
| 抄送人 | Luis ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [shibing624/MedicalGPT] 最近两天的更新是不是调整了什么？为什么出的结果比以前少了很多？ (Issue #114) |

什么出的结果少了？

如果是长度，max_length可以指定长度。

**Comment by shibing624** [comment]
```generation_config = dict(
        temperature=0.2,
        top_k=40,
        top_p=0.9,
        do_sample=True,
        repetition_penalty=1.3,
        max_new_tokens=400
    )
```  这个是之前的生成参数

**Comment by lzy83925** [comment]
感觉还是没啥变化。现在的答复有一些特征不知道算不算正常，我目前是直接用的shibing624/ziya-llama-13b-medical-merged在text-generation-webui上跑的，参数参考了楼一层楼你给的建议，结论基本如下：

1. 惜字如金，Chat的回答的非常精简(比如问老年人腰扭了，应该怎么治疗？
)，虽然是基于医疗的数据进行指令精调，但是回答非常的精简(相较于ChatGLM2、ChatGPT3.5)，这个也是挺奇怪的，按常理来说MedicalGPT应该要回复的更专业更详细一些啊。
2、没有像其他的大模型一样把输出的内容进行1、2、3、4这样的梳理和排版，给出的答复基本上就是一到两句话。


基于上，是我哪里做的还不对吗？还是模型本身就是这种效果？

**Comment by shibing624** [comment]
正常的，微调后回答会简练一些，预测前最好加上system prompt，就是alpaca的template, template_name='alpaca' ， 用inference.py看下。

**Comment by lzy83925** [comment]
> 正常的，微调后回答会简练一些，预测前最好加上system prompt，就是alpaca的template, template_name='alpaca' ， 用inference.py看下。

是这个吗？
![image](https://github.com/shibing624/MedicalGPT/assets/1124823/5452f9a9-0757-455b-9812-e4ce60555eb4)

**Comment by shibing624** [comment]
嗯
