### ISSUE TITLE
今天使用新代码 sft跑chatglm2-6b ：| WARNING  | __main__:preprocess_function:813 - tokenization mismatch: 1 vs. 81.  (ignored) 

### ISSUE THREAD

**Issue by valkryhx** [shibing624/MedicalGPT#115]
在sft.py 的
769行开始德循环内logger.warning(f"tokenization mismatch: {cur_len} vs. {total_len}.  (ignored)") 这里
cur_len 一直为1 
| WARNING  | __main__:preprocess_function:813 - tokenization mismatch: 1 vs. 81.  (ignored) 不断  
感觉是循环内部cur_len += turn_len 没有正确处理
if len(parts) != 2:
       break
似乎全部break了 所以cur_len一直是1 。

我打印了
parts = turn.split(sep)
logger.info(f"len(parts)={len(parts)} , parts={parts}")
发现 所有的len(parts)=1 , parts=['[Round']   
感觉前面turns结果不对 导致 parts没有找到对应的问/答 而是对应到了round标记。

**Comment by valkryhx** [comment]
> 感谢指出问题，区分了chatglm和chatglm2的template， template_name='chatglm'， template_name='chatglm2'
> 
> 我之前本地测试用 template_name='vicuna'是成功的。

好的 我再试试

**Comment by shibing624** [comment]
updated, now set template_name='chatglm2' is ok.

**Comment by elijah-hz** [comment]
把template_name='vicuna' ，在chatglm2的最新模型上训练，还是有大量的warning：
WARNING  | __main__:preprocess_function:754 - tokenization mismatch: 339 vs. 341. (ignored)
并且最后出错：
RuntimeError: Subtraction, the `-` operator, with a bool tensor is not supported. If you are trying to invert a mask, use the `~` or `logical_not()` operator instead.

**Comment by shibing624** [comment]
https://github.com/shibing624/MedicalGPT/issues/118
