### ISSUE TITLE
rl_training训练集问题

### ISSUE THREAD

**Issue by cosine123** [shibing624/MedicalGPT#120]
发生异常: KeyError
'instruction'
  File "MedicalGPT/rl_training.py", line 334, in preprocess_function
    for instruction, input in zip(examples['instruction'], examples['input']):
  File "MedicalGPT/rl_training.py", line 357, in main
    tokenized_dataset = train_dataset.shuffle().map(
  File "MedicalGPT/rl_training.py", line 461, in <module>
    main()
KeyError: 'instruction'

**Comment by shibing624** [comment]
新增了多轮对话数据集，还没适配rl，rl阶段可以用alpaca数据集测试。

**Comment by cosine123** [comment]
发生异常: ValueError
only one element tensors can be converted to Python scalars
  File "/MedicalGPT/rl_training.py", line 448, in <listcomp>
    rewards = [torch.tensor(float(score) - args.reward_baseline) for score in score_outputs]
  File "/MedicalGPT/rl_training.py", line 448, in main
    rewards = [torch.tensor(float(score) - args.reward_baseline) for score in score_outputs]
  File "/MedicalGPT/rl_training.py", line 469, in <module>
    main()
ValueError: only one element tensors can be converted to Python scalars

**Comment by vs0533** [comment]
@shibing624 同问

**Comment by vs0533** [comment]
研究了一下 发现 多个元素的张量转换为 Python 标量（单个值）时出现了问题 可以这么解决
rewards = calculate_rewards(score_outputs, args)
# 计算奖励
    def calculate_rewards(score_outputs, args):
        rewards = []
        for score in score_outputs:
            if isinstance(score, torch.Tensor) and score.numel() == 1:
                reward_value = score.item() - args.reward_baseline
                rewards.append(torch.tensor(reward_value))
            else:
                # 处理 `score` 不是单个值张量的情况（例如，包含多个元素的张量）
                # 这里我们选择计算张量元素的平均值作为奖励值，您可以根据具体情况选择其他操作
                reward_value = torch.mean(score).item() - args.reward_baseline
                rewards.append(torch.tensor(reward_value))
        return rewards
或者可以将batch_size 改为1 @shibing624 @cosine123

**Comment by cosine123** [comment]
Thanks.



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月2日(周三) 晚上10:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [shibing624/MedicalGPT] rl_training训练集问题 (Issue #120)




 
研究了一下 发现 多个元素的张量转换为 Python 标量（单个值）时出现了问题 可以这么解决
 rewards = calculate_rewards(score_outputs, args)
 
计算奖励
 def calculate_rewards(score_outputs, args):     rewards = []     for score in score_outputs:         if isinstance(score, torch.Tensor) and score.numel() == 1:             reward_value = score.item() - args.reward_baseline             rewards.append(torch.tensor(reward_value))         else:             # 处理 `score` 不是单个值张量的情况（例如，包含多个元素的张量）             # 这里我们选择计算张量元素的平均值作为奖励值，您可以根据具体情况选择其他操作             reward_value = torch.mean(score).item() - args.reward_baseline             rewards.append(torch.tensor(reward_value))     return rewards  
或者可以将batch_size 改为1 @shibing624 @cosine123
