### ISSUE TITLE
使用lora对CodeGen模型进行训练，显示模型的可训练参数为0

### ISSUE THREAD

**Issue by peppa-nwpu** [shibing624/MedicalGPT#123]
### Describe the Question
Please provide a clear and concise description of what the question is.
大哥你好，我在使用SFT方式对一个gpt系列的模型进行训练时，使用lora方式，显示模型的可训练参数为0，请问这是什么原因。
![Snipaste_2023-07-27_12-26-54](https://github.com/shibing624/MedicalGPT/assets/63275684/2d5bc8fc-2634-42dd-bfd2-8b7b9807fd00)
但是我在用自己写了几行代码尝试使用lora方式训练时，却显示模型的可训练参数不为0
![Snipaste_2023-07-27_12-28-44](https://github.com/shibing624/MedicalGPT/assets/63275684/0f565782-b44a-4356-9a3b-bdc264a9569e)
![Snipaste_2023-07-27_12-29-15](https://github.com/shibing624/MedicalGPT/assets/63275684/dbc919ff-7c80-4efe-87b1-abf4b546036b)
但是我如果再用SFT时，将参数--target_modules设置为'[q_proj,v_proj]'，运行的时候会报错为
![Snipaste_2023-07-27_12-36-00](https://github.com/shibing624/MedicalGPT/assets/63275684/9c2e89e3-e0ad-4462-b8ef-b5aee8c77e31)
请问这个是什么原因

**Comment by shibing624** [comment]
set --target_modules all

**Comment by peppa-nwpu** [comment]
我设置了--target_moudles all，也还是显示可训练参数为0
![Snipaste_2023-07-27_16-45-05](https://github.com/shibing624/MedicalGPT/assets/63275684/9f137e83-669c-4fd1-83d9-0c0095682059)
![Snipaste_2023-07-27_16-44-26](https://github.com/shibing624/MedicalGPT/assets/63275684/65b78c4b-c245-4546-8cdd-fdcfc2644f42)

**Comment by peppa-nwpu** [comment]
一个代码生成的模型，cdoeGen

**Comment by shibing624** [comment]
我没测试过，可能不兼容，需要自己改下代码适配。

**Comment by peppa-nwpu** [comment]
那这个应该怎么进行尝试呢，需要改那个find linear函数吗

**Comment by peppa-nwpu** [comment]
我找到原因了，模型在加载的时候就是8位量化了，但是在最后的时候又执行了一次量化，所以就导致了可训练的参数为0，不知道原因是什么，但是把下面的量化代码给注释掉，可训练参数就有了，但是不明白原理
![Snipaste_2023-07-27_23-24-12](https://github.com/shibing624/MedicalGPT/assets/63275684/e30e8a80-6a8a-4593-9725-0742777c96e8)
![Snipaste_2023-07-27_23-23-22](https://github.com/shibing624/MedicalGPT/assets/63275684/8b8ae09c-cc1d-4d9c-9760-9f02aaa76925)
![Snipaste_2023-07-27_23-23-46](https://github.com/shibing624/MedicalGPT/assets/63275684/871b2a19-a596-4916-adcf-5443daaacf2c)

**Comment by shibing624** [comment]
就是lora不支持8为量化的训练吧

**Comment by shibing624** [comment]
fixed
