### ISSUE TITLE
sft过程中，使用中文LLama2 出现tokenization_mismatch 问题

### ISSUE THREAD

**Issue by LKAMING97** [shibing624/MedicalGPT#128]
使用了hf上的 [Chinese-Llama-2-7b](https://huggingface.co/LinkSoul/Chinese-Llama-2-7b) ，但是出现tokenization_mismatch 问题,使用的template也是“llama-2”
### Describe the Question
Please provide a clear and concise description of what the question is.
![微信图片_20230728121032](https://github.com/shibing624/MedicalGPT/assets/90093699/7d4d32b3-9af7-4fd5-9e3d-97cd50cda5f5)

**Comment by shibing624** [comment]
训练指定template_name = 'vicuna' , 有问题看下https://github.com/shibing624/MedicalGPT/wiki/%E8%AE%AD%E7%BB%83%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E
