### ISSUE TITLE
单机多卡运行时报timeout的错

### ISSUE THREAD

**Issue by CHAOJICHENG5** [shibing624/MedicalGPT#129]
感谢作者的项目！
我想问个问题就是每次多卡运行的时候因为分词得花很多时间，所以到30分钟的时候总会报错，后来查看 pytorch的ddp运行参数里有：
init_process_group(
    backend: Union[str, Backend] = None,
    init_method: Optional[str] = None,
    timeout: timedelta = default_pg_timeout（1800s）,
    world_size: int = -1,
    rank: int = -1,
    store: Optional[Store] = None,
    group_name: str = "",
    pg_options: Optional[Any] = None,
)
里面的初始化默认timeout时间为1800s(30min),也就是run_pt.sh脚本中的--ddp_timeout参数，我发现这个并不能调整。所以运行三十分钟时会报错，我想问一下怎么修改ddp_timeout?

**Comment by shibing624** [comment]
1.  用单卡把tokenizer process跑完，然后存到cache，多卡执行时调用cache。参考https://github.com/huggingface/transformers/issues/17106
2. 当前如果ddp_timeout参数调大如果失效，可能是pytorch的bug，https://github.com/shibing624/MedicalGPT/blob/main/run_sft.sh#L31

**Comment by acadaiaca** [comment]
> 感谢作者的项目！ 我想问个问题就是每次多卡运行的时候因为分词得花很多时间，所以到30分钟的时候总会报错，后来查看 pytorch的ddp运行参数里有： init_process_group( backend: Union[str, Backend] = None, init_method: Optional[str] = None, timeout: timedelta = default_pg_timeout（1800s）, world_size: int = -1, rank: int = -1, store: Optional[Store] = None, group_name: str = "", pg_options: Optional[Any] = None, ) 里面的初始化默认timeout时间为1800s(30min),也就是run_pt.sh脚本中的--ddp_timeout参数，我发现这个并不能调整。所以运行三十分钟时会报错，我想问一下怎么修改ddp_timeout?

请问解决了吗？尝试了调大ddp_timeout无法生效。打算采用“用单卡把tokenizer process跑完，然后存到cache，多卡执行时调用cache。”这个方法，但不太会改

**Comment by shibing624** [comment]
那手动写代码把tokenizer process的结果保存为pkl，下次训练加载pkl文件

**Comment by acadaiaca** [comment]
> 那手动写代码把tokenizer process的结果保存为pkl，下次训练加载pkl文件

谢谢！
