### ISSUE TITLE
使用deepspeed+项目中的deepspeed config文件跑 sft和pt 发现会存储很大的中间状态文件

### ISSUE THREAD

**Issue by valkryhx** [shibing624/MedicalGPT#130]
参考sft.sh 和 pt.sh 我将启动方式改成如下启动方式 ds使用到项目自带cofig 是zero-2
deepspeed --include localhost:0,1 supervised_finetuning.py \
    --model_type chatglm \
    --model_name_or_path THUDM/chatglm2-6b \
    --train_file_dir ./data/finetune \
    --validation_file_dir ./data/finetune \
    --template_name chatglm2 \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --do_train \
    --do_eval \
    --use_peft True \
    --qlora True \
    --fp16 \
    --max_train_samples 200 \
    --max_eval_samples 10 \
    --num_train_epochs 100 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 5 \
    --evaluation_strategy steps \
    --save_steps 10 \
    --save_strategy steps \
    --save_total_limit 2 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --model_max_length 512 \
    --output_dir outputs-sft-qlora-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 64 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float32 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --deepspeed [deepspeed_config.json]

 --save_steps 10  每10步保存lora adapter 。
但是发现每次保存的时候都会向目录中输出deepspeed 状态的 .pt 文件 这个文件基本就是模型大小 很占磁盘。
想问下 如何不输出这个文件呢？我看有的项目就没有这个问题。比如 这个 https://github.com/shuxueslpi/chatGLM-6B-QLoRA    使用deepspeed训练就可以只输出lora adapter 。不知道是不是配置问题？

**Comment by shibing624** [comment]
1. --save_steps 10 改为100000
2. deepspeed需要单独测试下，我还没来得及测试多个模型的deepspeed多种运行方法

**Comment by valkryhx** [comment]
> 1. --save_steps 10 改为100000
> 2. deepspeed需要单独测试下，我还没来得及测试多个模型的deepspeed多种运行方法

--save_steps 改大确实可以规避这个问题  但是这样的话就无法正常保证中间的lora adapter ckpt 比如我想200步存一次 即使训练中断 或者人为停止 我也可以从中间的某个ckpt-400 重新继续训练。

**Comment by valkryhx** [comment]
已修改成功

**Comment by chloefresh** [comment]
> 已修改成功

@valkryhx hi，怎么解决的呢？也遇到了一样的问题
