### ISSUE TITLE
ChatGLM2 Sft tokenization mismatch问题

### ISSUE THREAD

**Issue by zhengorange** [shibing624/MedicalGPT#131]
### Describe the Question
Please provide a clear and concise description of what the question is.

最近使用您的框架微调ChatGLM2，但是有几个问题没有跑通，请您帮忙看一下是bug还是我这有问题？谢谢啦

【问题1】
supervised_finetuning.py第737行 turns = conversation.split(conv.sep2)
假如有三轮对话，则conversation中存在三个`</s>`，遍历中的turn是不含`</s>`的，所以turn_len求和之后再加上初试的cur_len会比total_len少2

【问题2】
可能是ChatGlm2的问题，其tokenizer无法对eos字符即`</s>`进行处理。
tokenizer = AutoTokenizer.from_pretrained("THUDM/chatglm2-6b", trust_remote_code=True)
print(tokenizer("你好"))  # {'input_ids': [64790, 64792, 36474, 54591]}
print(tokenizer("你好`</s>`")) # {'input_ids': [64790, 64792, 36474, 54591, 1833, 30917, 30994]}
print(tokenizer.eos_token) # `</s>`
print(tokenizer.eos_token_id) # 2

【问题3】
ChatGLM2默认的tokenizer是从左边填充pad，而看您的代码好像是需要从右侧pad。
conversations = ["""问：你好。

答: 你也好`</s>`"""]
input_ids = tokenizer(
    conversations,
    return_tensors="pt",
    padding="max_length",
    max_length=512,
    truncation=True,
).input_ids
print(input_ids) # tensor([[    0,     0,     0,  ...,  1833, 30917, 30994]])

非常感谢！

**Comment by shibing624** [comment]
fixed
