### ISSUE TITLE
模型中断后，重新跑找不到chekpoint

### ISSUE THREAD

**Issue by Leekinxun** [shibing624/MedicalGPT#133]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
ValueError: Can't find a valid checkpoint   是因为save的时候没有save全吗？

**Comment by shibing624** [comment]
lora训练没有checkpoint，自己看下lora训练的博客吧。
