### ISSUE TITLE
利用chatglm2-6B进行有监督微调训练之后，其inference能力很差，结果中出现一句话多次重复的情况，想问下您这是什么原因引起的，是由于数据集的问题吗？

### ISSUE THREAD

**Issue by 1716649290** [shibing624/MedicalGPT#135]
![image](https://github.com/shibing624/MedicalGPT/assets/58947669/7a4dabc5-ba03-4526-97f1-7bec89bf1e3c)

**Comment by AILWQ** [comment]
> ![image](https://user-images.githubusercontent.com/58947669/257230451-7a4dabc5-ba03-4526-97f1-7bec89bf1e3c.png)

推理的时候加没加prompt，参数要指定 --with_prompt

**Comment by 1716649290** [comment]
最新的inference代码里没有with_prompt属性

**Comment by shibing624** [comment]
指定--template_name为训练时用的。

**Comment by vs0533** [comment]
训练时并未发现--template_name参数 且colab第四阶段不能运行 提示
Traceback (most recent call last):
  File "/content/MedicalGPT/rl_training.py", line 461, in <module>
    main()
  File "/content/MedicalGPT/rl_training.py", line 443, in main
    rewards = [torch.tensor(float(score) - args.reward_baseline) for score in score_outputs]
  File "/content/MedicalGPT/rl_training.py", line 443, in <listcomp>
    rewards = [torch.tensor(float(score) - args.reward_baseline) for score in score_outputs]
ValueError: only one element tensors can be converted to Python scalars @shibing624

**Comment by shibing624** [comment]
利用chatglm2-6B进行有监督微调训练之后，其inference能力很差，结果中出现一句话多次重复的情况，想问下您这是什么原因引起的，是由于数据集的问题吗？

1. 预测效果差，训练集比较少时，不足千条，num_epoch需要设置大些，num_epoch=10
2. 训练时不允许指定--template_name参数，默认用vicuna模版训练，其他模板训练需要修改data process函数，如果要用其他模板，自行修改即可（其实区别不大）
3. rl_training 的问题fixed

**Comment by vs0533** [comment]
> 利用chatglm2-6B进行有监督微调训练之后，其inference能力很差，结果中出现一句话多次重复的情况，想问下您这是什么原因引起的，是由于数据集的问题吗？
> 
> 1. 预测效果差，训练集比较少时，不足千条，num_epoch需要设置大些，num_epoch=10
> 2. 训练时不允许指定--template_name参数，默认用vicuna模版训练，其他模板训练需要修改data process函数，如果要用其他模板，自行修改即可（其实区别不大）
> 3. rl_training 的问题fixed

训练时data process处理函数中将训练模板改为 llama-2 在处理target的时候会因为seq2的值是"<s></s>" 导致问题
1是split时因为llama-2的处理中是空格 而处理target时用了“:”
2相同原因cur_len != total_len

**Comment by shibing624** [comment]
> > 利用chatglm2-6B进行有监督微调训练之后，其inference能力很差，结果中出现一句话多次重复的情况，想问下您这是什么原因引起的，是由于数据集的问题吗？
> > 
> > 1. 预测效果差，训练集比较少时，不足千条，num_epoch需要设置大些，num_epoch=10
> > 2. 训练时不允许指定--template_name参数，默认用vicuna模版训练，其他模板训练需要修改data process函数，如果要用其他模板，自行修改即可（其实区别不大）
> > 3. rl_training 的问题fixed
> 
> 训练时data process处理函数中将训练模板改为 llama-2 在处理target的时候会因为seq2的值是"" 导致问题 1是split时因为llama-2的处理中是空格 而处理target时用了“:” 2相同原因cur_len != total_len

今天晚些时候，我更新一种data tokenizer process 方法，兼容下多个模型的处理方法。

**Comment by shibing624** [comment]
done
