### ISSUE TITLE
跑奖励模型出错，transformers版本是最新的4.31.0 还需要更新什么库？

### ISSUE THREAD

**Issue by cqray1990** [shibing624/MedicalGPT#141]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

TypeError: BloomForSequenceClassification.__init__() got an unexpected keyword argument 'num_labels'

**Comment by shibing624** [comment]
https://github.com/shibing624/MedicalGPT/issues/119#issuecomment-1661451904
