### ISSUE TITLE
训练奖励模型的时候，如果训练百川模型，请问model_type 传什么参数？我传的 baichuan 这个报错了。请问怎么处理？

### ISSUE THREAD

**Issue by DaiJitao** [shibing624/MedicalGPT#144]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

**Comment by DaiJitao** [comment]
我这样传参数的：
CUDA_VISIBLE_DEVICES=$gpu python -u reward_modeling.py \
    --model_type baichuan \
    --model_name_or_path merged-sft \
    --train_file_dir ./data/reward \
    --validation_file_dir ./data/reward \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --use_peft True \
    --seed 42 \
    --max_train_samples 1000 \
    ...

**Comment by DaiJitao** [comment]
--model_type 传什么参数？

**Comment by shibing624** [comment]
百川跟chatglm一样，暂不支持reward training。
https://github.com/shibing624/MedicalGPT/wiki/FAQ
