### ISSUE TITLE
关于V1.3的SFT格式

### ISSUE THREAD

**Issue by nuoma** [shibing624/MedicalGPT#146]
您好，关于今天更新的V1.3的SFT的格式，是不是必须使用sharegpt的格式：
{"conversations":[{"from":"human","value":"和尚\n输出下联：\n"},{"from":"gpt","value":"悟空"}]}
而原来alpaca的需要使用convert_dataset.py转化？

我在supervised_finetuning.py中看到了，这个是不是和输入的sft格式无关？并没有参透这部分是用来干什么的。谢谢麻烦了
# Baichuan-13B-Chat template
register_conv_template(
    # source: https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/blob/f5f47be2adbbdceb784f334d6fa1ca2c73e65097/modeling_baichuan.py#L507
    # https://huggingface.co/baichuan-inc/Baichuan-13B-Chat/blob/main/generation_config.json
    Conversation(
        name="baichuan-chat",
        system="",
        roles=(" <reserved_102> ", " <reserved_103> "),
        messages=[],
        offset=0,
        sep_style=SeparatorStyle.NO_COLON_TWO,
        sep="",
        sep2="</s>",
        stop_token_ids=[2, 195],
    )
)

**Comment by shibing624** [comment]
兼容百川模板，预测用的。
