### ISSUE TITLE
下载的train_encyclopedia.json医疗的数据pretrain 要把text转成一行的txt？

### ISSUE THREAD

**Issue by cqray1990** [shibing624/MedicalGPT#147]
### Describe the Question
Please provide a clear and concise description of what the question is.

加载train_encyclopedia.json 数据作增量训练的时候出错，代码是拉取最新的

envs/llama_env/lib/python3.10/site-packages/datasets/builder.py", line 552, in _create_builder_config
    builder_config = self.BUILDER_CONFIG_CLASS(**config_kwargs)
TypeError: JsonConfig.__init__() got an unexpected keyword argument 'keep_linebreaks'

**Comment by shibing624** [comment]
fixed
