### ISSUE TITLE
医疗的pretrain的中英文数据一定要合并成一个txt？

### ISSUE THREAD

**Issue by cqray1990** [shibing624/MedicalGPT#149]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

我看这里有说要合并到一个txt
https://github.com/shibing624/MedicalGPT/wiki/%E6%95%B0%E6%8D%AE%E9%9B%86

但是pretrain.py 代码这里是支持多个文件的

 if data_args.train_file_dir is not None and os.path.exists(data_args.train_file_dir):
            train_data_files = glob(f'{data_args.train_file_dir}/**/*.txt', recursive=True) + glob(
                f'{data_args.train_file_dir}/**/*.json', recursive=True) + glob(
                f'{data_args.train_file_dir}/**/*.jsonl', recursive=True)

但是到这里：

           lm_datasets = tokenized_datasets.map(
                group_texts,
                batched=True,
                num_proc=data_args.preprocessing_num_workers,
                load_from_cache_file=not data_args.overwrite_cache,
                desc=f"Grouping texts in chunks of {block_size}",

train只有一个txt文件的数据，本身总共有有44万多，可以训练的时候显示13万多，还有一个30多万每加载

**Comment by shibing624** [comment]
自动合并了，merge到block size=1024长度了
