### ISSUE TITLE
单机多卡运行卡死

### ISSUE THREAD

**Issue by zhangxinxin0428** [shibing624/MedicalGPT#15]
/### Describe the Question
Please provide a clear and concise description of what the question is.
直接运行run_pt.sh后，模型正常加载，到数据那一步卡死了，也不报错，也不往下走，显卡显存也卡住不动

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question
- [ ] 
![image](https://github.com/shibing624/MedicalGPT/assets/129820604/cdef0f62-31e8-4ff1-97a1-f994624629bf)

**Comment by shibing624** [comment]
执行命令是啥？

**Comment by zhangxinxin0428** [comment]
@shibing624 bash run_pt.sh

**Comment by shibing624** [comment]
> @shibing624 bash run_pt.sh

我在colab上3分钟跑完了这个演示的，你试试。

**Comment by zhangxinxin0428** [comment]
> /### Describe the Question Please provide a clear and concise description of what the question is. 直接运行run_pt.sh后，模型正常加载，到数据那一步卡死了，也不报错，也不往下走，显卡显存也卡住不动
> 
> ### Describe your attempts
> * [ ]  I walked through the tutorials
> * [ ]  I checked the documentation
> * [ ]  I checked to make sure that this is not a duplicate question
> * [ ]
>   ![image](https://user-images.githubusercontent.com/129820604/246045653-cdef0f62-31e8-4ff1-97a1-f994624629bf.png)

等待十几分钟后，报错如下：
![image](https://github.com/shibing624/MedicalGPT/assets/129820604/d9be6aca-ad4d-4e3b-9c78-6f66119e3a7a)

有没有小伙伴和我遇到同样的问题？想请教一下如何解决

**Comment by shibing624** [comment]
你在colab上试了pretrain的ok吗？ 如果ok，把本地环境安装的跟colab一样就行（全部库是最新版本）。

**Comment by nlper-hou** [comment]
> 

这个问题我遇到过，可以把batch_size降低，或者删一部分数据，用少量数据跑，就可以了

**Comment by zhangxinxin0428** [comment]
> > 
> 
> 这个问题我遇到过，可以把batch_size降低，或者删一部分数据，用少量数据跑，就可以了

好的，我这边试一下，感谢您的解答
