### ISSUE TITLE
关于奖励模型的选择

### ISSUE THREAD

**Issue by valkryhx** [shibing624/MedicalGPT#152]
刚才在issues中搜索发现chatglm无法作为奖励模型
请问使用bloom作为奖励模型是否可以？
在最后的RLHF阶段PPO算法中使用RM_bloom来训练SFT_chatglm是否可行呢？
我看RL阶段的代码中好像RM和SFT 模型都选的同一类 应该没有这个约束吧？

**Comment by shibing624** [comment]
都可以
