### ISSUE TITLE
请问如何把训练好的rw model参数加载起来，看log的输出是训练的score层参数没有被加载

### ISSUE THREAD

**Issue by expresschen** [shibing624/MedicalGPT#156]
### Describe the Question
Please provide a clear and concise description of what the question is.

<img width="1433" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/18161256/d6bc421e-7520-4873-aab3-75f807c41b97">

**Comment by shibing624** [comment]
训练哪个阶段出错的？

看着像是RL阶段，RL做的是生成任务，score层不加载应该不影响。

**Comment by expresschen** [comment]
我是在训练过rm之后，准备加载模型时出现的问题

**Comment by expresschen** [comment]
![image](https://github.com/shibing624/MedicalGPT/assets/18161256/d3f52569-fc9a-4507-9367-04dffe3700e6)
使用lama训练模型时，这个类是不是没有什么作用呢，我去掉这个类，测试一下模型的输出没有什么区别

**Comment by expresschen** [comment]
好的，谢谢回答啦
