### ISSUE TITLE
训练LoRA后，模型输出重复内容并且无法停止

### ISSUE THREAD

**Issue by qinyuenlp** [shibing624/MedicalGPT#157]
如题，用13000+条样本进行LoRA训练，加载训练好的LoRA权重后，在部分问题下模型会重复输出相同的一句话或一段话，并且无法停止。请问有解决方案或者debug思路吗？

效果类似于：
![image](https://github.com/shibing624/MedicalGPT/assets/39150772/41b8b34e-81ce-4ee4-8c22-fc2095fae771)

**Comment by shibing624** [comment]
一般这种情况是loss飞了，训练集质量不高也会遇到此问题，需要小心调参。

**Comment by qinyuenlp** [comment]
偶发，所以比较疑惑。
对监督微调代码有一个问题：
数据预处理(preprocess_function)逻辑是：1.给output添加eos_token；2.tokenizer根据max_target_length进行截断。

当数据集中存在output长度大于max_target_length的样本时，该样本对应的target在训练时是不带eos_token的。

不知道这个操作是否也会导致重复输出且无法停止的问题呢？

**Comment by shibing624** [comment]
1. 偶发我就不清楚；
2. process_function里面考虑到这种情况了，会手动加上eos_token的

**Comment by qinyuenlp** [comment]
> 1. 偶发我就不清楚；
> 2. process_function里面考虑到这种情况了，会手动加上eos_token的

找到原因了，我使用的代码是旧版本的，sample length > max_target_length的时候，target尾部会缺失eos_token，使用新代码后暂时没有复现复读机问题了。thx
