### ISSUE TITLE
预训练Baichuan-Chat成功但是预训练Baichuan-Base报错

### ISSUE THREAD

**Issue by Candy555** [shibing624/MedicalGPT#160]
![30351a50750e0e1ea044c97ccac3835](https://github.com/shibing624/MedicalGPT/assets/50703072/298dd2bf-d331-4b3b-b1b7-8bfaf3650544)

rt，预训练Baichuan-13B-Chat没有问题，但是替换成Baichuan-13B-Base就报如上错误，不太了解具体是怎么回事，希望大佬有空的时候能帮忙解答~我这儿peft库的版本是0.4.0.dev

**Comment by shibing624** [comment]
注释 enable_input_require_grads() 这行。
