### ISSUE TITLE
chatglm2预训练代码完成后，进行推理报错

### ISSUE THREAD

**Issue by ysanimals** [shibing624/MedicalGPT#161]
### Describe the Question
out of piece id, 推理的时候生成了词表之外的token_id，请问是什么原因

**Comment by shibing624** [comment]
need to resize model token embedding, when you add tokens.

**Comment by ysanimals** [comment]
> need to resize model token embedding, when you add tokens.

I haven't not add tokens, just use pretrain.py use pretrain model, use peftmodel to inference, without peftmodel, this problem never happen, and chatglm2 not support use resize token embedding

**Comment by ysanimals** [comment]
File "/home/komove/anaconda3/envs/glmPreTrain/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 3509, in decode
    return self._decode(
  File "/home/komove/anaconda3/envs/glmPreTrain/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 931, in _decode
    filtered_tokens = self.convert_ids_to_tokens(token_ids, skip_special_tokens=skip_special_tokens)
  File "/home/komove/anaconda3/envs/glmPreTrain/lib/python3.9/site-packages/transformers/tokenization_utils.py", line 912, in convert_ids_to_tokens
    tokens.append(self._convert_id_to_token(index))
  File "/home/komove/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 121, in _convert_id_to_token
    return self.tokenizer.convert_id_to_token(index)
  File "/home/komove/.cache/huggingface/modules/transformers_modules/chatglm2-6b/tokenization_chatglm.py", line 60, in convert_id_to_token
    return self.sp_model.IdToPiece(index)
  File "/home/komove/anaconda3/envs/glmPreTrain/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1045, in _batched_func
    return _func(self, arg)
  File "/home/komove/anaconda3/envs/glmPreTrain/lib/python3.9/site-packages/sentencepiece/__init__.py", line 1038, in _func
    raise IndexError('piece id is out of range.')
IndexError: piece id is out of range.

**Comment by ysanimals** [comment]
│   1233 │   │   """                                                                               │
│   1234 │   │   base_model = getattr(self, self.base_model_prefix, self)                          │
│   1235 │   │   if base_model is not self:                                                        │
│ ❱ 1236 │   │   │   base_model.set_input_embeddings(value)                                        │
│   1237 │   │   else:                                                                             │
│   1238 │   │   │   raise NotImplementedError                                                     │
│   1239                                                                                           │
│                                                                                                  │
│ /home/komove/anaconda3/envs/glmPreTrain/lib/python3.9/site-packages/transformers/modeling_utils. │
│ py:1238 in set_input_embeddings                                                                  │
│                                                                                                  │
│   1235 │   │   if base_model is not self:                                                        │
│   1236 │   │   │   base_model.set_input_embeddings(value)                                        │
│   1237 │   │   else:                                                                             │
│ ❱ 1238 │   │   │   raise NotImplementedError                                                     │
│   1239 │                                                                                         │
│   1240 │   def get_output_embeddings(self) -> nn.Module:                                         │
│   1241 │   │   """                                                                               │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
NotImplementedError
