### ISSUE TITLE
请问如何用deepspeed将模型并行，运行run_pt.sh？

### ISSUE THREAD

**Issue by 1106301825** [shibing624/MedicalGPT#163]
自己用deepspeed和deepspeed config文件运行run_pt.sh，出现以下错误：
DeepSpeed Zero-3 is not compatible with `low_cpu_mem_usage=True` or with passing a `device_map`.

**Comment by shibing624** [comment]
same  https://github.com/shibing624/MedicalGPT/issues/46#issuecomment-1676182910
