### ISSUE TITLE
chatglm2二次预训练报错

### ISSUE THREAD

**Issue by chloefresh** [shibing624/MedicalGPT#164]
大佬好，用项目自带数据集，在V100上用deepspeed跑全参数二次预训练报错：
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 48136) of binary: /opt/conda/envs/gpt/bin/python
Traceback (most recent call last):
  File "/opt/conda/envs/gpt/bin/torchrun", line 33, in <module>
    sys.exit(load_entry_point('torch==1.13.1', 'console_scripts', 'torchrun')())
  File "/opt/conda/envs/gpt/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/opt/conda/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/opt/conda/envs/gpt/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/opt/conda/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/opt/conda/envs/gpt/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

用lora版本是可以跑通的，但是全参数用deepspeed，deepspeed用项目自带的config，会报错。运行脚本是下面：
CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 torchrun --nproc_per_node 6 pretraining.py \
    --model_type chatglm \
    --model_name_or_path /nfs/chatglm2-6b \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pretrain \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --use_peft False \
    --seed 42 \
    --fp16 \
    --max_train_samples 10000 \
    --max_eval_samples 10 \
    --num_train_epochs 0.5 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --block_size 1024 \
    --output_dir outputs-pt-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --deepspeed deepspeed_config.json

**Comment by chloefresh** [comment]
最新尝试，deepspeed还是不行，不过CUDA_VISIBLE_DEVICES=2,3,4,5,6,7 python pretraining.py 直接跑可以跑通，不过需要修改chatglm2的代码，参考https://huggingface.co/THUDM/chatglm2-6b/discussions/54#64b542b05c1ffb087056001c

**Comment by chloefresh** [comment]
全参数预训练完了后，看着perplexity和loss都是正常的，但是推理的时候，不管问什么问题，都返回类似没有意义的回答：
![image](https://github.com/shibing624/MedicalGPT/assets/38456889/6a0e3eab-6074-42ad-b7f0-0d955dd29e0e)

USER: 西瓜是水果吗
ASSISTANT: 2.4.199974、1、南朝、840000000000000000000000000018、77.3、10000000000000000000000000000米，将100000000000000000001.30191200000000000000000000米，是人们认为最便宜， 200000000000000000000000000000000000000000000000000000000000000000000000000年7.60000000000000米，在996000000米，就，12.13.2000000万克,在1000000000年30000000000万亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿亿年11.3. 1700000年5.2.19991000年780000万克，而“人，因为兔子，14.10000000000000000000000000000000米， 4个。 1.2.2、圆，而在197000000000000000000000年14、南、绿。 3.3、5个，可以增加、1000000000000000000万亿亿亿亿亿年，可在白，而且容易有1000000000000米，因为

请问大佬这是什么原因呢 @shibing624 

推理的脚本是：
CUDA_VISIBLE_DEVICES=0 python inference.py \
      --model_type chatglm \
      --template_name vicuna \
       --base_model ./outputs \
      --tokenizer_path ./outputs\
       --interactive

**Comment by shibing624** [comment]
基本用法：Pretrain后的模型用few shot推理；SFT后的模型用zero shot推理。 inference.py 适用于SFT后的模型。
