### ISSUE TITLE
rl 阶段，运行报错  AttributeError: 'NoneType' object has no attribute 'device'

### ISSUE THREAD

**Issue by LKAMING97** [shibing624/MedicalGPT#165]
### Describe the Question
Please provide a clear and concise description of what the question is.
使用LLaMa2模型，运行脚本如下
![1692068527465](https://github.com/shibing624/MedicalGPT/assets/90093699/b93cdad5-9298-4c19-8b9e-e391fed60288)
运行到第449行报错
![1692068614786](https://github.com/shibing624/MedicalGPT/assets/90093699/9a3e8961-06b6-4dfb-98e1-8ec8ddf75d02)
![1692068629814](https://github.com/shibing624/MedicalGPT/assets/90093699/2a4f9fe6-0b79-4d6b-ab6a-b54d5c9ffb14)
 想请问一下是什么原因呢

**Comment by shibing624** [comment]
得到了None空值结果吗？
