### ISSUE TITLE
使用run_pt.sh对llama-13B在医疗数据上增量训练，跑了5个epoch，可是loss不下降是怎么回事？一直是10.25附近波动

### ISSUE THREAD

**Issue by nlper-hou** [shibing624/MedicalGPT#17]
### Describe the Question
Please provide a clear and concise description of what the question is.

### Describe your attempts
- [ ] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

**Comment by nlper-hou** [comment]
> 降的慢，正常，我pt跑了一周，8卡V100。
好的好的，多谢

**Comment by nlper-hou** [comment]
> 下降的慢，正常，我跑了一周，8卡V100。

好的好的，多谢

**Comment by HanXM715** [comment]
> 降的慢，正常，我pt跑了一周，8卡V100。

您是全量参数增量预训练吗，还是使用Lora进行增量预训练

**Comment by shibing624** [comment]
lora
