### ISSUE TITLE
continue train后，Error(s) in loading state_dict for BaichuanForCausalLM

### ISSUE THREAD

**Issue by WoWuQ** [shibing624/MedicalGPT#170]
运行v1.4版本的continue train后，加载模型再进行训练时，报如下错误，是怎么回事？

RuntimeError: Error(s) in loading state_dict for BaichuanForCausalLM:
  size mismatch for model.embed_tokens.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([64000, 5120]).
   size mismatch for model.layers.0.self_attn.W_pack.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([15360, 5120]).
  size mismatch for model.layers.0.self_attn.o_proj.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([5120, 5120]).
   size mismatch for model.layers.0.mlp.gate_proj.weight: copying a param with shape torch.Size([0]) from checkpoint, the shape in current model is torch.Size([13696, 5120]).

运行脚本：
deepspeed --hostfile=./hostfile.txt pretraining.py \
    --model_type baichuan \
    --model_name_or_path ./outputs-pt-v1 \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pt_eval \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --use_peft False \
    --seed 42 \
    --fp16 \
    --max_train_samples 10000000000000 \
    --max_eval_samples 3000 \
    --num_train_epochs 1 \
    --learning_rate 2e-4 \
    --warmup_ratio 0.05 \
    --weight_decay 0.01 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 300 \
    --evaluation_strategy steps \
    --save_steps 1500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 4 \
    --block_size 1024 \
    --output_dir outputs-pt-v2 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --deepspeed deepspeed_config_zero3.json

**Comment by shibing624** [comment]
deepspeed_config_zero3 不兼容。
