### ISSUE TITLE
增量预训练格式问题

### ISSUE THREAD

**Issue by dongteng** [shibing624/MedicalGPT#172]
### Describe the Question
请问大佬，有两个问题
1.增量预训练的格式整理成data/pretrain里边中的txt格式就行嘛？除了清洗不需要其它处理嘛
2.如果我只有领域几本技术标准、专业书籍作为数据，这个数据量够嘛？一般设置多少epochs呀？怎么衡量增量预训练的东西是否记住了呀？

**Comment by nuoma** [comment]
1.是的。
2.参考类似的工作（链家的chathome），只要是预训练阶段没见过的就有帮助，但是要注意只是某个特定领域会被训偏（其他不相关领域会降分）。epoch最少的有看过1-2的，最多的有10（微软 text book is all you need）。针对于领域数据，用c-eval的方法去few shot做题目。

**Comment by dongteng** [comment]
多谢大佬
