### ISSUE TITLE
增加领域tokenizer之后进行pretrain阶段训练 是不是需要修改训练代码和参数

### ISSUE THREAD

**Issue by haoran1062** [shibing624/MedicalGPT#173]
### Describe the Question
Please provide a clear and concise description of what the question is.
您好，关于修改tokenizer后训练pretrain我有3个问题：
* 1.我根据wiki上[add tokenizer](https://github.com/shibing624/MedicalGPT/wiki/%E6%89%A9%E5%85%85%E4%B8%AD%E6%96%87%E8%AF%8D%E8%A1%A8) 合并了新的词表，在训练pretrain的时候是不是需要在[pretrain.py](https://github.com/shibing624/MedicalGPT/blob/main/pretraining.py#L629)这里添加
```
# resize to new tokenizer
    model_vocab_size = model.get_output_embeddings().weight.size(0)
    if model_vocab_size != len(tokenizer):
        print(f'model vocab size: {model_vocab_size} != tokenizer size: {len(tokenizer)} resize to tokenizer size...')
        model.resize_token_embeddings(len(tokenizer))
```
这样才能匹配新增的tokenizer 否则启动pretrain训练会在这里报错
* 2.在启动训练的时候是否需要添加 `--modules_to_save="embed_tokens,lm_head"` ([参考](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/557) )
* 3.还有就是发现修改tokenizer后训练loss很高 一开始`5.x` 后面train loss 降到`2.x` eval loss 还是`3.x~4` acc 大概是`0.3`，同样的数据集如果不修改tokenizer 训练的loss开始是`3`左右 训一段时间train loss到 `2.0`附近 eval loss差不多`2.9` acc 在`0.4`附近 (用baichuan13b)  我这边用的pretrain data 是wiki提到的的[中文公开语料](https://huggingface.co/datasets/Linly-AI/Chinese-pretraining-dataset) random choice 20% + 领域知识语料 一共大概2千万条数据，block size 1024, 每张卡batch size=4，4卡A100 80G 训练1.5epoch我看预估时间要 80+小时，这个训练速度正常么？ 根据您的经验预训练的话eval loss和acc大概到多少适合停止训练呢？

**Comment by shibing624** [comment]
1. 加词表后需要；
2. 加词表后需要；
3. 正常；loss到1.x

**Comment by haoran1062** [comment]
> 1. 加词表后需要；
> 2. 加词表后需要；
> 3. 正常；loss到1.x

感谢答疑解惑！再多问一句 chatglm修改tokenizer并训练pretrain和其他模型是一模一样的么 没有什么其他步骤吧？

**Comment by shibing624** [comment]
嗯

**Comment by shibing624** [comment]
updated： https://github.com/shibing624/MedicalGPT/wiki/%E6%89%A9%E5%85%85%E4%B8%AD%E6%96%87%E8%AF%8D%E8%A1%A8

**Comment by tuqingwen** [comment]
> ### Describe the Question
> Please provide a clear and concise description of what the question is. 您好，关于修改tokenizer后训练pretrain我有3个问题：
> 
> * 1.我根据wiki上[add tokenizer](https://github.com/shibing624/MedicalGPT/wiki/%E6%89%A9%E5%85%85%E4%B8%AD%E6%96%87%E8%AF%8D%E8%A1%A8) 合并了新的词表，在训练pretrain的时候是不是需要在[pretrain.py](https://github.com/shibing624/MedicalGPT/blob/main/pretraining.py#L629)这里添加
> 
> ```
> # resize to new tokenizer
>     model_vocab_size = model.get_output_embeddings().weight.size(0)
>     if model_vocab_size != len(tokenizer):
>         print(f'model vocab size: {model_vocab_size} != tokenizer size: {len(tokenizer)} resize to tokenizer size...')
>         model.resize_token_embeddings(len(tokenizer))
> ```
> 
> 这样才能匹配新增的tokenizer 否则启动pretrain训练会在这里报错
> 
> * 2.在启动训练的时候是否需要添加 `--modules_to_save="embed_tokens,lm_head"` ([参考](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/557) )
> * 3.还有就是发现修改tokenizer后训练loss很高 一开始`5.x` 后面train loss 降到`2.x` eval loss 还是`3.x~4` acc 大概是`0.3`，同样的数据集如果不修改tokenizer 训练的loss开始是`3`左右 训一段时间train loss到 `2.0`附近 eval loss差不多`2.9` acc 在`0.4`附近 (用baichuan13b)  我这边用的pretrain data 是wiki提到的的[中文公开语料](https://huggingface.co/datasets/Linly-AI/Chinese-pretraining-dataset) random choice 20% + 领域知识语料 一共大概2千万条数据，block size 1024, 每张卡batch size=4，4卡A100 80G 训练1.5epoch我看预估时间要 80+小时，这个训练速度正常么？ 根据您的经验预训练的话eval loss和acc大概到多少适合停止训练呢？

请问，您是针对baichuan做的

> ### Describe the Question
> Please provide a clear and concise description of what the question is. 您好，关于修改tokenizer后训练pretrain我有3个问题：
> 
> * 1.我根据wiki上[add tokenizer](https://github.com/shibing624/MedicalGPT/wiki/%E6%89%A9%E5%85%85%E4%B8%AD%E6%96%87%E8%AF%8D%E8%A1%A8) 合并了新的词表，在训练pretrain的时候是不是需要在[pretrain.py](https://github.com/shibing624/MedicalGPT/blob/main/pretraining.py#L629)这里添加
> 
> ```
> # resize to new tokenizer
>     model_vocab_size = model.get_output_embeddings().weight.size(0)
>     if model_vocab_size != len(tokenizer):
>         print(f'model vocab size: {model_vocab_size} != tokenizer size: {len(tokenizer)} resize to tokenizer size...')
>         model.resize_token_embeddings(len(tokenizer))
> ```
> 
> 这样才能匹配新增的tokenizer 否则启动pretrain训练会在这里报错
> 
> * 2.在启动训练的时候是否需要添加 `--modules_to_save="embed_tokens,lm_head"` ([参考](https://github.com/ymcui/Chinese-LLaMA-Alpaca/issues/557) )
> * 3.还有就是发现修改tokenizer后训练loss很高 一开始`5.x` 后面train loss 降到`2.x` eval loss 还是`3.x~4` acc 大概是`0.3`，同样的数据集如果不修改tokenizer 训练的loss开始是`3`左右 训一段时间train loss到 `2.0`附近 eval loss差不多`2.9` acc 在`0.4`附近 (用baichuan13b)  我这边用的pretrain data 是wiki提到的的[中文公开语料](https://huggingface.co/datasets/Linly-AI/Chinese-pretraining-dataset) random choice 20% + 领域知识语料 一共大概2千万条数据，block size 1024, 每张卡batch size=4，4卡A100 80G 训练1.5epoch我看预估时间要 80+小时，这个训练速度正常么？ 根据您的经验预训练的话eval loss和acc大概到多少适合停止训练呢？

请问，您这是基于baichuan做的词表扩充吗？另外有遇到下列问题吗？
Traceback (most recent call last):
  File "E:\MedicalGPT-main\pretraining.py", line 782, in <module>
    main()
  File "E:\MedicalGPT-main\pretraining.py", line 401, in main
    tokenizer = tokenizer_class.from_pretrained(tokenizer_name_or_path, **tokenizer_kwargs)
  File "D:\Anaconda\envs\Belle\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 917, in from_pretrained
    raise ValueError(
ValueError: Tokenizer class BaichuanTokenizer does not exist or is not currently imported.

**Comment by tuqingwen** [comment]
另外，在pretraining.py里将MODEL_CLASSES 中baichuan配成    "baichuan": (AutoConfig, AutoModelForCausalLM, BaichuanTokenizer),遇到下列问题：
TypeError: Old language model head is of type <class 'transformers_modules.Baichuan2-7b-chat.modeling_baichuan.NormHead'>, which is not an instance of <class 'torch.nn.modules.linear.Linear'>. You should either use a different resize function or make sure that `old_lm_head` are an instance of <class 'torch.nn.modules.linear.Linear'>.
