### ISSUE TITLE
使用deepspeed出现cuda out of memory问题，而且是在代码运行一部分的情况下出现的错误

### ISSUE THREAD

**Issue by loki1017** [shibing624/MedicalGPT#177]
### Describe the bug
这是我的参数详情，在run_sft.sh 提供的torchrun版本行不通的情况下，使用deepspeed进行多卡训练
gpu_vis=0,1
MASTER_PORT=2345
deepspeed  --include localhost:$gpu_vis --master_port $MASTER_PORT $base_dir /Work/Medical/supervised_finetuning.py \
    --deepspeed /Work/Medical/deepspeed_config.json \
    --model_type chatglm \
    --model_name_or_path /Work/pre_model/chatglm2-6b \
    --train_file_dir /Work/data_sets/IM \
    --validation_file_dir /Work/data_sets/IM \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --do_train \
    --do_eval \
    --use_peft True \
    --fp16 \
    --num_train_epochs 1 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 1000 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 4 \
    --output_dir outputs-sft-01 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True  \
    --max_eval_samples 1500
这是报错信息：
2023-08-23 14:11:34.791 | INFO     | __main__:main:920 - *** Train ***
Rank: 0 partition count [2] and sizes[(7411712, False)] 
Rank: 1 partition count [2] and sizes[(7411712, False)] 
  0%|                                                                                                                             | 1/77212 [00:01<21:59:53,  1.03s/it]tried to get lr value before scheduler/optimizer started stepping, returning lr=0
tried to get lr value before scheduler/optimizer started stepping, returning lr=0
{'loss': 5.7578, 'learning_rate': 0, 'epoch': 0.0}                                                                                                                     
{'loss': 5.4674, 'learning_rate': 5.035771249007384e-06, 'epoch': 0.0}                                                                                                 
{'loss': 5.2377, 'learning_rate': 6.99959614426009e-06, 'epoch': 0.0}                                                                                                  
{'loss': 5.6224, 'learning_rate': 8.069579900090606e-06, 'epoch': 0.0}                                                                                                 
{'loss': 5.1699, 'learning_rate': 8.80912082969134e-06, 'epoch': 0.0}                                                                                                  
{'loss': 5.7751, 'learning_rate': 9.374864529305328e-06, 'epoch': 0.0}                                                                                                 
  0%|                                                                                                                             | 50/77212 [00:09<3:37:06,  5.92it/s]
Traceback (most recent call last):████████████████████████████▋                                                                      | 338/750 [04:31<13:09,  1.92s/it]
  File "//Work/Medical/supervised_finetuning.py", line 962, in <module>
    main()
  File "//Work/Medical/supervised_finetuning.py", line 930, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop
    self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval)
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 2256, in _maybe_log_save_evaluate
    metrics = self.evaluate(ignore_keys=ignore_keys_for_eval)
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 2972, in evaluate
    output = eval_loop(
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 3187, in evaluation_loop
    preds_host = logits if preds_host is None else nested_concat(preds_host, logits, padding_index=-100)
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 116, in nested_concat
    return torch_pad_and_concatenate(tensors, new_tensors, padding_index=padding_index)
  File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 81, in torch_pad_and_concatenate
    result = tensor1.new_full(new_shape, padding_index)
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 31.53 GiB (GPU 1; 79.15 GiB total capacity; 43.28 GiB already allocated; 31.47 GiB free; 46.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by shibing624** [comment]
update, 设置 --max_eval_samples 10

**Comment by loki1017** [comment]
我的训练集并没有设置max_train_samples，保留了原有的数据样本量，大约有20W条左右。那么max_eval_samples设置这么少会不会起不到验证效果呢？

**Comment by shibing624** [comment]
你先跑通逻辑，初步验证效果，可以用1000条。

**Comment by wxue1995** [comment]
> ### Describe the bug
> 这是我的参数详情，在run_sft.sh 提供的torchrun版本行不通的情况下，使用deepspeed进行多卡训练 gpu_vis=0,1 MASTER_PORT=2345 deepspeed --include localhost:$gpu_vis --master_port $MASTER_PORT $base_dir /Work/Medical/supervised_finetuning.py --deepspeed /Work/Medical/deepspeed_config.json --model_type chatglm --model_name_or_path /Work/pre_model/chatglm2-6b --train_file_dir /Work/data_sets/IM --validation_file_dir /Work/data_sets/IM --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --do_eval --use_peft True --fp16 --num_train_epochs 1 --learning_rate 2e-5 --warmup_ratio 0.05 --weight_decay 0.05 --logging_strategy steps --logging_steps 10 --eval_steps 50 --evaluation_strategy steps --save_steps 1000 --save_strategy steps --save_total_limit 3 --gradient_accumulation_steps 1 --preprocessing_num_workers 4 --output_dir outputs-sft-01 --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --target_modules all --lora_rank 8 --lora_alpha 16 --lora_dropout 0.05 --torch_dtype float16 --device_map auto --report_to tensorboard --ddp_find_unused_parameters False --gradient_checkpointing True --max_eval_samples 1500 这是报错信息： 2023-08-23 14:11:34.791 | INFO | **main**:main:920 - *** Train *** Rank: 0 partition count [2] and sizes[(7411712, False)] Rank: 1 partition count [2] and sizes[(7411712, False)] 0%| | 1/77212 [00:01<21:59:53, 1.03s/it]tried to get lr value before scheduler/optimizer started stepping, returning lr=0 tried to get lr value before scheduler/optimizer started stepping, returning lr=0 {'loss': 5.7578, 'learning_rate': 0, 'epoch': 0.0} {'loss': 5.4674, 'learning_rate': 5.035771249007384e-06, 'epoch': 0.0} {'loss': 5.2377, 'learning_rate': 6.99959614426009e-06, 'epoch': 0.0} {'loss': 5.6224, 'learning_rate': 8.069579900090606e-06, 'epoch': 0.0} {'loss': 5.1699, 'learning_rate': 8.80912082969134e-06, 'epoch': 0.0} {'loss': 5.7751, 'learning_rate': 9.374864529305328e-06, 'epoch': 0.0} 0%| | 50/77212 [00:09<3:37:06, 5.92it/s] Traceback (most recent call last):████████████████████████████▋ | 338/750 [04:31<13:09, 1.92s/it] File "//Work/Medical/supervised_finetuning.py", line 962, in main() File "//Work/Medical/supervised_finetuning.py", line 930, in main train_result = trainer.train(resume_from_checkpoint=checkpoint) File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train return inner_training_loop( File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 1929, in _inner_training_loop self._maybe_log_save_evaluate(tr_loss, model, trial, epoch, ignore_keys_for_eval) File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 2256, in _maybe_log_save_evaluate metrics = self.evaluate(ignore_keys=ignore_keys_for_eval) File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 2972, in evaluate output = eval_loop( File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer.py", line 3187, in evaluation_loop preds_host = logits if preds_host is None else nested_concat(preds_host, logits, padding_index=-100) File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 116, in nested_concat return torch_pad_and_concatenate(tensors, new_tensors, padding_index=padding_index) File "/home/anaconda3/envs/loki/lib/python3.10/site-packages/transformers/trainer_pt_utils.py", line 81, in torch_pad_and_concatenate result = tensor1.new_full(new_shape, padding_index) torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 31.53 GiB (GPU 1; 79.15 GiB total capacity; 43.28 GiB already allocated; 31.47 GiB free; 46.99 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

你好，请问时使用的是什么环境，我是用qwen也报这样的错，谢谢啦
