### ISSUE TITLE
LORA SFT数据时，两T4卡共30G显存仍报OOM，与您参数介绍不一致

### ISSUE THREAD

**Issue by kkcondy** [shibing624/MedicalGPT#179]
### Describe the Question
Please provide a clear and concise description of what the question is.
torch.cuda.OutOfMemoryError    : new_value = value.to(device)CUDA out of memory. Tried to allocate 64.00 MiB (GPU 0; 14.58 GiB total capacity; 14.33 GiB already allocated; 55.62 MiB free; 14.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 64.00 MiB (GPU 1; 14.58 GiB total capacity; 14.33 GiB already allocated; 55.62 MiB free; 14.34 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 5102) of binary: /root/anaconda3/envs/transgpt/bin/python
Traceback (most recent call last):
  File "/root/anaconda3/envs/transgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/root/anaconda3/envs/transgpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/root/anaconda3/envs/transgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/root/anaconda3/envs/transgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/root/anaconda3/envs/transgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/root/anaconda3/envs/transgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

使用参数为CUDA_VISIBLE_DEVICES=1,2  torchrun --nproc_per_node 2 supervised_finetuning.py \
    --model_type llama \
    --model_name_or_path ./DUOMO-Lab/TransGPT-v0 \
    --train_file_dir ./data/finetune \
    --validation_file_dir ./data/finetune \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
    --do_train \
    --do_eval \
    --use_peft True \
    --fp16 \
    --max_train_samples 100 \
    --max_eval_samples 1 \
    --num_train_epochs 1 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 4 \
    --output_dir ./outputs-sft-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True

**Comment by shibing624** [comment]
torchrun是数据并行，你显存不够。改为CUDA_VISIBLE_DEVICES=1,2 python supervised_finetuning.py 。。。 执行
