### ISSUE TITLE
预训练用了哪些数据集，“数据集wiki”和“Dataset”的表述似乎有歧义

### ISSUE THREAD

**Issue by Pycelle** [shibing624/MedicalGPT#182]
老师您好！您在“数据集wiki”中提到使用了100G的预训练语料，
![1693157553161](https://github.com/shibing624/MedicalGPT/assets/58674597/d14d0560-4de1-4174-825e-37df7803e1d0)
但是在Readme中指出使用了以下预训练语料，请问实际使用了多少呢？因为我发现部分英文数据集无法下载到了
![image](https://github.com/shibing624/MedicalGPT/assets/58674597/80331f8e-3345-42af-932f-075d61eb4782)
最后如果使用的是前者100G的语料，70G的英文，20G的中文，这样的数据占比会对中文生成能力有正面还是负面影响呢？

**Comment by shibing624** [comment]
fixed，开源的没有100GB，已经修改为16GB

**Comment by Pycelle** [comment]
好的谢谢老师，那没有使用纯英文语料预训练，最后模型的英文生成表现会变弱吗
