### ISSUE TITLE
sft阶段eval_loss不降反升

### ISSUE THREAD

**Issue by invokerbyxv** [shibing624/MedicalGPT#183]
### Describe the Question
Please provide a clear and concise description of what the question is.

用ChatGLM2-6B做sft，训练集数量6912条，验证集是独立的768条。
这种情况是验证集数量太多吗？并且验证集不适合用独立的数据？

![微信图片_20230828172535](https://github.com/shibing624/MedicalGPT/assets/43714368/9e6961a5-3735-4b26-a563-328aeb2f708d)

**Comment by shibing624** [comment]
这是正常的， 取3000个step的结果就可以。
