### ISSUE TITLE
关于领域知识增量预训练、指令微调的疑惑

### ISSUE THREAD

**Issue by Pycelle** [shibing624/MedicalGPT#184]
您好！使用领域知识做增量预训练时，如果所用的预训练模型比如"中文LLaMA"已经学习过百科类文档类数据集，有必要将领域知识跟其他百科类文档类数据集合并再一起训练吗？指令微调所涉及的领域知识是不是应该出自增量预训练所用知识呢？

**Comment by shibing624** [comment]
1. 纯百科的没必要加；
2. 需要，避免遗忘；
3. 是

**Comment by Pycelle** [comment]
好的谢谢~
