### ISSUE TITLE
ChatGLM-6B不能进行RLHF训练和DPO训练吗？为什么到第三阶段都报错。

### ISSUE THREAD

**Issue by lk202010** [shibing624/MedicalGPT#185]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
![Q1](https://github.com/shibing624/MedicalGPT/assets/73419811/e21ad1da-2fc8-45e3-94cd-dc53672da231)
![q2](https://github.com/shibing624/MedicalGPT/assets/73419811/28331d58-8f17-4749-af44-b41d305b5f11)

**Comment by shibing624** [comment]
see https://github.com/shibing624/MedicalGPT/wiki/FAQ
