### ISSUE TITLE
在用llama2指令微调时，train_loss会先下降几个epoch，然后变为0,eval_loss一直为nan

### ISSUE THREAD

**Issue by yzw-yzw** [shibing624/MedicalGPT#186]
用的是作者这个文档中的finetune数据集，还加了几千条，参数如下
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 supervised_finetuning.py \
    --model_type llama \
    --model_name_or_path /hy-tmp/Llama-2-7b-hf\
    --train_file_dir ./data/finetune \
    --template_name alpaca \
    --per_device_train_batch_size 20 \
    --per_device_eval_batch_size 20 \
    --do_train \
    --do_eval \
    --use_peft True \
    --fp16 \
    --num_train_epochs 2 \
    --learning_rate 2e-6 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --model_max_length 512 \
    --output_dir outputs-sft-v1 \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 16 \
    --lora_alpha 32 \
    --lora_dropout 0.05 \
    --torch_dtype float32 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True

**Comment by dividez** [comment]
learning_rate 有可能太大了，不断调小，直到不出现 nan为止
