### ISSUE TITLE
继续预训练疑问

### ISSUE THREAD

**Issue by tianyunzqs** [shibing624/MedicalGPT#187]
### Describe the Question
Please provide a clear and concise description of what the question is.

1.如果想基于llama2用领域数据continue pretrain，那是不是还需要做sft啊？
2.如果只做continue pretrain 和sft是不是也可以具备chat能力啊（不做后续的reward和RL）？
3.如果continue pretrain用领域数据，sft用开源通用数据集是否可行呢？

**Comment by shibing624** [comment]
1.是
2.chat能力是SFT提供的；
3. 是

**Comment by tianyunzqs** [comment]
> 1.是 2.chat能力是SFT提供的； 3. 是

感谢大佬回复，再问几个问题啊~。
1.如果我用开源通用sft数据集微调经过领域数据continue pretrain的模型后，模型会不会遗忘领域知识啊？
2.如果直接基于chinese-llama2-chat类的模型用领域数据continue pretrain后，还需要做sft吗？（chinese-llama2-chat类模型也具备chat能力）

**Comment by shibing624** [comment]
1. 只有领域数据会，补充通用数据一起训练；
2. 需要，chat能力是sft提供的；
3. few shot

---
提问前翻翻有没有类似的issue。
