### ISSUE TITLE
Doubts about incremental pretraining

### ISSUE THREAD

**Issue by Aniketto16** [shibing624/MedicalGPT#188]
Hello! Thank you for your great work! 

1. I want to train model over Japanese office documents, should I merge my domain data with other Japanese general data for incremental pretraining step?   
2. For the SFT stage how I don't have any domain level instructions, can I only use general data sources ? 

Thank you in advance!

**Comment by shibing624** [comment]
1. yes
2. if only use general data, you get a general chat model, not domain model.
