### ISSUE TITLE
关于预训练的超参数设置问题

### ISSUE THREAD

**Issue by berton820** [shibing624/MedicalGPT#189]
您好，在您的项目给定的范例pt代码中显然为demo代码而非真实release模型版本的训练参数
```
CUDA_VISIBLE_DEVICES=0,1 torchrun --nproc_per_node 2 pretraining.py \
    --model_type bloom \
    --model_name_or_path bigscience/bloomz-560m \
    --train_file_dir ./data/pretrain \
    --validation_file_dir ./data/pretrain \
    --per_device_train_batch_size 4 \
    --per_device_eval_batch_size 4 \
...
...
```

在我能找到的相关issues上，您说真实项目采用了8卡V100训练了一周的时间
https://github.com/shibing624/MedicalGPT/issues/17#issuecomment-1592939997

我的问题是
1. 是否方便提供您真实二次训练的batch size，学习率，梯度累积量，lora rank等参数设置。比如说在此项目中训练模型采用的参数https://github.com/shibing624/MedicalGPT/releases/tag/0.2.0
2. 通常意义上lora训练是在qkv上挂在小矩阵进行训练，您是否认为在mlp层挂载lora在pt阶段能更加贴合全参数pt的效果。（可能通常认为在mlp阶段挂在lora的化侵入性较强？但是pt本身就需要整体模型变化吧？这点其实比较困惑）
3. 想知道您内部有无消融实验，例如base模型SFT后，lora PT后的模型再经过SFT，以及full PT后的模型再经过SFT的效果差距，或者是按照您的经验，他们的差距会是怎么样的。（比如说100分满分，三者得分可能是 70:85:90，或者70:75:90这类的）

**Comment by shibing624** [comment]
1. 具体参数在对应的model card里面有写：https://huggingface.co/shibing624/ziya-llama-13b-medical-lora 
<img width="519" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/10249622/17683f1f-d41b-4f13-bf7b-3c6a09365d8e">

2. 参考QLoRA的paper
3. 用lora是因为机器不够，如果我机器够可以用全参训练。对比效果我记得belle有个技术报告有写，大概结论是Full SFT + lora SFT效果最好
