### ISSUE TITLE
PT+SFT+DPO显存问题

### ISSUE THREAD

**Issue by ZzzybEric** [shibing624/MedicalGPT#190]
### Describe the Question
Please provide a clear and concise description of what the question is.
按顺序走PT+SFT+DPO微调链路，发现显存占用越来越高，比如在做PT和SFT时，单卡显存能够支持运行，而在做DPO时，显存oom，请问这是什么原因

**Comment by shibing624** [comment]
正常，DPO需要加载两遍模型。加机器。

**Comment by YueMing-github** [comment]
dpo 有一个policy model 和 reference model

解决方案是 开deepspeed 的 zero3，虽然通信开销1.5倍，但是多卡(k)时， 显存为1/k
