### ISSUE TITLE
用deepspeed 全参训练chatglm2 报错

### ISSUE THREAD

**Issue by wjy3326** [shibing624/MedicalGPT#191]
### Describe the bug
报错信息如下：
Traceback (most recent call last):
  File "/home/wjy/PycharmProjects/MedicalGPT-main/supervised_finetuning.py", line 945, in <module>
    main()
  File "/home/wjy/PycharmProjects/MedicalGPT-main/supervised_finetuning.py", line 916, in main
    train_result = trainer.train(resume_from_checkpoint=checkpoint)
  File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train
    return inner_training_loop(
  File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1633, in _inner_training_loop
    self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps)
  File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/deepspeed.py", line 343, in deepspeed_init
    hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps)
  File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/deepspeed.py", line 220, in trainer_config_finalize
    raise ValueError(
ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
- ds fp16.enabled=True vs hf fp16|fp16_full_eval+fp16_backend(amp)=False
The easiest method is to set these DeepSpeed config values to 'auto'.

训练参数如下：
CUDA_VISIBLE_DEVICES=1,2,3,7 deepspeed  --master_port 2241 supervised_finetuning.py \
    --model_type  chatglm \
    --template_name chatglm2 \
    --model_name_or_path /home/wjy/models/chatglm2-6b-32k \
    --train_file_dir   data/finetune/train/ \
    --validation_file_dir  data/finetune/dev \
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \
    --do_train \
    --do_eval \
    --overwrite_cache \
    --use_peft False \
    --num_train_epochs 100 \
    --learning_rate 2e-5 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 50 \
    --save_strategy steps \
    --save_total_limit 5000 \
    --gradient_accumulation_steps 4 \
    --preprocessing_num_workers 4 \
    --output_dir outputs-chatglm2_32k_zhenhuan_full_deepspeed \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --torch_dtype float16 \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True \
    --deepspeed deepspeed_config.json > chatglm2_32k_zhenhuan_full_deepspeed.log

deepspeed配置参数没有改动。
请问是什么问题呢

**Comment by tjb-tech** [comment]
> ### Describe the bug
> 报错信息如下： Traceback (most recent call last): File "/home/wjy/PycharmProjects/MedicalGPT-main/supervised_finetuning.py", line 945, in main() File "/home/wjy/PycharmProjects/MedicalGPT-main/supervised_finetuning.py", line 916, in main train_result = trainer.train(resume_from_checkpoint=checkpoint) File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1555, in train return inner_training_loop( File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/trainer.py", line 1633, in _inner_training_loop self.optimizer, self.lr_scheduler = deepspeed_init(self, num_training_steps=max_steps) File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/deepspeed.py", line 343, in deepspeed_init hf_deepspeed_config.trainer_config_finalize(args, model, num_training_steps) File "/home/wjy/software/anaconda3/envs/nlp/lib/python3.10/site-packages/transformers/deepspeed.py", line 220, in trainer_config_finalize raise ValueError( ValueError: Please correct the following DeepSpeed config values that mismatch TrainingArguments values:
> 
> * ds fp16.enabled=True vs hf fp16|fp16_full_eval+fp16_backend(amp)=False
>   The easiest method is to set these DeepSpeed config values to 'auto'.
> 
> 训练参数如下： CUDA_VISIBLE_DEVICES=1,2,3,7 deepspeed --master_port 2241 supervised_finetuning.py --model_type chatglm --template_name chatglm2 --model_name_or_path /home/wjy/models/chatglm2-6b-32k --train_file_dir data/finetune/train/ --validation_file_dir data/finetune/dev --per_device_train_batch_size 1 --per_device_eval_batch_size 1 --do_train --do_eval --overwrite_cache --use_peft False --num_train_epochs 100 --learning_rate 2e-5 --warmup_ratio 0.05 --weight_decay 0.05 --logging_strategy steps --logging_steps 10 --eval_steps 50 --evaluation_strategy steps --save_steps 50 --save_strategy steps --save_total_limit 5000 --gradient_accumulation_steps 4 --preprocessing_num_workers 4 --output_dir outputs-chatglm2_32k_zhenhuan_full_deepspeed --overwrite_output_dir --ddp_timeout 30000 --logging_first_step True --torch_dtype float16 --report_to tensorboard --ddp_find_unused_parameters False --gradient_checkpointing True --deepspeed deepspeed_config.json > chatglm2_32k_zhenhuan_full_deepspeed.log
> 
> deepspeed配置参数没有改动。 请问是什么问题呢
请问解决了，相同的问题🙋
