### ISSUE TITLE
SFT是否使用了全部的240万条中英文医疗数据集

### ISSUE THREAD

**Issue by JiangTanZJU** [shibing624/MedicalGPT#192]
### Describe the Question
Release Models  [shibing624/ziya-llama-13b-medical-merged](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged)的Introduction提到：在240万条中英文医疗数据集[shibing624/medical](https://huggingface.co/datasets/shibing624/medical)上SFT微调了一版Ziya-LLaMA-13B模型。

240万条中英文医疗数据集中只有2.07M的finetune数据， 请问finetune时是只使用了这2.07M的finetune数据吗，有用到362k的pretrain数据或者其他的额外数据吗？

**Comment by shibing624** [comment]
只用了SFT，2M就是200万。

**Comment by JiangTanZJU** [comment]
谢谢解答。那readme中“在240万条中英文医疗数据集[shibing624/medical](https://huggingface.co/datasets/shibing624/medical)上SFT微调了一版Ziya-LLaMA-13B模型，医疗问答效果有提升，发布微调后的完整模型权重(单轮对话)”

写成

”在240万条中英文医疗数据集[shibing624/medical](https://huggingface.co/datasets/shibing624/medical)上，使用其中的2.07M rows的finetune数据SFT微调了一版Ziya-LLaMA-13B模型，医疗问答效果有提升，发布微调后的完整模型权重(单轮对话)“

看上去似乎会更明确一些。”在240万条中英文医疗数据集上SFT微调了一版Ziya-LLaMA-13B模型“好像用了全部的240万数据一样。

**Comment by JiangTanZJU** [comment]
还想请教一下大佬，[shibing624/ziya-llama-13b-medical-lora](https://huggingface.co/shibing624/ziya-llama-13b-medical-lora)和[shibing624/vicuna-baichuan-13b-chat-lora](https://huggingface.co/shibing624/vicuna-baichuan-13b-chat-lora)这两个checkpoint的微调过程中，有做过扩充词表的操作吗。

因为我在SFT过程中，经常会print一连串的\<unk\>，这个是正常的吗？是不是需要先扩充词表才行，例如：
`| DEBUG    | __main__:main:896 - Decode labels[0]: <unk><unk><unk><unk><unk><unk><unk><unk><unk>`

**Comment by shibing624** [comment]
1. 没扩充词表，原因是2个模型都是前人已经做过中文适配了；
2. 正常。

**Comment by shibing624** [comment]
https://github.com/shibing624/MedicalGPT/wiki/%E6%89%A9%E5%85%85%E4%B8%AD%E6%96%87%E8%AF%8D%E8%A1%A8
