### ISSUE TITLE
使用deepspeed stage 3全参数SFT加载模型参数为空

### ISSUE THREAD

**Issue by jiangtann** [shibing624/MedicalGPT#193]
### Describe the bug
使用[Ziya-LLaMA-13B-v1](https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1) 作为基模型，参考https://github.com/shibing624/MedicalGPT/issues/46#issuecomment-1676182910 修改supervised_finetuning.py和deepspeed_config.json，运行sh run_sft.sh脚本，发现load模型后模型参数为空。

使用pdb调试，如下图所示：
![image](https://github.com/shibing624/MedicalGPT/assets/39088437/86f3883d-a6d7-4ccf-b007-100b6d47ef34)

如果不使用deepspeed则不会出现该现象，请问应该如何解决。

**Comment by shibing624** [comment]
使用lora，deepspeed zero3的模型保存逻辑需要单写，可以参考fastchat改下。
![image](https://github.com/shibing624/MedicalGPT/assets/10249622/52d99e5c-3abf-4699-a2ac-8855c0712750)

https://github.com/lm-sys/FastChat/blob/main/fastchat/train/train_lora.py
