### ISSUE TITLE
SFT时evaluate会卡住

### ISSUE THREAD

**Issue by JiangTanZJU** [shibing624/MedicalGPT#194]
### Describe the bug
运行sh run_sft.sh进行微调时，使用pdb调试，发现会卡在https://github.com/shibing624/MedicalGPT/blob/main/supervised_finetuning.py#L913 这一行，但是evaluation_strategy能正常执行，即每过eval_steps步后的evaluate又是能正常运行的。

卡住的时候0号显卡的利用率一直是100%，看起来像是卡在torch.distributed的进程通信了一样，其他显卡显存占用大部分为0。

**Comment by shibing624** [comment]
多卡调试，我不清楚。
