### ISSUE TITLE
使用baichuan13B模型在medical数据集上sft会报错

### ISSUE THREAD

**Issue by JiangTanZJU** [shibing624/MedicalGPT#195]
### Describe the Question
使用[baichuan-inc/Baichuan-13B-Chat](https://huggingface.co/baichuan-inc/Baichuan-13B-Chat)模型在[shibing624/medical](https://huggingface.co/datasets/shibing624/medical)数据集上sft会报错：

Token indices sequence length is longer than the specified maximum sequence length for this model (4450 > 4096). Running this sequence through the model will result in indexing errors

说明medical数据集中有sample长度大于4096，但我疑惑的是，为什么用[IDEA-CCNL/Ziya-LLaMA-13B-v1](https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1)模型在[shibing624/medical](https://huggingface.co/datasets/shibing624/medical)数据集上sft不会报错，我看[IDEA-CCNL/Ziya-LLaMA-13B-v1](https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1)模型的config.json里写着`max_position_embeddings : 2048`，应该意思就是context长度最大2048，按理来说也应该报错吧？

**Comment by shibing624** [comment]
百川的代码是百川自己写的，ziya的代码是依赖hf的，hf的context逻辑处理更完善一些。

fix方法：1. 手动处理数据；2.换别的base模型训练。
