### ISSUE TITLE
pretrain阶段只调整线性层的参数是有什么考虑吗

### ISSUE THREAD

**Issue by zhangyu68** [shibing624/MedicalGPT#197]
### Describe the Question
Please provide a clear and concise description of what the question is.

请问pretrain阶段只调整线性层的参数是有什么考虑吗，是算力的考虑，还是有什么认知或者其他考虑在里面呢？

**Comment by shibing624** [comment]
lora作用于dense层。

**Comment by zhangyu68** [comment]
可能我没描述清楚，想问的就是在pretrain训练时，为什么使用lora调整dense层参数，而不是调整全参数。 之前看到过帖子说知识存储于Linear层，但是没有啥实验数据支撑

**Comment by shibing624** [comment]
看下lora的paper  https://arxiv.org/abs/2106.09685 ，我简单说：
1. LoRA 主要处理线性层，因为在 Transformer 中，线性层承担了大部分参数和计算负担，慢就慢在线性层的计算量大；
2. LoRA是使用低秩矩阵来近似原始模型中的线性层，从而减少参数数量和计算复杂度。公式是对线性层的处理，别的也不好低秩处理；非线性层（如激活函数）或卷积层无法用LoRA进行压缩和加速
