### ISSUE TITLE
rl_training和reward_modeling中Tokenizer新增Pad token，Model不需要resize吗？

### ISSUE THREAD

**Issue by baibaiw5** [shibing624/MedicalGPT#20]
standford_alpaca新增Pad token时需要
![image](https://github.com/shibing624/MedicalGPT/assets/233871/05503c3d-b619-45f5-9c8e-20fe08a82a53)

rl_training.py和reward_modeling.py，新增Pad token，无resize model操作
![image](https://github.com/shibing624/MedicalGPT/assets/233871/4669c799-e41e-4572-b9de-309afd94d041)

**Comment by shibing624** [comment]
都不需要resize，而且pad_token_id 可以设为0，避免数组越界问题。

resize token size 的操作建议放merge_adapter_model.py 里面做。
