### ISSUE TITLE
chatglm2增量预训练

### ISSUE THREAD

**Issue by MKD1** [shibing624/MedicalGPT#202]
### Describe the Question
Please provide a clear and concise description of what the question is.
看到chatglm2可以使用自回归进行增量预训练，做了一个12w的领域数据集（每行大概200个token）去尝试，但感觉pretrain完成后模型没有学到领域知识（eval数据的loss还在3.0左右），在测试的时候没有生成出领域的相关文本，并且出现了重复某一段话的情况。
我的问题是
1.  重复某一段话是因为block size切分后模型经常会预测到最大限制长度吗？还是没有用SFT微调就都会出现这种情况。
2. 对于增量预训练的话，一般增量的数据大概要满足什么规模才能学到呢，通用预料占比20%可以吗？
3. 我的预想流程是 领域数据+通用数据 预训练，通用数据SFT后进行下游任务，这样是正常的流程吧？

**Comment by tuqingwen** [comment]
楼上，想请教一下你做增量预训练的数据集是什么形式的呢？领域是哪个方向？（是与项目里txt文本形式一样？）

**Comment by shibing624** [comment]
1. 重复大多数情况是loss没有收敛，训练没有拟合好导致，可以在训练时取前几个steps的checkpoint推理看到；
2. 数据配比没有太科学的依据，我建议通用语料占比80%+，因为领域语料一般质量不高，数据比较脏；
3. 是，但一般只做SFT也能get领域知识，而且一般的领域知识（如医学、法律）base大模型是学到过的。

**Comment by zhaoxin-L** [comment]
> 1. 重复大多数情况是loss没有收敛，训练没有拟合好导致，可以在训练时取前几个steps的checkpoint推理看到；
> 2. 数据配比没有太科学的依据，我建议通用语料占比80%+，因为领域语料一般质量不高，数据比较脏；
> 3. 是，但一般只做SFT也能get领域知识，而且一般的领域知识（如医学、法律）base大模型是学到过的。

对于您说的第一点，如何才能有效降低loss呢？我用的是chatglm2，数据量大概30w，参数只改了这三个值，其他参数与项目一致
    --per_device_train_batch_size 1 \
    --per_device_eval_batch_size 1 \

**Comment by shibing624** [comment]
降低loss跟你的调参有啥关系？per_device_train_batch_size 不能设为1，最少是2。换高质量训练集才能降。

**Comment by zhaoxin-L** [comment]
> 降低loss跟你的调参有啥关系？per_device_train_batch_size 不能设为1，最少是2。换高质量训练集才能降。

好的，感谢。我再试试

**Comment by sevenandseven** [comment]
> ### Describe the Question
> Please provide a clear and concise description of what the question is. 看到chatglm2可以使用自回归进行增量预训练，做了一个12w的领域数据集（每行大概200个token）去尝试，但感觉pretrain完成后模型没有学到领域知识（eval数据的loss还在3.0左右），在测试的时候没有生成出领域的相关文本，并且出现了重复某一段话的情况。 我的问题是
> 
> 1. 重复某一段话是因为block size切分后模型经常会预测到最大限制长度吗？还是没有用SFT微调就都会出现这种情况。
> 2. 对于增量预训练的话，一般增量的数据大概要满足什么规模才能学到呢，通用预料占比20%可以吗？
> 3. 我的预想流程是 领域数据+通用数据 预训练，通用数据SFT后进行下游任务，这样是正常的流程吧？

你好，关于你的数据集的概述，我想请教一下，你是怎么计算出，每行大概多少个token的？

**Comment by sevenandseven** [comment]
> 降低loss跟你的调参有啥关系？per_device_train_batch_size 不能设为1，最少是2。换高质量训练集才能降。

请问 batch size为什么不能是1，最少是2？

**Comment by shibing624** [comment]
在深度学习中，batch size 表示模型在训练过程中一次性处理的样本数量。通常情况下，batch size 可以是 1，但是这样会增加训练的不稳定性。这是因为在这种情况下，梯度的计算将只基于单个样本，这可能导致模型收敛困难。当 batch size 设置为 2 或更大时，模型可以更稳定地学习样本之间的统计特征，有助于更有效地更新模型参数，因此一般建议将 batch size 设置为至少 2。
