### ISSUE TITLE
Regarding data size 

### ISSUE THREAD

**Issue by Aniketto16** [shibing624/MedicalGPT#203]
Thank you for your hard work!
I want to confirm following : 
1. What should be pretraining data size, I have currently : ~2 million tokens
2. What should be SFT data size, I have currently : ~1000 conversations 

I also see that after performing both steps the model seems to output factually wrong information, how can I improve ?

**Comment by shibing624** [comment]
1. 2 million tokens is ok
2. domain dataset: 1000 conversations is a small dataset, add https://huggingface.co/datasets/shibing624/sharegpt_gpt4 data, merge your domain data with it. then training SFT.

**Comment by Aniketto16** [comment]
Thank you! I will close the issue now!
