### ISSUE TITLE
使用Ziya-LLaMA-13B-v1 作为基模型lora sft时爆显存

### ISSUE THREAD

**Issue by jiangtann** [shibing624/MedicalGPT#205]
### Describe the bug
sft脚本如下：
~~~sh
torchrun --nproc_per_node 8 supervised_finetuning.py \
    --model_type llama \
    --model_name_or_path /mnt/afs/user/jiangtan/data/Ziya-LLaMA-13B-v1 \
    --train_file_dir ./data/finetune/medical \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --use_peft True \
    --fp16 \
    --max_train_samples 1000 \
    --max_eval_samples 10 \
    --num_train_epochs 10 \
    --learning_rate 2e-5 \
    --warmup_ratio 0 \
    --weight_decay 0 \
    --logging_strategy steps \
    --logging_steps 50 \
    --eval_steps 50 \
    --save_steps 500 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 100 \
    --output_dir outputs/ziya \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step False \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing False \
    --cache_dir ./cache \
~~~

环境如下：
transformers==4.29.0        （试过4.30也一样）
peft==0.4.0        （0.5.0版本会报错ImportError: cannot import name 'is_npu_available' from 'accelerate.utils'）
accelerate==0.20.3
显卡为：A800/80G

只有在https://github.com/shibing624/MedicalGPT/blob/main/supervised_finetuning.py#L836 后加`.half()`后才能正常训练。
比较疑惑的是，https://huggingface.co/IDEA-CCNL/Ziya-LLaMA-13B-v1/blob/main/config.json 这里写着`"torch_dtype": "float16"`，按理来说就是以float16加载模型的，不需要加.half()，请问您有遇到过这个问题吗？

**Comment by shibing624** [comment]
1. 显存不够，可以加model.half()
2. gradient_checkpointing True 可以开启，省显存

**Comment by jiangtann** [comment]
在`model.from_pretrained`的时候，已经把模型的config文件传进去了，参考这一行https://github.com/shibing624/MedicalGPT/blob/main/supervised_finetuning.py#L825 ，可以确定`config.torch_dtype`为`torch.float16`。

所以求大佬解答：为什么通过`model.from_pretrained`load好模型后，查看`model.dtype`仍为`torch.float32`呢，按理来说config应该生效，不需要自己手动加`.half()`吧。

**Comment by shibing624** [comment]
see https://github.com/huggingface/transformers/blob/main/src/transformers/modeling_utils.py#L2230C10-L2230C10 如果torch_dtype='auto' 默认用的config的torch_dtype, 否则用指定的。
