### ISSUE TITLE
关于sft的超参数设置问题

### ISSUE THREAD

**Issue by jiangtann** [shibing624/MedicalGPT#207]
### Describe the Question

在复现大佬您得到的[ziya lora权重]([shibing624/ziya-llama-13b-medical-lora](https://huggingface.co/shibing624/ziya-llama-13b-medical-lora))过程中，发现loss曲线和您在model card里report的有些许不一致，大概差了10%左右。

查看相关issue，例如https://github.com/shibing624/MedicalGPT/issues/189#issuecomment-1700586420 ，还是没能找到您所使用的比较完整的训练超参。

目前我主要有这么几个问题，希望您能解答：
1. 您在sft阶段几个和显存相关的重要参数为：

> per_device_train_batch_size=8 (来自[model card](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged#training-details))
> gradient_checkpointing=false (来自[model card](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged#training-details))
> deepspeed=null (来自[model card](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged#training-details))
> fp16=true (来自[run_sft.sh](https://github.com/shibing624/MedicalGPT/blob/main/run_sft.sh#L11C13-L11C13))

但当我使用单节点8张A800/80G显存的环境来跑sft时，batch_size=8显存是不够的，我只能将batch_size改成4才能跑通sft。看https://github.com/shibing624/MedicalGPT/issues/17#issuecomment-1592939997 您说跑pt的时候用的是8卡V100，请问您sft时也用的是8卡V100吗？按理来说，llama 13B，以float16的精度光是load到显存中，就已经需要占用13*2=26G显存了，为什么您用batch_size=8能跑通呢？您跑sft时，是否使用了qlora、load_in_8bit、deepspeed等省显存的方法呢？

2. lora相关的参数没有在[model card](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged#training-details)中展示出来，您跑sft时lora的相关参数是否和[run_sft](https://github.com/shibing624/MedicalGPT/blob/main/run_sft.sh)中一致呢？例如：

> lora_rank=8 (来自[run_sft.sh](https://github.com/shibing624/MedicalGPT/blob/main/run_sft.sh#L32))
> target_modules="all" (来自[run_sft.sh](https://github.com/shibing624/MedicalGPT/blob/main/run_sft.sh#L31))

3. [model card](https://huggingface.co/shibing624/ziya-llama-13b-medical-merged#training-details)中提到，您使用的`num_train_epochs=10`。但是看您的loss曲线，发现横轴停在66k steps的位置，参考[数据集](https://huggingface.co/datasets/shibing624/medical)发现finetune的数据总共有2.07M条，因为您使用的是`per_device_train_batch_size=8`，那么可以推算，您使用的卡数为：

> 2070000 * 10 / 8 / 66000 = 40张

感觉不太对劲，您在sft Ziya的时候，是使用的medical数据集里面完整的2.07M条finetune数据训练了10个epoch吗？

**Comment by shibing624** [comment]
1. 用了lora；
2. lora_rank=16；target_modules="all"
3. 设置的num_train_epochs=10，跑SFT,一周8卡V100，loss降不下去了，停了，大概2个epochs。

**Comment by shibing624** [comment]
https://huggingface.co/shibing624/vicuna-baichuan-13b-chat-lora#%E8%AE%AD%E7%BB%83%E6%95%B0%E6%8D%AE%E9%9B%86 可以参考这个，如果机器支持的话，用qlora

**Comment by jiangtann** [comment]
感谢您的解答，对于问题1，我还有点问题。因为我也是按照model card和run_sft.sh里的设置，用了lora，但未使用qlora、load_in_8bit、deepspeed等，在batch_size=8的情况下，80G显存是不够用的。

V100是32G显存，如果只用了lora的话，Ziya-13B batch_size=8的sft似乎是跑不起来的，您当时用了qlora吗？

**Comment by shibing624** [comment]
--gradient_checkpointing True

**Comment by jiangtann** [comment]
https://huggingface.co/shibing624/ziya-llama-13b-medical-merged#training-details  里面的training args提到

![image](https://github.com/shibing624/MedicalGPT/assets/39088437/673711db-f679-4da9-8161-78e655ca0f8d)

实际上您gradient_checkpointing使用的是True吗？

**Comment by shibing624** [comment]
是True。
