### ISSUE TITLE
基于chatglm训练reward model是使用AutoModelForSequenceClassification加载模型吗

### ISSUE THREAD

**Issue by wang9702** [shibing624/MedicalGPT#21]
感谢分享，基于chatglm训练reward model时使用AutoModelForSequenceClassification加载模型报错如图
![image](https://github.com/shibing624/MedicalGPT/assets/52562761/d6ded778-5d80-43ca-b932-354b6db2345e)，加载模型的类用错了吗？

**Comment by shibing624** [comment]
chatglm 官方不支持SequenceClassification，我也没写。

**Comment by yangliuIOC** [comment]
> chatglm 官方不支持SequenceClassification，我也没写。

你好， 我训练的rw发现对所有句子打分都是负数？。。。

**Comment by shibing624** [comment]
> > chatglm 官方不支持SequenceClassification，我也没写。
> 
> 你好， 我训练的rw发现对所有句子打分都是负数？。。。

自己训练的reward model吗？ 数据集label是啥样，对啥句子打分是负数
