### ISSUE TITLE
合并缺少py文件

### ISSUE THREAD

**Issue by ZzzybEric** [shibing624/MedicalGPT#210]
作者你好，之前看到有人提出过类似问题，但是我好奇的是 为什么我之前微调时没有遇到过缺少py这种情况，现在出现了这种情况，除了copy py之外，还有别的解决方法吗

**Comment by ZzzybEric** [comment]
出现问题前后，本地代码没有修改过

**Comment by shibing624** [comment]
还有别的解决方法是什么意思？copy py文件不行吗？

**Comment by ZzzybEric** [comment]
你好，copy py文件是可以的哈，我就是好奇为什么之前微调和merge的时候不用copy py文件，最近突然出现了这个问题
