### ISSUE TITLE
为什么全参sft时需要将模型转为fp32

### ISSUE THREAD

**Issue by jiangtann** [shibing624/MedicalGPT#212]
### Describe the Question
https://github.com/shibing624/MedicalGPT/blob/main/supervised_finetuning.py#L871
请问为什么全参sft时需要将模型转为fp32？

**Comment by shibing624** [comment]
半精度训练过程中loss会变0

**Comment by wangrx33** [comment]
可是为什么设置torch_dtype=float32之后，全参sft，用deep speed zero2，loss也会中途变成0？
