### ISSUE TITLE
大佬，rl_training.py中的prompt文字为啥只取偶数位的

### ISSUE THREAD

**Issue by laiqinghan** [shibing624/MedicalGPT#219]
### Describe the Question
Please provide a clear and concise description of what the question is.

        for prompt in get_prompt(examples):
            for i in range(len(prompt) // 2):
                **source_txt = prompt[2 * i]**
                tokenized_question = tokenizer(
                    source_txt, truncation=True, max_length=max_source_length, padding="max_length",
                    return_tensors="pt"
                )
                new_examples["query"].append(source_txt)
                new_examples["input_ids"].append(tokenized_question["input_ids"])

**Comment by laiqinghan** [comment]
<img width="650" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/22470281/1b1e1582-cfd3-49ef-a70c-e6a00e455f71">

**Comment by shibing624** [comment]
取的是query，格式是：
0   问
1 答
2 问
3 答

所以去偶数的。
