### ISSUE TITLE
最后两步的一些疑问

### ISSUE THREAD

**Issue by skepsun** [shibing624/MedicalGPT#22]
1. reward model脚本使用torchrun进行多卡训练，无论是否使用deepspeed都提示参数重复使用的问题。
2. rl脚本里的target_modules需要手动定义，无法像之前那样使用函数自动获取，示例notebook里没有定义target modules。
3. rl脚本似乎不支持deepspeed?我看trl库是有支持的，虽然看不明白怎么调用。

**Comment by shibing624** [comment]
1. reward model 还没兼容多卡训练；
2. rl脚本里的target_modules需要手动定义，手动写进去就行，示例没写target modules，也可以，是自动用默认的；
3. rl脚本我还没兼容deepspeed。
