### ISSUE TITLE
DPO

### ISSUE THREAD

**Issue by C929-x** [shibing624/MedicalGPT#226]
### Describe the Question
Please provide a clear and concise description of what the question is.

如何获得DPO数据

**Comment by shibing624** [comment]
reward dataset, https://github.com/shibing624/MedicalGPT#reward-model-datasets

**Comment by C929-x** [comment]
> reward dataset, https://github.com/shibing624/MedicalGPT#reward-model-datasets

如果训练一个垂直LLM，这个reward数据集可以直接用吗

**Comment by shibing624** [comment]
不能，这些是通用数据集，没有垂直数据集，一般是自建。

**Comment by C929-x** [comment]
> 不能，这些是通用数据集，没有垂直数据集，一般是自建。

好的谢谢
![image](https://github.com/shibing624/MedicalGPT/assets/125797225/9f93fc25-a7d1-4d2a-9d35-536f8aa97d6b)
如果要做医疗的dpo，是按照知乎数据集的格式吗
