### ISSUE TITLE
请问是否支持chatglm2-6b-32k？

### ISSUE THREAD

**Issue by LanHao0** [shibing624/MedicalGPT#228]
- [ x ] I checked to make sure that this is not a duplicate issue

### Describe the solution you'd like
如题，大佬你好，请问项目是否支持32k版本的chatglm2-6b?

**Comment by valkryhx** [comment]
就我个人经验而言，虽然微调代码不完全和本项目一样，但是原来跑8k版本的代码不用改直接可以用在32k的模型上。
不过有一点要注意，8k版本chatglm2源代码里面实现了modelforsequenceclassifaction 类，这个在32k的源码里面没有。如果你在RM或者RLHF阶段用到了这个类，那32k的代码就要自己实现这一部分。
