### ISSUE TITLE
运行run_rm.sh报错  RuntimeError: CUDA error: device-side assert triggered

### ISSUE THREAD

**Issue by Candy555** [shibing624/MedicalGPT#23]
基于llama13B 运行 run_rm.sh报错如下 数据集用的test.json也不行，单机多卡的环境下报错
 ../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [29,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [30,0,0] Assertion `srcIndex < srcSelectDimSize` failed.
../aten/src/ATen/native/cuda/Indexing.cu:1146: indexSelectLargeIndex: block: [420,0,0], thread: [31,0,0] Assertion `srcIndex < srcSelectDimSize` failed.

RuntimeError: CUDA error: device-side assert triggered
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

**Comment by shibing624** [comment]
set pad_token_id = 0, later i will fix it.
