### ISSUE TITLE
Chat模型训练问题

### ISSUE THREAD

**Issue by ozmemory** [shibing624/MedicalGPT#230]
### Describe the Question

Release models的介绍里，shibing624/vicuna-baichuan-13b-chat-lora的base是Baichuan-13B-Chat，请问是可以直接基于Chat模型而非base模型进行增量预训练吗？SFT的信息不会受影响吗？还是需要先用base模型做PT，然后再从头做SFT？

**Comment by shibing624** [comment]
都行，没那么多限制。
