### ISSUE TITLE
预训练的思路问题

### ISSUE THREAD

**Issue by J-G-Y** [shibing624/MedicalGPT#231]
感谢作者的分享，新人想和您请教一个问题
我所理解的领域数据注入，如下两种：
1.原文：领域数据注入。input：领域[MASK]注入。output：**数据**。然后做loss，回传更新梯度
2.原文：领域数据注入，然后有监督微调。input：领域数据注入，[MASK]。output:然后有监督微调。然后做loss，回传更新梯度。
我调试代码发现了您在构造数据时候，有如下代码：
result["labels"] = result["input_ids"].copy()
但是我在阅读pretrain.py的代码时并没有发现又MASK 的相关代码，想和您请教一下您实现领域数据注入的具体原理是什么，即loss时怎么样计算的

**Comment by shibing624** [comment]
next word prediction task, is all the same for GPT training.
