### ISSUE TITLE
使用chinese-llama-alpaca 7b进行dpo训练报错，求教！

### ISSUE THREAD

**Issue by Everyday-seu** [shibing624/MedicalGPT#233]
我直接在您的huggingface上下载的chinese-llama-alpaca进行dpo训练，没有pt和sft，
报的错误是：
Trying to set a tensor if shape torch.Size([49953,4096]) in "weight" (which has shape torch.Size([49954,4096]))
据我之前的经验，这是因为alpaca比llama多了一个token？
想请教一下这个报错怎么解决，感谢！

**Comment by shibing624** [comment]
resize embeddings first
