### ISSUE TITLE
训练loss在每个epoch之后都会突然下降

### ISSUE THREAD

**Issue by jiangtann** [shibing624/MedicalGPT#234]
### Describe the Question
Please provide a clear and concise description of what the question is.

![image](https://github.com/shibing624/MedicalGPT/assets/39088437/f8a8a1d0-56a8-4788-8403-bf2bae5bf58b)

全参sft InternLM-7B模型时，训练loss会在每个epoch之后突然下降。
这好像是微调LLM时一个普遍发生的现象。

但看很多LLM的预训练过程，loss曲线并不长这样，有什么方法可以避免这样的loss曲线吗？

**Comment by shibing624** [comment]
二次预训练，这样loss是正常的，对训练数据的拟合变高。
