### ISSUE TITLE
inference.py和gradio_demo.py结果不一致

### ISSUE THREAD

**Issue by ozmemory** [shibing624/MedicalGPT#238]
### Describe the Question
模型：基于Baichuan2-13B-Chat 做qlora SFT并融合后的模型（加载时用了4bit量化）
问题：
1. 使用inference.py进行推理，微调数据中的一些问题可以正确回答，但是使用gradio_demo.py推理，回答的结果就像完全没微调过一样。请问是有什么配置需要添加吗？
2. 这个模型使用gradio_demo时，答案只显示了第一个词，然后这个词也消失了，回答的一栏最后就完全没结果。在代码里加log的话，后面的词其实是有正常生成的，只是不知为何没正常显示到web页面。我切换到原版的Baichuan2-13B-Chat也是一样。

**Comment by shibing624** [comment]
gradio_demo可能有点问题，我看下
