### ISSUE TITLE
求教！chinese-llama2 7B DPO训练时loss=0，eval=nan

### ISSUE THREAD

**Issue by Everyday-seu** [shibing624/MedicalGPT#239]
使用的是项目自带的医疗数据集，基座模型是chinese-llama 7B，直接跑DPO时遇到这个问题，请问该如何解决呀大佬

![4e9b3297e5617b0f78106cf5e5cbc50](https://github.com/shibing624/MedicalGPT/assets/53171458/bcbaea82-2f83-45c8-b98e-15b1fa7ac7e3)
![f3f45a5edb34ec6977a6ce319d849bf](https://github.com/shibing624/MedicalGPT/assets/53171458/8ab31b04-cfcf-448c-a568-1195e992d93f)
![53354be16f55d8077a3faac0b12634d](https://github.com/shibing624/MedicalGPT/assets/53171458/6fa559df-82d3-4929-8e33-7c153f92dc95)

**Comment by shibing624** [comment]
改为bfloat16或者float32

**Comment by Everyday-seu** [comment]
感谢大佬回答！首先尝试了float32，但是在2卡3090 24GB上报cuda out of memory的错误
所以尝试了bfloat16，loss不会一直是0了，但有时还是会变成0，且eval一直是nan，请问这该怎么解决呢？

![1fe4b367655558e9c1fd66127fdbaea](https://github.com/shibing624/MedicalGPT/assets/53171458/eb5c653d-cc28-429e-b5a6-91be1130185d)

**Comment by tszslovewanpu** [comment]
我也遇到了这个问题，eval一直是nan，训练loss先震荡后变成0，随后一直是0

**Comment by shibing624** [comment]
使用 --bf16

**Comment by tszslovewanpu** [comment]
删去--fp16，然后将参数torch_dtype设成float32可以吗

**Comment by shibing624** [comment]
> 删去--fp16，然后将参数torch_dtype设成float32可以吗

可
