### ISSUE TITLE
dataset bug help

### ISSUE THREAD

**Issue by YJSoooooo** [shibing624/MedicalGPT#242]
我在sft阶段遇到这个问题 ：datasets.arrow_writer.SchemaInferenceError: Please pass `features` or at least one example when writing data

datasets==2.14.6

transformers==4.33.2

sft微调参数：

CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc_per_node 4 supervised_finetuning.py \

  --deepspeed deepspeed_zero_stage2_config.json \

  --model_type baichuan \

  --model_name_or_path /data1/llm_base/baichuan7b \

  --train_file_dir ./data/finetune/gpt_train_data.jsonl \

  --validation_file_dir ./data/finetune/gpt_val_data.jsonl \

  --per_device_train_batch_size 16 \

  --per_device_eval_batch_size 4 \

  --do_train \

  --do_eval \

  --use_peft True \

  --fp16 \

  --num_train_epochs 1 \

  --learning_rate 2e-5 \

  --warmup_ratio 0.05 \

  --weight_decay 0.05 \

  --logging_strategy steps \

  --logging_steps 10 \

  --eval_steps 50 \

  --evaluation_strategy steps \

  --save_steps 1000 \

  --save_strategy steps \

  --save_total_limit 3 \

  --gradient_accumulation_steps 16 \

  --preprocessing_num_workers 4 \

  --output_dir outputs-sft-baichuan-v1 \

  --overwrite_output_dir \

  --ddp_timeout 30000 \

  --logging_first_step True \

  --target_modules all \

  --lora_rank 8 \

  --lora_alpha 16 \

  --lora_dropout 0.05 \

  --torch_dtype float16 \

  --device_map auto \

  --report_to tensorboard \

  --ddp_find_unused_parameters False \

  --gradient_checkpointing True \

  --cache_dir ./cache

数据集格式： 

![image-20231026160805687](C:\Users\jiash\AppData\Roaming\Typora\typora-user-images\image-20231026160805687.png)

大佬可以帮忙看看是哪出错了吗  求助

**Comment by YJSoooooo** [comment]
数据集格式是这样的
![image](https://github.com/shibing624/MedicalGPT/assets/125850867/f7127b17-31d9-4b87-a25a-80d9a5075150)

**Comment by YJSoooooo** [comment]
文件夹如下
![image](https://github.com/shibing624/MedicalGPT/assets/125850867/9e0b22db-dce5-45de-b8c3-92433007ec56)

**Comment by shibing624** [comment]
--train_file_dir ./data/finetune/

**Comment by shibing624** [comment]
参考run_sft.sh

**Comment by shibing624** [comment]
会划分

**Comment by YJSoooooo** [comment]
那白明白 谢谢大佬
