### ISSUE TITLE
指定--use_peft False 为全参训练(要移除 --fp16 )，需要移除 --torch dtype bfloat16 吗

### ISSUE THREAD

**Issue by SoYuCry** [shibing624/MedicalGPT#243]
### Describe the Question
Please provide a clear and concise description of what the question is.

如题，不太理解 --fp16 和 --torch dtype bfloat16 的区别

**Comment by shibing624** [comment]
fp16对应 torch_dtype float16; bf16对应的是bfloat16。

**Comment by SoYuCry** [comment]
不好意思，图贴错了。全参训练需要移除 --torch_dtype bfloat16 吗？

![image](https://github.com/shibing624/MedicalGPT/assets/87529679/2a3f23ef-e570-453d-b7a8-b91dc66024b2)

**Comment by shibing624** [comment]
自己试就知道了。

**Comment by tszslovewanpu** [comment]
> fp16对应 torch_dtype float16; bf16对应的是bfloat16。

我的理解：
torch_dtype flot16，对应fp16
torch_dtype bfloat16，对应bf16
那torch_dtype flot32，是不是要对应于fp32？

**Comment by shibing624** [comment]
是。

不过没fp32，默认是float32
