### ISSUE TITLE
数据集的划分问题，是否需要手动划分 train 和 val

### ISSUE THREAD

**Issue by SoYuCry** [shibing624/MedicalGPT#244]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
我在 https://github.com/shibing624/MedicalGPT/issues/242 里看到 会划分 train 和 val，但是在实际的代码中，我注意到没有划分。
![微信图片_20231030160219](https://github.com/shibing624/MedicalGPT/assets/87529679/e68a5fac-61be-48d1-94e6-38a07496be91)

**Comment by shibing624** [comment]
删除--validation_file_dir ，自动划分

**Comment by SoYuCry** [comment]
1、如果不删除 --validation_file_dir 手动划分是可以用的吗？like：
    --train_file_dir ./data/pretrain/train \
    --validation_file_dir ./data/pretrain/test \

2、需要设置测试集吗？比如以8:1:1 的比例分配 train：test：val（不确定大模型中 pretrain 的比例）

**Comment by shibing624** [comment]
1. 可以；
2. 需要；不懂逻辑就看代码。

**Comment by SoYuCry** [comment]
您好，仔细 debug 了一下代码。没有看到划分测试集的代码，只看到了划分 train_dataset 和 eval_dataset
