### ISSUE TITLE
RL强化学习训练后，模型合并时报错，前面的步骤完全按pipeline命令，

### ISSUE THREAD

**Issue by PICOPON** [shibing624/MedicalGPT#251]
### 4卡机器， 前面的步骤完全按pipeline命令
python merge_peft_adapter.py --model_type bloom \
    --base_model_name_or_path merged-sft --peft_model_path outputs-rl-v1 --output_dir merged-rl/

![image](https://github.com/shibing624/MedicalGPT/assets/49949166/6b45978d-793c-4529-9395-a89a15f84bbe)

**Comment by shibing624** [comment]
训练中出错？ 可能是显存不足，分到2个卡了，收到改掉device="auto"  -》   device="cuda:0"强制分到一个gpu卡跑
