### ISSUE TITLE
关于原始百川的infer

### ISSUE THREAD

**Issue by nuoma** [shibing624/MedicalGPT#26]
### Describe the Question
您好，我下载了百川7B，尝试使用您的代码做infer：

python inference.py     --model_type llama     --base_model ../baichuan/model      --with_prompt     --interactive

但是出来的结果是乱码：
Input:登鹳雀楼->王之涣
夜雨寄北->Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.

Response:  , (;s ,’  and as& out' — question for “ - boxâ said ””, business ‘， "',,” always’,¦ ' ;—,%, sort,,,, ),,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,

而使用这个代码则没有这个问题：
#tokenizer = AutoTokenizer.from_pretrained("./model", trust_remote_code=True)
#model = AutoModelForCausalLM.from_pretrained("./model", device_map="auto", trust_remote_code=True,load_in_8bit=True)
inputs = tokenizer('登鹳雀楼->王之涣\n夜雨寄北->', return_tensors='pt')
inputs = inputs.to('cuda:0')
pred = model.generate(**inputs, max_new_tokens=64,repetition_penalty=1.1)
print("First Question:\n",tokenizer.decode(pred.cpu()[0], skip_special_tokens=True))

### Describe your attempts
- [ x] I walked through the tutorials
- [ x] I checked the documentation
- [ x] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
去掉 --with_prompt ， 没做sft就不需要prompt

**Comment by nuoma** [comment]
谢谢解答，但是我用 python inference.py     --model_type llama     --base_model ../baichuan/model        --interactive

得到的结果是：
Input:北京是
Setting `pad_token_id` to `eos_token_id`:2 for open-end generation.
Response:  北京是-. GSG pup: t gTs s1g  ( C T fren—-. up-c-apm-eviner不需要 followed-..ta---.-p.--hest..-..-t.很快...-号.-il-...... Be........all...........--....-...-..l.8...-.. in. until..............any.........................der............................明alled..................oul..irts.......or...... be.....ore................................... eight.......9.............ber..able..................三分.................................ides..............3......................................

**Comment by shibing624** [comment]
Input:登鹳雀楼->王之涣

你可以先了解base model 和SFT后的模型的区别。用few-shot测试base model

**Comment by shibing624** [comment]
更新代码，template_name=baichuan-chat兼容原版模型推理。
