### ISSUE TITLE
大佬能帮我看看loss吗，Train 的loss一直在下降，eval的loss 触底猛反弹

### ISSUE THREAD

**Issue by SoYuCry** [shibing624/MedicalGPT#260]
### Describe the Question
Please provide a clear and concise description of what the question is.
如题，我应该选择哪一个位置的权重呢？谢谢大佬！
![image](https://github.com/shibing624/MedicalGPT/assets/87529679/35d8af07-8d07-4edd-8a07-8d674d064888)

**Comment by shibing624** [comment]
loss只是参考，选测试得分最高的checkpoint。
