### ISSUE TITLE
baichuan2的chat template

### ISSUE THREAD

**Issue by w5688414** [shibing624/MedicalGPT#262]
### Describe the Question
Please provide a clear and concise description of what the question is.

我看了一下baichuan2的chat template。https://github.com/shibing624/MedicalGPT/blob/474b32c352423b4051dbf07b53cd6d585f7ab41e/supervised_finetuning.py#L562C18-L562C30
reserved_106是从哪里来的，我在官方的代码里面没找到。https://huggingface.co/baichuan-inc/Baichuan2-7B-Chat/blob/main/modeling_baichuan.py

**Comment by shibing624** [comment]
仔细看下。   https://huggingface.co/baichuan-inc/Baichuan2-13B-Chat/blob/main/modeling_baichuan.py#L801
