### ISSUE TITLE
【数据集】Alpaca 和 Vicuna 两个 Template 之间有什么不同

### ISSUE THREAD

**Issue by SoYuCry** [shibing624/MedicalGPT#268]
### Describe the Question
Please provide a clear and concise description of what the question is.

想请教一下，Alpaca 和 Vicuna 这两个模板在格式上有什么不一样吗
<img width="880" alt="8c02ec49d8af69ef7649be418e021e9" src="https://github.com/shibing624/MedicalGPT/assets/87529679/c0e4152a-35ed-4734-8c9c-7382c4a07f14">

我了解到的是：相较于Alpaca，Vicuna在训练中将序列长度由512扩展到了2048，并且数据是从 ShareGPT.com 来的，而 Alpaca 的数据是从 GPT 3.5 来的。

Alpaca 是 instruction，input，output
Vicuna 是 User，assitant，User，assitant ...

一方面长度不同，另一方面是 Vicuna 没有 instruction 部分？

**Comment by shibing624** [comment]
1.system prompt不同；
2.格式不同

**Comment by shibing624** [comment]
vicuna也有system prompt.
