### ISSUE TITLE
Error(s) in loading state_dict for {}:\n\t{}'.format( RuntimeError: Error(s) in loading state_dict for PeftModelForSequenceClassification

### ISSUE THREAD

**Issue by waycup7** [shibing624/MedicalGPT#271]
Hello ,I get an error at reward_modeling(adapter_model) marge base model. 

error message:

 File "/home/airuser/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2152, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for PeftModelForSequenceClassification:
        size mismatch for base_model.model.score.modules_to_save.default.weight: copying a param with shape torch.Size([1, 5120]) from checkpoint, the shape in current model is torch.Size([2, 5120]).
        
 thanks for help.

**Comment by shibing624** [comment]
update code.
