### ISSUE TITLE
num_train_epochs这个参数好像只在训练的.sh文件中出现，在代码中没有出现过？

### ISSUE THREAD

**Issue by erichuazhou** [shibing624/MedicalGPT#287]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

num_train_epochs本意是控制训练的epoch数量，但是num_train_epochs这个参数好像只在训练的.sh文件中出现，在代码中搜索不到？
@shibing624

**Comment by shibing624** [comment]
执行不会报错的。看下transformers的Trainer源码。
