### ISSUE TITLE
是用zero2进行pt时，出现ValueError: `--mixed_precision` arg cannot be set to `bf16` when `fp16` is set in the DeepSpeed config file.

### ISSUE THREAD

**Issue by erichuazhou** [shibing624/MedicalGPT#288]
### Describe the Question
Please provide a clear and concise description of what the question is.
是用zero2进行pt时，出现ValueError: `--mixed_precision` arg cannot be set to `bf16` when `fp16` is set in the DeepSpeed config file.

请问大捞，应该如何正确设置？
谢谢。

@shibing624

**Comment by shibing624** [comment]
提示不是写了吗，deepspeed的config改下，要么都用bf16.
