### ISSUE TITLE
关于合并词表的疑问

### ISSUE THREAD

**Issue by awmthink** [shibing624/MedicalGPT#289]
看提供的词表合并的代码，只是将sp model中的pieces进行了合并；从我对bpe这样的算法理解上，模型里除了词表外，应该还包括merge规则信息吧，对于unigram算法，应该还有subword的概率吧，这些信息不需要更新到target的tokenizer中的吗？

**Comment by shibing624** [comment]
pt阶段训练，会更新

**Comment by awmthink** [comment]
> pt阶段训练，会更新

大佬是不是理解错我的问题了，继续预训练阶段不会再训练tokenizer吧（模型embedding会被训练），词表一旦合并完了，tokenizer应该就不会动了吧

**Comment by shibing624** [comment]
PT阶段加上--modules_to_save embed_tokens,lm_head
