### ISSUE TITLE
合并词表后运行pt报错

### ISSUE THREAD

**Issue by tuqingwen** [shibing624/MedicalGPT#290]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
![Uploading 屏幕截图 2023-12-17![屏幕截图 2023-12-17 220658](https://github.com/shibing624/MedicalGPT/assets/103909737/68bcb6fe-be7a-4de8-9663-c9ecc9ce741a)220600.png…]()
（设备是4090）

**Comment by tuqingwen** [comment]
![屏幕截图 2023-12-17 220600](https://github.com/shibing624/MedicalGPT/assets/103909737/5a6eac2a-4193-409e-916d-8a4c544e326b)
![屏幕截图 2023-12-17 220658](https://github.com/shibing624/MedicalGPT/assets/103909737/caa3e1c4-b879-4318-b686-6add17050509)

**Comment by shibing624** [comment]
安装 pip install peft==0.6.0
