### ISSUE TITLE
跑DPO的时候出现下面的问题。

### ISSUE THREAD

**Issue by LanShanPi** [shibing624/MedicalGPT#298]
跑dpo的时候出现下面的问题：
![WechatIMG227](https://github.com/shibing624/MedicalGPT/assets/58167546/ff9af66e-a001-43bf-98da-a87257721722)
其中上图中红色框是下面这张图中红框的输出：
![WechatIMG228](https://github.com/shibing624/MedicalGPT/assets/58167546/e45b6221-4b4b-4c75-be28-ebf21d411057)
第二张图所在文件为：
/XXX/XXX/miniconda3/envs/medical/lib/python3.9/site-packages/trl/trainer/utils.py

从输出的数据来看，错误是因为列表中出现了None值，导致torch.LongTensor()出错，我没有改变数据，然后用的是chatglm3-6b的模型。

**Comment by shibing624** [comment]
用llama类gpt结构的模型跑dpo

**Comment by LanShanPi** [comment]
这样啊，好吧，谢谢啦

**Comment by lx86110** [comment]
> 用llama类gpt结构的模型跑dpo

dpo不支持chatglm吗

**Comment by wxue1995** [comment]
> 用llama类gpt结构的模型跑dpo

你好，使用qwen-chat版本不行吗
