### ISSUE TITLE
colab乱码，求大佬解答

### ISSUE THREAD

**Issue by small-white-zs** [shibing624/MedicalGPT#299]
/
大佬，我运行您colab的代码的时候，乱码了，
![Uploading 1704540301190.png…]()
正常是您的这样
![Uploading 1704540342999.jpg…]()

**Comment by small-white-zs** [comment]
![1704540301190](https://github.com/shibing624/MedicalGPT/assets/99191955/10b02ac2-b652-448a-b8b9-76ddfa75c544)
![Uploading 1704540342999.jpg…]()

**Comment by small-white-zs** [comment]
![Uploading 1704540342999.jpg…](https://github.com/shibing624/MedicalGPT/assets/99191955/b3ef1eff-e9da-4359-9e46-b4d3a8c9066a)

**Comment by small-white-zs** [comment]
![Uploading 屏幕截图 2024-01-06 193302.png…]()

**Comment by small-white-zs** [comment]
![屏幕截图 2024-01-06 193302](https://github.com/shibing624/MedicalGPT/assets/99191955/233acfdd-e4eb-473a-9525-46e8bd4901fc)

**Comment by shibing624** [comment]
没有乱码，最后有文本。可以打开--group_by_length True 就没有padding操作。

**Comment by small-white-zs** [comment]
大佬好，我没表述清楚，后面的第二张截图是您正常运行时的截图（有文本的），第一张截图是我的（出错的）。
然后按照您的方法加了--group_by_length True 后
![屏幕截图 2024-01-06 201657](https://github.com/shibing624/MedicalGPT/assets/99191955/fc651f57-2e11-4ffe-853b-2b7bbc2843bc)

**Comment by shibing624** [comment]
https://github.com/shibing624/MedicalGPT/commit/3a7922a600cd044d698d290cb9c4e6d6c5d2d85a fixed

**Comment by shibing624** [comment]
https://github.com/shibing624/MedicalGPT/commit/9c9eaf16ac9287124f70edc2edb1827b43440c2f updated.
