### ISSUE TITLE
gradio_demo.py

### ISSUE THREAD

**Issue by gaojing8500** [shibing624/MedicalGPT#30]
![image](https://github.com/shibing624/MedicalGPT/assets/20908110/c7a2d383-4c36-4867-a11c-3b5c858e7a57)

初步排查是 问题导致beamsearch出现CPU与GPU之间分开计算的问题
![image](https://github.com/shibing624/MedicalGPT/assets/20908110/7f3c5f76-32e4-4192-8e1d-34734642af1e)

**Comment by shibing624** [comment]
是最新代码吗？
