### ISSUE TITLE
大佬，reward_model的训练是不是也不支持chatglm。

### ISSUE THREAD

**Issue by LanShanPi** [shibing624/MedicalGPT#300]
### Describe the Question
Please provide a clear and concise description of what the question is.

**Comment by LanShanPi** [comment]
我在用chatglm3训练的时候，在下面这个图中绿色箭头的位置会出现维度问题。
<img width="619" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/58167546/cf389fa9-25d8-46fe-918f-fe0386df8adc">
<img width="978" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/58167546/77eddf80-8b3d-44de-8641-fa33c3786a7f">
不知道是不是数据处理问题，还是模型支不支持的问题。

**Comment by LanShanPi** [comment]
我在reward_modeling.py中加了关于chatglm相关的MODEL_CLASSES内容

**Comment by shibing624** [comment]
reward_model 不支持chatglm
