### ISSUE TITLE
使用 llama2-7b的模型调用 pretraining.py进行预训练之后，在使用 inference.py进行 inference 时--template_name应该填什么？

### ISSUE THREAD

**Issue by lljpwrs** [shibing624/MedicalGPT#302]
使用默认的 vicuna 的话，会报错，我尝试改成 llama 和 llama2都是一样的错：

Traceback (most recent call last):

File "inference.py", line 330, in <module>

main()

File "inference.py", line 252, in main

prompt_template = get_conv_template(args.template_name)

 "inference.py", line 94, in get_conv_template

return conv_templates[name]

KeyError: 'vicuna'

**Comment by shibing624** [comment]
pt训练后的模型无法chat作答，需要 sft 后才可以。
