### ISSUE TITLE
请问在进行增量预训练的时候，加载的模型必须是base模型吗，可以是微调过的chat模型吗?

### ISSUE THREAD

**Issue by listwebit** [shibing624/MedicalGPT#304]
大佬好，我想进行模型的增量预训练，又几个问想请教一下：
1.进行增量预训练的时候，加载的模型必须是base模型吗，可以是微调过的chat模型吗?
2.只要其他别的模型放出来权重，hf的bin格式的权重，是不是就可以进行增量预训练呢？
3.使用咱们得框架进行其他模型的增量预训练，怎么做呢，需要注意哪些事项呢？

请大佬回复，谢谢

**Comment by shibing624** [comment]
1.都可以；
2.看模型架构支持就可以，主要是transformers库支持；
3.看下wiki
