### ISSUE TITLE
这是为什么啊？!用指令SFT后，模型的回答都变得短了，短就算了，还不对， 新的内容没学习进去

### ISSUE THREAD

**Issue by Thunderltx** [shibing624/MedicalGPT#306]
### Describe the Question
Please provide a clear and concise description of what the question is.
数据集是shibing624/medical/train_zh_0.json
模型用的是baichuan
这是SFT后
![image](https://github.com/shibing624/MedicalGPT/assets/37621028/d0e7b2eb-2943-4933-bcd2-0e9fd0111754)
这是SFT前
![image (1)](https://github.com/shibing624/MedicalGPT/assets/37621028/938353c3-6bfb-4e72-b23f-51ce5488de5f)

**Comment by Thunderltx** [comment]
再补一句，不是全参，是LoRA

**Comment by shibing624** [comment]
看下wiki，加些通用数据。多训练几轮（eg:epochs=10)

**Comment by Thunderltx** [comment]
> 看下wiki，加些通用数据。多训练几轮（eg:epochs=10)

谢谢答复，不过SFT也要加通用的数据么

**Comment by shibing624** [comment]
是
