### ISSUE TITLE
模型inference输出不能复现

### ISSUE THREAD

**Issue by wangrx33** [shibing624/MedicalGPT#308]
### Describe the Question
Please provide a clear and concise description of what the question is.

我增量预训练了一个模型，昨天运行inference.py，测试了一些问题，回答的比较满意。
但是今天重新测试了一下，输出就完全变了，没有调整任何参数，回答不如昨天的版本。
请问这是什么原因？我检查了好像也不是随机数的问题，repetition_penlaty一直设置的是1.2。

**Comment by shibing624** [comment]
我不知道。。。
