### ISSUE TITLE
PPO的训练代码里，预处理函数把数据切成了单字，这是正常的吗？

### ISSUE THREAD

**Issue by chiquitita-101** [shibing624/MedicalGPT#312]
### Describe the Question
Please provide a clear and concise description of what the question is.
训练代码PPO
训练脚本：
![image](https://github.com/shibing624/MedicalGPT/assets/19623404/c02ace2c-4555-4734-9bc6-ff1fbf6eb736)

因为想用自己的数据；所以打印了一下预处理后的数据；结果如下：
![image](https://github.com/shibing624/MedicalGPT/assets/19623404/f4973865-4b8e-4246-9c84-31be464331ba)
第一条数据：[{'from': 'human', 'value': '治疗阳痿吃什么药呢？，性生活一直很正常的，但是这段时间感觉性欲变低了，有时勃起都感觉很困难，试过许多的方法都没效果，听朋友说我这种情况可能会是早泄，想知道治疗早泄的药物？'}, {'from': 'gpt', 'value': '男子早泄、早泄病症的再次发生，多由恣情纵欲，或青年误犯性交，至命门火衰，精气虚寒；或思量忧郁，伤损心脾；或因恐惧伤肾，也有因湿热下注，宗筋弛而痿的。但主要是肾阳虚衰而痿。肾阳为那身阳气之根本，有温煦形体，蒸化水液，增进围产生长发育等功能。肾阳虚衰则温煦失责，气化无权。因而再次发生畏寒肢冷，性机能减退。故见男子早泄不举或不坚，且伴发头晕目眩。'}]
加上vicuna的模板：A chat between a curious user and an artificial intelligence assistant.......；可以看到数据被切成了单字；

预处理代码里yield出来的是个字符串；所以导致了这样；是不是本来是要拿到用户prompt？这是正常的吗？
![image](https://github.com/shibing624/MedicalGPT/assets/19623404/81b57590-a88e-49c6-aa05-551711f40acf)

**Comment by shibing624** [comment]
数据集格式错误，看下示例咋写的，看下colab的。

**Comment by chiquitita-101** [comment]
![298511648-81b57590-a88e-49c6-aa05-551711f40acf](https://github.com/shibing624/MedicalGPT/assets/19623404/5581b963-5813-4ea3-87e8-7710bdf127cc)

如果是想要拿出用户的prompt；那这应该是个bug；
我画出来的这三行：第一行yield出来的是一个字符串；所以在下面两行取偶数索引的时候；取的不是对话里的偶数回合（用户query）；而是一个字符串里的偶数索引的字符。
因为我不确定这个是不是故意要切成单字，所以才这样问；如果不是，那应该是bug

**Comment by user2311717757** [comment]
我也遇到这个问题，感觉需要把get_prompt改成get_dialog
