### ISSUE TITLE
对pretraining阶段的数据加工有点疑问

### ISSUE THREAD

**Issue by hongyix** [shibing624/MedicalGPT#32]
感谢作者的项目，对pretraining的代码有点疑问：
1. 为什么制作训练集的时候是合并所有数据然后按照block_size进行切割？这样做的样本可能把一个完整的句子分割，相对于按照句子或者按行切割有什么好处或者优势？
2. 如果我想改成按照行切割或者句子切割该怎么改？

**Comment by shibing624** [comment]
1. 按block_size 切割是跟原始预训练一致；
2. 注释block size的逻辑就行，但可能需要引入pad token保持max length 对齐，不建议手动这样做。可以改下sft去掉prompt label = -100的逻辑，当正常做next word predication,去训练语言模型就行。
