### ISSUE TITLE
Question about hardware requirements - 关于硬件要求的问题

### ISSUE THREAD

**Issue by elieobeid7** [shibing624/MedicalGPT#325]
This [hardware requirement section](https://github.com/shibing624/MedicalGPT/blob/main/README_EN.md#hardware-requirement) isn't clear 

1. Does this table show RAM or hard disk space?  Or is it VRAM?
2. How much RAM and hard disk space is it recommended to use?
3. Which graphics card to use?
4. Is there a small model we can download on PC to develop locally before we upload it to the server?

---

这个硬件要求部分不清楚

1. 这个表格显示的是RAM（随机存取存储器）还是硬盘空间？
2. 建议使用多少RAM和硬盘空间？
3. 应该使用哪款显卡？
4. 有没有一个小型模型，我们可以在PC上下载来本地开发，然后再上传到服务器？

---
This question has been translated into Chinese by ChatGPT as I don't speak Chinese
这个问题已经被ChatGPT翻译成中文，因为我不会说中文。

**Comment by shibing624** [comment]
1. VRAM
2. 32G RAM cpu, and 200G disk
3. A100 or V100
4. you can use 6B or Qwen-1.8B: https://huggingface.co/Qwen/Qwen-1_8B

**Comment by elieobeid7** [comment]
Ok thank you.

**Comment by elieobeid7** [comment]
@shibing624 trying to run it on AWS EC2 p4d.24xlarge, it complains about Ampere GPU when doing  `sh run_pt.sh`

<img width="1764" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/660142/ec85a20e-c817-44e6-b83a-d0e8ac895532">

Only A100 processors are based on Ampere architecture. AWS have only p4d.24xlarge instances with A100

Does it run on p4d.24xlarge?

**Comment by shibing624** [comment]
use fp16
