### ISSUE TITLE
这个错误是因为训练的单条数据太长了吗？截断是不是修改配置就可以了？

### ISSUE THREAD

**Issue by zxx20231119** [shibing624/MedicalGPT#328]
### 是不是输入的单条训练数据过长导致的

Token indices sequence length is longer than the specified maximum sequence length for this model (12598 > 8192). Running this sequence through the model will result in indexing errors

**Comment by zxx20231119** [comment]
用的测试模型是qwen1_8B的，增量预训练测试

**Comment by shibing624** [comment]
设置block size,warning可以忽略。

**Comment by zxx20231119** [comment]
感谢
