### ISSUE TITLE
从peft加载LoraConfig报错

### ISSUE THREAD

**Issue by xiaohengDa** [shibing624/MedicalGPT#33]
### Describe the bug
执行from peft import LoraConfig, TaskType, get_peft_model, PeftModel, prepare_model_for_int8_training时报错
RuntimeError: 
        CUDA Setup failed despite GPU being available. Please run the following command to get more information:

        python -m bitsandbytes

        Inspect the output of the command and see if you can locate CUDA libraries. You might need to add them
        to your LD_LIBRARY_PATH. If you suspect a bug, please take the information from python -m bitsandbytes
        and open an issue at: https://github.com/TimDettmers/bitsandbytes/issues
同时提示找不到libcuda.so和libcudart.so文件

**Comment by shibing624** [comment]
自行check机器是否能正常安装bitsandbytes，安装后能否正常运行，不能就卸载了：`pip uninstall bitsandbytes`

**Comment by xiaohengDa** [comment]
> 自行check机器是否能正常安装bitsandbytes，安装后能否正常运行，不能就卸载了：`pip uninstall bitsandbytes`

卸载之后还是不行，然后我在我的cuda-lib这个目录里确实没看到libcuda.so和libcudart.so文件，但我的CUDA是正常安装的，之前跑chatGLM推理也是没有问题的

**Comment by shibing624** [comment]
去peft库问问
