### ISSUE TITLE
chatglm2-6b预训练合并权重后，推理加载，AttributeError: can't set attribute

### ISSUE THREAD

**Issue by weedon666** [shibing624/MedicalGPT#332]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
【预训练及lora合并后模型文件目录】
![image](https://github.com/shibing624/MedicalGPT/assets/135689911/d9589c4f-762f-4fa5-a9f7-8f6a89cd926d)

【报错信息】
![image](https://github.com/shibing624/MedicalGPT/assets/135689911/725af22d-f304-41bb-b19f-47a200d773a2)

【版本】
transformers              4.37.2

**Comment by shibing624** [comment]
看你报错里面用的chatglm3-6b-1

**Comment by weedon666** [comment]
是的，目录见图1。chatglm3-6b-1是我预训练合并后的模型
