### ISSUE TITLE
DPO阶段报错

### ISSUE THREAD

**Issue by small-white-zs** [shibing624/MedicalGPT#334]
ValueError: You passed both a ref_model and a peft_config. For training PEFT adapters with DPO there is no need to pass a reference model. Please pass `ref_model=None` in case you want to train PEFT adapters.

=
![屏幕截图 2024-02-29 104954](https://github.com/shibing624/MedicalGPT/assets/99191955/6a0a503f-3cb3-4717-b16b-c8d89339b90e)

**Comment by shibing624** [comment]
base模型是哪个？transformers，peft的版本也说下，描述下具体出现问题的过程，帮助我复现问题

**Comment by small-white-zs** [comment]
就是大佬github主页运行的副本colab

**Comment by shibing624** [comment]
哦哦，可能是peft新版本更新导致的问题，我重新跑下试试。

**Comment by small-white-zs** [comment]
麻烦了

**Comment by shibing624** [comment]
fixed.
