### ISSUE TITLE
大佬好，请教几个模型训练问题

### ISSUE THREAD

**Issue by xxyp** [shibing624/MedicalGPT#336]
### Describe the Question
1、增量预训练使用的是base模型吧？chat模型可以增量预训练吗，chat模型增量预训练会破坏chat的能力吗？
2、如果使用base模型进行增量预训练，sft的时候是不是得使用比较多的通用指令或者垂域数据重新进行指令微调才会有比较好的结果？

**Comment by shibing624** [comment]
1、PT可以用base、chat都行，chat模型继续PT会劣化其对齐能力，需要再SFT；
2. 是。

**Comment by xxyp** [comment]
嗯嗯好的，了解，感谢大佬~
