### ISSUE TITLE
assert tokenzier_vocab_size > model_vocab_size

### ISSUE THREAD

**Issue by sevenandseven** [shibing624/MedicalGPT#350]
### Describe the Question
Please provide a clear and concise description of what the question is.

Hello, during the process of using LORA to fine-tune the chatglm3 base model, an inconsistency problem between the model vocabulary and the tokenization vocabulary occurred during the merging process. How can I solve this?

**Comment by shibing624** [comment]
logger.info("Resize model embeddings to fit tokenizer")
base_model.resize_token_embeddings(tokenzier_vocab_size)

**Comment by sevenandseven** [comment]
“Okay, thank you for your reply.”

**Comment by sevenandseven** [comment]
![Image_20240320135926](https://github.com/shibing624/MedicalGPT/assets/63324925/d1be7d2a-87f8-45be-8a88-d7328055ec8b)

Using your method, new problems have emerged.

**Comment by shibing624** [comment]
手动改词表了吗？没改词表的话不会报tokenzier_vocab_size > model_vocab_size的问题，把transformers降级到4.28.1

**Comment by sevenandseven** [comment]
没有手动改词表，就是用的工程的run_pt使用的txt数据，对base模型进行二次微调的。我试试降低版本。
