### ISSUE TITLE
预训练后模型出现自问自答、输出未知序列、重复口吃现象

### ISSUE THREAD

**Issue by Peter-of-Astora** [shibing624/MedicalGPT#351]
![4预测问题、重复问题、未知字符问题](https://github.com/shibing624/MedicalGPT/assets/155410688/daa19668-f7c2-4657-beb3-de5eac2dfb12)

这个问题是出在哪里了呢？
如果我的预训练数据不是很多，我是不是应该调整一下LoRA的参数，让模型参数调整变少一点，具体可以怎么调整呢？

**Comment by shibing624** [comment]
1. 你这是把escape special tokens 打开了，关闭就好了；
2. 如果要调整lora参数，就调整r（要参数小就调小），rank是秩，也可以调小。

**Comment by Peter-of-Astora** [comment]
不好意思还想再问一下，escape special tokens是在哪里设置呀，configuration的文件里面吗
然后惩罚系数的话，具体是指哪个参数呀😂

**Comment by Peter-of-Astora** [comment]
是要把tokenizer文件里面的这个设置成True吗
![image](https://github.com/shibing624/MedicalGPT/assets/155410688/29b5ddd8-27df-4651-9f0a-64e6f97c7b56)

**Comment by Riapy** [comment]
> 1. escape special tokens

请问您解决了吗？我也遇到了这个问题

**Comment by Riapy** [comment]
> 是要把tokenizer文件里面的这个设置成True吗 ![image](https://private-user-images.githubusercontent.com/155410688/316002340-29b5ddd8-27df-4651-9f0a-64e6f97c7b56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NDY1NDIsIm5iZiI6MTcxMTU0NjI0MiwicGF0aCI6Ii8xNTU0MTA2ODgvMzE2MDAyMzQwLTI5YjVkZGQ4LTI3ZGYtNDY1MS05ZjBhLTY0ZTZmOTdjN2I1Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyN1QxMzMwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMjlmMDk3MWM4YzNhNDUzOTZjZDhlNTI1ZGY2YzJlYjA0ZTg1ZGFlNWI2ZTM2YzFhZWQwMjFjNWE5ZmU0OGQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hKEB5Y57UuxXwH2KrSyQr6A2YCp-6m7XT7FpkQKhqws)

请问您解决了吗？我也遇到了这个问题

**Comment by Peter-of-Astora** [comment]
惩罚系数是在这里：
https://github.com/THUDM/ChatGLM3/blob/main/basic_demo/web_demo_gradio.py#L139
在api的demo和gradio的demo里面都有这个参数，关于特殊字符的参数也在这里面。
我更改了参数后，发现依然存在以上问题。

最后解决的办法是，用少量（20K以下就行）的通用SFT数据进行训练，发现可以进行正常的交流：
![image](https://github.com/shibing624/MedicalGPT/assets/155410688/594ca2d4-d377-44d1-b0ed-cc376a5e2bd4)

所以应该是需要在增量预训练后进行能力恢复，就可以了。

**Comment by tszslovewanpu** [comment]
@Peter-of-Astora 
您好，请教您一下
i、请问你的解决办法是sft中只用20k条样例来训练吗？
ii、您的增量预训练用的样例数可以问一下吗？
我也出现了模型自问自答，甚至胡言乱语的情况，很头疼。。。
