### ISSUE TITLE
扩充词表后能否直接进行SFT呢？

### ISSUE THREAD

**Issue by HaotianLiu123** [shibing624/MedicalGPT#352]
### Describe the Question
Please provide a clear and concise description of what the question is.

请问扩充词表后能否直接进行SFT呢？如果可以的话，需要改变哪些参数么？

**Comment by kevinhonor** [comment]
我想是不可以的，扩充词表后，需要训练embed_token和lm_head，更新对应词的语义向量，即先需要pt，然后在进行sft，我觉得这样是比较好的

**Comment by HaotianLiu123** [comment]
好的，谢谢您了！
