### ISSUE TITLE
几步的训练怎么都是独立的，rm都没用sft的adapter

### ISSUE THREAD

**Issue by cqray1990** [shibing624/MedicalGPT#365]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

**Comment by shibing624** [comment]
可以用，可以不用。

**Comment by cqray1990** [comment]
> 可以用，可以不用。
用与不用如何判定呢，不用的话为什么还要去sft对齐呢？
@shibing624

**Comment by shibing624** [comment]
Reward Model是一个独立的模型
