### ISSUE TITLE
dpo_training.py eal存在空的情况

### ISSUE THREAD

**Issue by 14686039** [shibing624/MedicalGPT#369]
### Describe the bug
![Xnip2024-04-27_10-02-44](https://github.com/shibing624/MedicalGPT/assets/7911286/9f5b4130-3dda-4cb7-a3f6-360124858815)
![Xnip2024-04-27_10-03-48](https://github.com/shibing624/MedicalGPT/assets/7911286/4a90c5d1-e69b-49ab-92bd-f15d8d9585d4)

**Comment by shibing624** [comment]
1.模型是啥？
2.看图2是已经跑了8个epoch了，再出现的问题吗？

**Comment by 14686039** [comment]
--per_device_train_batch_size 2 \



调整这个参数，可以了


                       
原始邮件
                       
                     

发件人："Ming Xu (徐明)"< ***@***.*** &gt;;

发件时间：2024/4/27 13:43

收件人："shibing624/MedicalGPT"< ***@***.*** &gt;;

抄送人："BZ"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [shibing624/MedicalGPT] dpo_training.py eal存在空的情况 (Issue #369)




 
1.模型是啥？
 2.看图2是已经跑了8个epoch了，再出现的问题吗？
