### ISSUE TITLE
奖励模型数据构造

### ISSUE THREAD

**Issue by ZTurboX** [shibing624/MedicalGPT#37]
奖励模型数据需要怎样构造呢

**Comment by shibing624** [comment]
最好是人工标注，格式参考示例jsonl

**Comment by ZTurboX** [comment]
> 最好是人工标注，格式参考示例jsonl

60亿参数全量训练，一台8卡的a100/h100够用吗

**Comment by shibing624** [comment]
够

**Comment by cxjtju** [comment]
> 奖励模型数据需要怎样构造呢

请问增量训练增加了垂直领域的数据，奖励模型的数据是否只需要领域相关即可

**Comment by cxjtju** [comment]
response_chosen 和 response_reject是sft之后的模型生成两个response，然后人工选择吗？

**Comment by shibing624** [comment]
是
