### ISSUE TITLE
有没有人能分享下自己微调后的模型id，我懒得弄，只想吃现成的

### ISSUE THREAD

**Issue by aqpmzngldh** [shibing624/MedicalGPT#372]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.

**Comment by shibing624** [comment]
[shibing624/vicuna-baichuan-13b-chat](https://huggingface.co/shibing624/vicuna-baichuan-13b-chat)
