### ISSUE TITLE
ValueError: Please specify target_modules in peft_config

### ISSUE THREAD

**Issue by lyj-newbie** [shibing624/MedicalGPT#379]
<img width="527" alt="微信图片_20240531104049" src="https://github.com/shibing624/MedicalGPT/assets/56766521/27720c37-d568-47a4-9b68-fb9ea52614f8">
在训练PPO的时候出现的这个问题如何解决，切换了peft不同的版本也没用。

**Comment by shibing624** [comment]
指定target modules就可以。 参考 https://github.com/shibing624/MedicalGPT/tree/main?tab=readme-ov-file#supported-models
