### ISSUE TITLE
为啥我这数据集老是有问题呢

### ISSUE THREAD

**Issue by qihangf** [shibing624/MedicalGPT#38]
我的操作CUDA_VISIBLE_DEVICES=0 python3 supervised_finetuning.py     --model_type chatglm     --model_name_or_path ./model     --train_file_dir ./data  --validation_file_dir ./data     --per_device_train_batch_size 2     --per_device_eval_batch_size 1     --do_train     --do_eval     --use_peft True     --fp16     --max_train_samples 1000     --max_eval_samples 10   --num_train_epochs 1     --learning_rate 2e-5     --warmup_ratio 0.05     --weight_decay 0.05     --logging_strategy steps     --logging_steps 10     --eval_steps 50     --evaluation_strategy steps     --save_steps500     --save_strategy steps     --save_total_limit 3     --gradient_accumulation_steps 1     --preprocessing_num_workers 1     --max_source_length 128     --max_target_length 128     --output_dir outputs-sft-chatglm2-6b-v1     --overwrite_output_dir     --ddp_timeout 30000     --logging_first_step True     --target_modulesquery_key_value     --lora_rank 8     --lora_alpha 16     --lora_dropout 0.05     --torch_dtype float16     --device_map auto     --report_to tensorboard     --ddp_find_unused_parameters False     --gradient_checkpointing True

error：Failed to read file '/home/wyxx/warBackup/ner/ChatGLM2-6B/data/data.json' with error <class 'pyarrow.lib.ArrowInvalid'>: JSON parse error: Missing a comma or '}'after an object member. in row 202
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/packaged_modules/json/json.py:134  │
│ in _generate_tables                                                                              │
│                                                                                                  │
│   131 │   │   │   │   │   │   except pa.ArrowInvalid as e:                                       │
│   132 │   │   │   │   │   │   │   try:                                                           │
│   133 │   │   │   │   │   │   │   │   with open(file, encoding="utf-8") as f:                    │
│ ❱ 134 │   │   │   │   │   │   │   │   │   dataset = json.load(f)                                 │
│   135 │   │   │   │   │   │   │   except json.JSONDecodeError:                                   │
│   136 │   │   │   │   │   │   │   │   logger.error(f"Failed to read file '{file}' with error {   │
│   137 │   │   │   │   │   │   │   │   raise e                                                    │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/json/__init__.py:293 in load                              │
│                                                                                                  │
│   290 │   To use a custom ``JSONDecoder`` subclass, specify it with the ``cls``                  │
│   291 │   kwarg; otherwise ``JSONDecoder`` is used.                                              │
│   292 │   """                                                                                    │
│ ❱ 293 │   return loads(fp.read(),                                                                │
│   294 │   │   cls=cls, object_hook=object_hook,                                                  │
│   295 │   │   parse_float=parse_float, parse_int=parse_int,                                      │
│   296 │   │   parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)          │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/json/__init__.py:346 in loads                             │
│                                                                                                  │
│   343 │   if (cls is None and object_hook is None and                                            │
│   344 │   │   │   parse_int is None and parse_float is None and                                  │
│   345 │   │   │   parse_constant is None and object_pairs_hook is None and not kw):              │
│ ❱ 346 │   │   return _default_decoder.decode(s)                                                  │
│   347 │   if cls is None:                                                                        │
│   348 │   │   cls = JSONDecoder                                                                  │
│   349 │   if object_hook is not None:                                                            │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/json/decoder.py:340 in decode                             │
│                                                                                                  │
│   337 │   │   obj, end = self.raw_decode(s, idx=_w(s, 0).end())                                  │
│   338 │   │   end = _w(s, end).end()                                                             │
│   339 │   │   if end != len(s):                                                                  │
│ ❱ 340 │   │   │   raise JSONDecodeError("Extra data", s, end)                                    │
│   341 │   │   return obj                                                                         │
│   342 │                                                                                          │
│   343 │   def raw_decode(self, s, idx=0):                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
JSONDecodeError: Extra data: line 2 column 1 (char 408)

During handling of the above exception, another exception occurred:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/builder.py:1858 in                 │
│ _prepare_split_single                                                                            │
│                                                                                                  │
│   1855 │   │   │   )                                                                             │
│   1856 │   │   │   try:                                                                          │
│   1857 │   │   │   │   _time = time.time()                                                       │
│ ❱ 1858 │   │   │   │   for _, table in generator:                                                │
│   1859 │   │   │   │   │   if max_shard_size is not None and writer._num_bytes > max_shard_size  │
│   1860 │   │   │   │   │   │   num_examples, num_bytes = writer.finalize()                       │
│   1861 │   │   │   │   │   │   writer.close()                                                    │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/packaged_modules/json/json.py:137  │
│ in _generate_tables                                                                              │
│                                                                                                  │
│   134 │   │   │   │   │   │   │   │   │   dataset = json.load(f)                                 │
│   135 │   │   │   │   │   │   │   except json.JSONDecodeError:                                   │
│   136 │   │   │   │   │   │   │   │   logger.error(f"Failed to read file '{file}' with error {   │
│ ❱ 137 │   │   │   │   │   │   │   │   raise e                                                    │
│   138 │   │   │   │   │   │   │   # If possible, parse the file as a list of json objects and    │
│   139 │   │   │   │   │   │   │   if isinstance(dataset, list):  # list is the only sequence t   │
│   140 │   │   │   │   │   │   │   │   try:                                                       │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/packaged_modules/json/json.py:113  │
│ in _generate_tables                                                                              │
│                                                                                                  │
│   110 │   │   │   │   │   │   try:                                                               │
│   111 │   │   │   │   │   │   │   while True:                                                    │
│   112 │   │   │   │   │   │   │   │   try:                                                       │
│ ❱ 113 │   │   │   │   │   │   │   │   │   pa_table = paj.read_json(                              │
│   114 │   │   │   │   │   │   │   │   │   │   io.BytesIO(batch), read_options=paj.ReadOptions(   │
│   115 │   │   │   │   │   │   │   │   │   )                                                      │
│   116 │   │   │   │   │   │   │   │   │   break                                                  │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/pyarrow/_json.pyx:258 in pyarrow._json.read_json            │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/home/wyxx/warBackup/ner/ChatGLM2-6B/pyarrow/_json.pyx'    │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/pyarrow/error.pxi:144 in                                    │
│ pyarrow.lib.pyarrow_internal_check_status                                                        │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/home/wyxx/warBackup/ner/ChatGLM2-6B/pyarrow/error.pxi'    │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/pyarrow/error.pxi:100 in pyarrow.lib.check_status           │
│                                                                                                  │
│ [Errno 2] No such file or directory: '/home/wyxx/warBackup/ner/ChatGLM2-6B/pyarrow/error.pxi'    │
╰────────────────���─────────────────────────────────────────────────────────────────────────────────╯
ArrowInvalid: JSON parse error: Missing a comma or '}' after an object member. in row 202

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/supervised_finetuning.py:550 in <module>                    │
│                                                                                                  │
│   547                                                                                            │
│   548                                                                                            │
│   549 if __name__ == "__main__":                                                                 │
│ ❱ 550 │   main()                                                                                 │
│   551                                                                                            │
│                                                                                                  │
│ /home/wyxx/warBackup/ner/ChatGLM2-6B/supervised_finetuning.py:384 in main                        │
│                                                                                                  │
│   381 │   │   │   │   f'{data_args.validation_file_dir}/**/*.jsonl', recursive=True)             │
│   382 │   │   │   logger.info(f"eval files: {', '.join(eval_data_files)}")                       │
│   383 │   │   │   data_files["validation"] = eval_data_files                                     │
│ ❱ 384 │   │   raw_datasets = load_dataset(                                                       │
│   385 │   │   │   'json',                                                                        │
│   386 │   │   │   data_files=data_files,                                                         │
│   387 │   │   │   cache_dir=model_args.cache_dir,                                                │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/load.py:1797 in load_dataset       │
│                                                                                                  │
│   1794 │   try_from_hf_gcs = path not in _PACKAGED_DATASETS_MODULES                              │
│   1795 │                                                                                         │
│   1796 │   # Download and prepare data                                                           │
│ ❱ 1797 │   builder_instance.download_and_prepare(                                                │
│   1798 │   │   download_config=download_config,                                                  │
│   1799 │   │   download_mode=download_mode,                                                      │
│   1800 │   │   verification_mode=verification_mode,                                              │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/builder.py:890 in                  │
│ download_and_prepare                                                                             │
│                                                                                                  │
│    887 │   │   │   │   │   │   │   prepare_split_kwargs["max_shard_size"] = max_shard_size       │
│    888 │   │   │   │   │   │   if num_proc is not None:                                          │
│    889 │   │   │   │   │   │   │   prepare_split_kwargs["num_proc"] = num_proc                   │
│ ❱  890 │   │   │   │   │   │   self._download_and_prepare(                                       │
│    891 │   │   │   │   │   │   │   dl_manager=dl_manager,                                        │
│    892 │   │   │   │   │   │   │   verification_mode=verification_mode,                          │
│    893 │   │   │   │   │   │   │   **prepare_split_kwargs,                                       │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/builder.py:985 in                  │
│ _download_and_prepare                                                                            │
│                                                                                                  │
│    982 │   │   │                                                                                 │
│    983 │   │   │   try:                                                                          │
│    984 │   │   │   │   # Prepare split will record examples associated to the split              │
│ ❱  985 │   │   │   │   self._prepare_split(split_generator, **prepare_split_kwargs)              │
│    986 │   │   │   except OSError as e:                                                          │
│    987 │   │   │   │   raise OSError(                                                            │
│    988 │   │   │   │   │   "Cannot find data file. "                                             │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/builder.py:1746 in _prepare_split  │
│                                                                                                  │
│   1743 │   │   │   gen_kwargs = split_generator.gen_kwargs                                       │
│   1744 │   │   │   job_id = 0                                                                    │
│   1745 │   │   │   with pbar:                                                                    │
│ ❱ 1746 │   │   │   │   for job_id, done, content in self._prepare_split_single(                  │
│   1747 │   │   │   │   │   gen_kwargs=gen_kwargs, job_id=job_id, **_prepare_split_args           │
│   1748 │   │   │   │   ):                                                                        │
│   1749 │   │   │   │   │   if done:                                                              │
│                                                                                                  │
│ /data/software/anaconda3/lib/python3.9/site-packages/datasets/builder.py:1891 in                 │
│ _prepare_split_single                                                                            │
│                                                                                                  │
│   1888 │   │   │   # Ignore the writer's error for no examples written to the file if this erro  │
│   1889 │   │   │   if isinstance(e, SchemaInferenceError) and e.__context__ is not None:         │
│   1890 │   │   │   │   e = e.__context__                                                         │
│ ❱ 1891 │   │   │   raise DatasetGenerationError("An error occurred while generating the dataset  │
│   1892 │   │                                                                                     │
│   1893 │   │   yield job_id, True, (total_num_examples, total_num_bytes, writer._features, num_  ���
│   1894                                                                                           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
DatasetGenerationError: An error occurred while generating the dataset

我的第202行数据{"instruction": "国内货物运输保险的赔偿处理遵循什么原则", "input": "", "output": "对于国内货物运输保险的赔偿是，在发生保险责任范围内的灾害事故时，普通财产保险仅负责被保险财产的直接损失以及为避免损失扩大采取施救、保护等措施而产生的合理费用。对于国内货物运输保险的定义是以在国内运输过程中的货物为保险标的，在标的物遭遇自然灾害或意外事故所造成的损失时给予经济补偿。按照分输方式可分为：直运货物运输保险、联运货物运输保险、集装箱运输保险。在发生保险事故的时候，被保险人要向保险人申请索赔，必须提供下列有关单证：保险凭证、运单（货票）、提货单、发货票，承运部门签发的货运记录、普通记录、交接验收记录、鉴定书，收货单位的入库记录、检验报告、损失清单及救护货物所支付的直接费用的单据。"}

我感觉这没问题啊

**Comment by shibing624** [comment]
数据问题，就自己仔细检查数据，不行删除这条。
