### ISSUE TITLE
大佬，DPO训练报错

### ISSUE THREAD

**Issue by cheun726** [shibing624/MedicalGPT#382]
### Describe the Question
Please provide a clear and concise description of what the question is.

![image](https://github.com/shibing624/MedicalGPT/assets/72805517/e35a2b5d-7350-4c9a-a387-63acbf3df22a)

**Comment by shibing624** [comment]
检查数据，看着是有空值。

**Comment by cheun726** [comment]
徐老师，我按照你的notebook跑，报了这个错，麻烦帮我看下如何解决
![image](https://github.com/shibing624/MedicalGPT/assets/72805517/7d00d07c-aab4-4a91-9f3e-8544bf59b376)

**Comment by cheun726** [comment]
DPO阶段
![image](https://github.com/shibing624/MedicalGPT/assets/72805517/5093f6c2-1913-4045-a7c1-1fb4ebedd65e)

**Comment by shibing624** [comment]
--max_eval_samples 1000 ,改为这个。
