### ISSUE TITLE
从头开始训练

### ISSUE THREAD

**Issue by dage0127** [shibing624/MedicalGPT#390]
请教一个问题，
  如果想从头训练，比如用qwen的模型结构，但不使用已经发布的模型Qwen/Qwen-chat的模型参数。

问题1：只需要修改模型初始化的地方，类似下面这样：
cfg = QwenConfig()
model = AutoModelForCausalLM.from_config(cfg)

问题2：如果从头训练，是不是只能使用全参数训练了。因为如果使用lora训练，训练结束之后没有基础模型可以merge。

谢谢！

**Comment by shibing624** [comment]
1.嗯；2.没有base模型。

**Comment by dage0127** [comment]
多谢多谢
