### ISSUE TITLE
训练数据集切分一次，多次重复使用的问题

### ISSUE THREAD

**Issue by dage0127** [shibing624/MedicalGPT#393]
因为数据量比较大，每次切分好几个小时。希望切分一次，缓存到本地，后面训练多次重复使用。
在训练参数中设置了：--cache_dir ./cache，在cache目录下也看到生成了相关数据。
但重新启动 pretraining.py，进行训练时，代码又开始重新切分，非常耗时。
请教一下，除了设置--cache_dir ./cache参数之外，还需要设置什么参数，才能使用切分好的数据集，不用重新切分。
	./cache下的数据：
	-rw-rw-r-- 1 llm llm       5489 7月  18 18:42 dataset_info.json
	-rw-rw-r-- 1 llm llm  508713832 7月  18 18:41 json-train-00000-of-00009.arrow
	-rw-rw-r-- 1 llm llm  506487152 7月  18 18:41 json-train-00001-of-00009.arrow
	-rw-rw-r-- 1 llm llm  504142336 7月  18 18:42 json-train-00002-of-00009.arrow
	-rw-rw-r-- 1 llm llm  509391416 7月  18 18:42 json-train-00003-of-00009.arrow
	-rw-rw-r-- 1 llm llm  506347880 7月  18 18:42 json-train-00004-of-00009.arrow
	...

谢谢。

**Comment by shibing624** [comment]
改下代码，不切分呗。再说为啥重跑？
这个不是一次性的操作吗？

**Comment by dage0127** [comment]
OK，多谢了。
重跑是想验证不同的参数规模的效果。

**Comment by dage0127** [comment]
忘了关闭了。
