### ISSUE TITLE
internlm2-1.8b微调报错

### ISSUE THREAD

**Issue by deep-practice** [shibing624/MedicalGPT#395]
使用internlm2-1.8b进行微调的时候，会报AttributeError: 'InternLM2ForCausalLM' object has no attribute 'lm_head'。但是使用internlm2-1.8b增量预训练又没有报错。

**Comment by deep-practice** [comment]
在代码里面加上：
if getattr(config, "model_type", None) == "internlm2":
            setattr(model, "lm_head", model.output)
            setattr(model, "_keys_to_ignore_on_save", ["lm_head.weight"])

**Comment by shibing624** [comment]
thanks，fixed。
