### ISSUE TITLE
run  chatglm

### ISSUE THREAD

**Issue by yangzhipeng1108** [shibing624/MedicalGPT#40]
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "/root/.cache/huggingface/modules/transformers_modules/chatglm-6b/modeling_chatglm.py", line 201, in <forward op>
    cos, sin = F.embedding(position_id, cos.squeeze(1)).unsqueeze(2), \
        F.embedding(position_id, sin.squeeze(1)).unsqueeze(2)
    q, k = (q * cos) + (rotate_half(q) * sin), (k * cos) + (rotate_half(k) * sin)
                                                ~~~~~~~ <--- HERE
    return q, k
RuntimeError: The size of tensor a (1024) must match the size of tensor b (36) at non-singleton dimension 0

**Comment by shibing624** [comment]
环境问题，请安装新版本的库。 pip install -U transformers

**Comment by yangzhipeng1108** [comment]
升级环境未解决
