### ISSUE TITLE
请教一下base_model的问题

### ISSUE THREAD

**Issue by panliang5020** [shibing624/MedicalGPT#41]
### Describe the Question
是否可以直接使用chinese-llama-plus-13b-hf作为base_model,然后使用ziya-llama-13b-medical-lora为lora_model进行推理

### Describe your attempts
- [x] I walked through the tutorials
- [ ] I checked the documentation
- [ ] I checked to make sure that this is not a duplicate question

**Comment by shibing624** [comment]
可以
