### ISSUE TITLE
chatglm2-6b

### ISSUE THREAD

**Issue by Vincent131499** [shibing624/MedicalGPT#42]
chatglm2-6b目前支持吗

**Comment by shibing624** [comment]
support， https://github.com/THUDM/ChatGLM2-6B/issues/51?notification_referrer_id=NT_kwDOAJxllrM2ODgwMTcwMjQyOjEwMjQ5NjIy#issuecomment-1610616338

**Comment by Macvh** [comment]
请问chatglm2-6b的全量微调有需要更改的参数吗，因为数据需要我设max_source_length为2000，batch_size 1，在40G卡上报显存溢出了，请问有什么解决办法吗
