### ISSUE TITLE
从头开始预训练 Loss下降缓慢

### ISSUE THREAD

**Issue by dage0127** [shibing624/MedicalGPT#426]
师兄，请教个问题。
采用和Qwen2一样的模型架构，调了一下参数，模型规模在1.1B左右 。8卡训练了10天，训练5000万行数据了，但现在模型训练的Loss一直在2.8左右徘徊，根据您之前训练的经验，有什么解决方案吗？

**Comment by shibing624** [comment]
精简到1000条数据，训练10个epochs，看loss变化和模型效果。

**Comment by dage0127** [comment]
多谢多谢。是1000万 * 10 轮吧？

**Comment by shibing624** [comment]
1000条。
