### ISSUE TITLE
CEVAL评分问题

### ISSUE THREAD

**Issue by dage1210** [shibing624/MedicalGPT#427]
请教楼主一个问题，
第一步，完成了从头开始的预训练，模型大小1B左右。用CEVAL评分在25分左右。
第二步，使用了各种类型的数据比如万卷问题，belle，匠数科技提供的调优数据，CEVAL的评分只能到27分左右。增大调优数据量好像不太管用。

请问，有什么方法能让调优模型评分达到30分以上。

谢谢！

**Comment by shibing624** [comment]
从7b或者13b的模型那里做蒸馏，能快速提高刷榜成绩。

**Comment by dage1210** [comment]
谢谢！
是将ceval的问题作为输入，以7b/13b的模型回答作为输出，生成训练数据做调优训练吧。
我对每个问题生成了3-5个答案，进行微调，ceval评分反而不如使用匠数科技，Belle，万卷等数据得分高。全参数和Lora都试过，不知道是什么原因。

Ming Xu (徐明) ***@***.***> 于2024年12月12日周四 16:35写道：

**Comment by shibing624** [comment]
刷榜的奇淫技巧自己摸索吧。

举例（仅参考）：是将ceval的问题作为输入，以gpt-4o的模型回答作为输出，每个问题生成一个，训练10个epochs。

**Comment by wlll123456** [comment]
大佬现在刷到几分了？可以交流下吗
