### ISSUE TITLE
rlhf实验效果

### ISSUE THREAD

**Issue by zxgineng** [shibing624/MedicalGPT#43]
我看了下trl那个库里写的rlhf算法是错的，照理是做不出效果的。
请问你们自己的实验情况是怎么样的 难道是成功的？

**Comment by zxgineng** [comment]
你们用他们的库发布了代码， 那肯定是你们做出了什么效果吧？ 所以想确认下

**Comment by zxgineng** [comment]
> 去trl库提问吧

你们用他们的库发布了代码， 那肯定是你们做出了什么效果吧？ 所以想确认下

**Comment by shibing624** [comment]
我测试有效果。

**Comment by HuipengXu** [comment]
> 

请问是什么错误呢，现在trl修复了吗
