### ISSUE TITLE
似乎训练程度有点不够？

### ISSUE THREAD

**Issue by bash99** [shibing624/MedicalGPT#45]
容易出现无法回答的情况。

比如问：
高血压，吃了拜新同头疼怎么办？

会没有响应。
用的是 https://huggingface.co/WHJ1998/Ziya-LLaMA-13B-v1 这个合并好的基础权重（如果有问题我试试自己合并一次，如果你能给出合并后的sha256更好）

用下列参数启动的：
```
python gradio_demo.py --model_type llama     --base_model /DaTa/Ziya/Ziya-LLaMA-13B-v1     --lora_model /DaTa/Ziya/ziya-llama-13b-medical-lora
```

我尝试用ooba textgeneration web ui里面的参数仔细调整，大致将主要参数设置如下能出结果。
```
temperature: 0.8
top_p: 0.99
top_k: 80
typical_p: 0.75
repetition_penalty: 1.01
encoder_repetition_penalty: 1.4
```

但是幻觉和重复率也稍微有点高，很多时候仅仅在简述高血压的机理和危害。另外拜新同就是硝苯地平控释片语言模型有点没理解。

感觉对于病理说明的训练有点过拟合（医学基础数据），但是对于问答类模式似乎又训练不足。

**Comment by shibing624** [comment]
1. ziya 权重，我训练时用的是官方最初发布的完整版模型权重（后来IDEA改为发布diff权重了），你给的这个ziya权重我没测试过；
2. repetition_penalty: 1.01 的数值调高可以降低重复问题；
3. 微调数据是240万那个数据集，我开源数据集了，可以自行查看。
4. 后续会把医疗多轮对话训练好，放个完全权重版本的模型（可能是falcon的等，可以免费商用协议的模型）。

**Comment by bash99** [comment]
> 1. ziya 权重，我训练时用的是官方最初发布的完整版模型权重（后来IDEA改为发布diff权重了），你给的这个ziya权重我没测试过；
这个有对应的sha256可以对比一下吗？
> 2. repetition_penalty: 1.01 的数值调高可以降低重复问题；
这个调高了非常容易不响应，也就是模型不输出任何东西。

**Comment by bash99** [comment]
> Ziya-LLaMA-13B-v1
> <img alt="image" width="526" src="https://user-images.githubusercontent.com/10249622/249702808-5fb78d5c-c43e-424f-8d4b-b85521e3c2e7.png">

我对比了一下，和我下载的不一样，sigh。
能发出第一个文件的 sha256 吗？hugglingface上面的lfs文件只有sha256可以对比。

**Comment by shibing624** [comment]
![image](https://github.com/shibing624/MedicalGPT/assets/10249622/8d932528-08a9-438f-b8f4-7c9ff381f521)

**Comment by shibing624** [comment]
release full model.
