### ISSUE TITLE
Expected all tensors to be on the same device, but found at least two devices, cuda:3 and cuda:0! 错误

### ISSUE THREAD

**Issue by dingxianzhong** [shibing624/MedicalGPT#47]
运行Stage 4: Reinforcement Learning Training， 用的完全一样的输入代码， 我是4XA100 GPU.然后出现了这个图中的错误。麻烦帮忙解释一下。谢谢
<img width="1308" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/22359098/8b1d9fb0-485b-45ee-8c49-fcf44e962019">

**Comment by shibing624** [comment]
多卡执行的问题，修改脚本里的 CUDA_VISIBLE_DEVICES 到你想要用的GPU编号（比如 0,1,2,3）即可
