### ISSUE TITLE
run_rl.sh chatglm2-6b  Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'>

### ISSUE THREAD

**Issue by yangzhipeng1108** [shibing624/MedicalGPT#48]
Traceback (most recent call last):
  File "/root/nas-share/chat/MedicalGPT-main/rl_training.py", line 456, in <module>
    main()
  File "/root/nas-share/chat/MedicalGPT-main/rl_training.py", line 240, in main
    model = AutoModelForCausalLMWithValueHead.from_pretrained(
  File "/usr/local/conda/lib/python3.9/site-packages/trl/models/modeling_base.py", line 189, in from_pretrained
    pretrained_model = cls.transformers_parent_class.from_pretrained(
  File "/usr/local/conda/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 487, in from_pretrained
    raise ValueError(
ValueError: Unrecognized configuration class <class 'transformers_modules.chatglm2-6b.configuration_chatglm.ChatGLMConfig'> for this kind of AutoModel: AutoModelForCausalLM.
Model type should be one of BartConfig, BertConfig, BertGenerationConfig, BigBirdConfig, BigBirdPegasusConfig, BioGptConfig, BlenderbotConfig, BlenderbotSmallConfig, BloomConfig, CamembertConfig, CodeGenConfig, CpmAntConfig, CTRLConfig, Data2VecTextConfig, ElectraConfig, ErnieConfig, GitConfig, GPT2Config, GPT2Config, GPTBigCodeConfig, GPTNeoConfig, GPTNeoXConfig, GPTNeoXJapaneseConfig, GPTJConfig, LlamaConfig, MarianConfig, MBartConfig, MegaConfig, MegatronBertConfig, MvpConfig, OpenLlamaConfig, OpenAIGPTConfig, OPTConfig, PegasusConfig, PLBartConfig, ProphetNetConfig, QDQBertConfig, ReformerConfig, RemBertConfig, RobertaConfig, RobertaPreLayerNormConfig, RoCBertConfig, RoFormerConfig, RwkvConfig, Speech2Text2Config, TransfoXLConfig, TrOCRConfig, XGLMConfig, XLMConfig, XLMProphetNetConfig, XLMRobertaConfig, XLMRobertaXLConfig, XLNetConfig, XmodConfig.

**Comment by shibing624** [comment]
run_rl.sh 暂还不支持chatglm2-6b，没测试过。

**Comment by yangzhipeng1108** [comment]
好的，感谢大神

**Comment by boxter007** [comment]
> run_rl.sh 暂还不支持chatglm2-6b，没测试过。

是不是RM也不支持chatglm2-6b、chatglm-6b？

**Comment by shibing624** [comment]
嗯，在开发适配中。
