### ISSUE TITLE
直接运行时会出现tokenizer长度错误

### ISSUE THREAD

**Issue by chelovek21** [shibing624/MedicalGPT#5]
默认tokenizer_path是没有提供了，将其指定为Ziya-LLaMA-13B-v1模型所在路径后，会提示长度不一致错误，该怎么解决？

Vocab of the base model: 39424
Vocab of the tokenizer: 39410
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ MedicalGPT/scripts/gradio_demo.py:190 in <module>                  │
│                                                                                                  │
│   187                                                                                            │
│   188                                                                                            │
│   189 if __name__ == '__main__':                                                                 │
│ ❱ 190 │   main()                                                                                 │
│   191                                                                                            │
│                                                                                                  │
│ MedicalGPT/scripts/gradio_demo.py:77 in main                       │
│                                                                                                  │
│    74 │   print(f"Vocab of the base model: {model_vocab_size}")                                  │
│    75 │   print(f"Vocab of the tokenizer: {tokenzier_vocab_size}")                               │
│    76 │   if model_vocab_size != tokenzier_vocab_size:                                           │
│ ❱  77 │   │   assert tokenzier_vocab_size > model_vocab_size                                     │
│    78 │   │   print("Resize model embeddings to fit tokenizer")                                  │
│    79 │   │   base_model.resize_token_embeddings(tokenzier_vocab_size)                           │
│    80 │   if args.lora_model is not None:                                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
AssertionError

**Comment by chelovek21** [comment]
@shibing624 按照更新的代码重新跑，双卡4090跑，显存每卡只占了14G左右，推理时依然会报错，
File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
/opt/conda/conda-bld/pytorch_1670525552843/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [0,0,0], thread: [64,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.
您知道是什么问题吗？谢谢

另外，需要在import时增加  from transformers import GenerationConfig，否则会报错

**Comment by shibing624** [comment]
已经补上了GenerationConfig。fixed gradio demo.
