### ISSUE TITLE
单机多卡(A100 80GB)，torchrun 数据并行报错

### ISSUE THREAD

**Issue by AllenYkl** [shibing624/MedicalGPT#53]
torchrun --nnodes 1 --nproc_per_node 3 supervised_finetuning_test.py \
    --model_type chatglm \
    --model_name_or_path /data/hongshen/models/chatglm-6b \
    --train_file_dir /data/kanlong/datasets/finetune/sft_classify_test/train \
    --validation_file_dir /data/kanlong/datasets/finetune/sft_classify_test/val \
    --per_device_train_batch_size 8 \
    --per_device_eval_batch_size 8 \
    --do_train \
    --do_eval \
    --use_peft True \
    --fp16 \
    --max_train_samples 50 \
    --max_eval_samples 50 \
    --num_train_epochs 3 \
    --learning_rate 1e-3 \
    --warmup_ratio 0.05 \
    --weight_decay 0.05 \
    --logging_strategy steps \
    --logging_steps 10 \
    --eval_steps 50 \
    --evaluation_strategy steps \
    --save_steps 100 \
    --save_strategy steps \
    --save_total_limit 3 \
    --gradient_accumulation_steps 1 \
    --preprocessing_num_workers 1 \
    --max_source_length 4096 \
    --max_target_length 128 \
    --output_dir /data/kanlong/outputs/instruction_classify_2050-chatglm-6b-pt \
    --overwrite_output_dir \
    --ddp_timeout 30000 \
    --logging_first_step True \
    --target_modules all \
    --lora_rank 8 \
    --lora_alpha 16 \
    --lora_dropout 0.05 \
    --torch_dtype float16 \
    --device_map auto \
    --report_to tensorboard \
    --ddp_find_unused_parameters False \
    --gradient_checkpointing True

### **Error:**
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: -11) local_rank: 0 (pid: 1609205) of binary: /data/anaconda3/envs/medicalgpt/bin/python
Traceback (most recent call last):
  File "/data/anaconda3/envs/medicalgpt/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/data/anaconda3/envs/medicalgpt/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/data/anaconda3/envs/medicalgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/data/anaconda3/envs/medicalgpt/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/data/anaconda3/envs/medicalgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/data/anaconda3/envs/medicalgpt/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError:
=========================================================
supervised_finetuning_test.py FAILED
---------------------------------------------------------
Failures:
[1]:
  time      : 2023-06-30_16:44:08
  host      : ubuntu
  rank      : 1 (local_rank: 1)
  exitcode  : -11 (pid: 1609206)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1609206
[2]:
  time      : 2023-06-30_16:44:08
  host      : ubuntu
  rank      : 2 (local_rank: 2)
  exitcode  : -11 (pid: 1609207)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1609207
---------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-06-30_16:44:08
  host      : ubuntu
  rank      : 0 (local_rank: 0)
  exitcode  : -11 (pid: 1609205)
  error_file: <N/A>
  traceback : Signal 11 (SIGSEGV) received by PID 1609205
=========================================================

所有包均为最新，多卡模型并行可以运行，但是多卡数据并行报错

求教

**Comment by valkryhx** [comment]
麻烦问下，多卡模型并行是使用了什么输入参数？

**Comment by AllenYkl** [comment]
> 麻烦问下，多卡模型并行是使用了什么输入参数？

<img width="746" alt="1688117504622" src="https://github.com/shibing624/MedicalGPT/assets/105541324/8526e2aa-d91a-4e73-bb4c-07eee85d0bba">

**Comment by shibing624** [comment]
> 麻烦问下，多卡模型并行是使用了什么输入参数？

参考这个： https://github.com/shibing624/MedicalGPT/blob/main/run_sft.sh

**Comment by shibing624** [comment]
只能多卡模型并行，不支持其他。如果想单卡把显存打满，就把batch size 调大就行。


nproc_per_node = 3 那么就要用3个卡，
CUDA_VISIBLE_DEVICES=0,1,2 torchrun --nproc_per_node 3 supervised_finetuning.py

**Comment by AllenYkl** [comment]
> 只能多卡模型并行，不支持其他。如果想单卡把显存打满，就把batch size 调大就行。
> 
> nproc_per_node = 3 那么就要用3个卡， CUDA_VISIBLE_DEVICES=0,1,2 torchrun --nproc_per_node 3 supervised_finetuning.py

CUDA_VISIBLE_DEVICES=5,6,7，这个我是用os.env的方式声明在了supervised_finetuning.py里面，因为发现如果声明在sh文件里，他调用的是0，1，2。

我看您这里说了可以支持多卡数据并行，
![image](https://github.com/shibing624/MedicalGPT/assets/105541324/274bc574-f44a-4120-ac94-29f3ebf3a459)

**Comment by valkryhx** [comment]
我试了下 用您提供的方式  load model后两张卡显存都是12.4G 
考虑到chatglm2-6B 参数是6.2B  那么说明是把模型完整的分发到两张显卡了？
这样好像没有对模型参数进行切分和分发？属于模型并行吗 @shibing624  。
我这边自己改了一些代码，让一个卡上存7G参数 另一个卡存大概6G参数 ，感觉这样才是模型并行？

**Comment by valkryhx** [comment]
> 可以用deepspeed处理；但模型放2个卡上，训练会慢很多，不建议，等同于zero3。

赞，确实是这么操作的。

**Comment by vs0533** [comment]
deepspeed 开启zero3 模型放在两张卡上 然后进行pt 但是发现保存的模型不完整 合并lora时出错 请问如何解决？


> 可以用deepspeed处理；但模型放2个卡上，训练会慢很多，不建议，等同于zero3。
