### ISSUE TITLE
lora训练完的chatglm2-6b，adapter model怎么和base model合并成新的model？

### ISSUE THREAD

**Issue by AaronZLT** [shibing624/MedicalGPT#55]
很感谢大佬提供的脚本~
目前在尝试训练chatglm2-6b，然后想使用这个[web_demo2.py](https://github.com/THUDM/ChatGLM2-6B/blob/53f010681717fc70144fbd15e973ef60bc863227/web_demo2.py)来进行推理，然而这里只能加载base model，所以需要把lora model合并一下？

**Comment by shibing624** [comment]
嗯

**Comment by valkryhx** [comment]
> 很感谢大佬提供的脚本~ 目前在尝试训练chatglm2-6b，然后想使用这个[web_demo2.py](https://github.com/THUDM/ChatGLM2-6B/blob/53f010681717fc70144fbd15e973ef60bc863227/web_demo2.py)来进行推理，然而这里只能加载base model，所以需要把lora model合并一下？

在https://github.com/THUDM/ChatGLM2-6B/blob/53f010681717fc70144fbd15e973ef60bc863227/web_demo2.py#L16  
代码Line 16之后 使用peft_model = PeftModel.from_pretrained(base_model, peft_model_checkpoint) 的方式合并，挂载组合lora adapter 。

**Comment by AaronZLT** [comment]
> > 很感谢大佬提供的脚本~ 目前在尝试训练chatglm2-6b，然后想使用这个[web_demo2.py](https://github.com/THUDM/ChatGLM2-6B/blob/53f010681717fc70144fbd15e973ef60bc863227/web_demo2.py)来进行推理，然而这里只能加载base model，所以需要把lora model合并一下？
> 
> 在https://github.com/THUDM/ChatGLM2-6B/blob/53f010681717fc70144fbd15e973ef60bc863227/web_demo2.py#L16 代码Line 16之后 使用peft_model = PeftModel.from_pretrained(base_model, peft_model_checkpoint) 的方式合并，挂载组合lora adapter 。

谢谢！
