### ISSUE TITLE
Prompt设置

### ISSUE THREAD

**Issue by Ricardokevins** [shibing624/MedicalGPT#56]
### Describe the Question
Please provide a clear and concise description of what the question is.

似乎在微调阶段没有针对不同模型使用不同的prompt？
用的都是alpaca的模板。这样微调chatGLM 6B这种模板不同，但原能力不错的模型的时候，是否会亏损啊

**Comment by shibing624** [comment]
1. 生成模型的能力跟用啥模版没关系，跟微调样本的训练集质量有关；
2. 可以自行添加vicuna等模版的适配代码，chatglm也可以不用模版，直接拼接q+a，效果也不差。
