### ISSUE TITLE
run_rm使用llama模型看代码做了set pad_token_id = 0还是报错

### ISSUE THREAD

**Issue by charryshi** [shibing624/MedicalGPT#58]
/opt/conda/conda-bld/pytorch_1682343967769/work/aten/src/ATen/native/cuda/IndexKernel.cu:92: operator(): block: [61,0,0], thread: [31,0,0] Assertion `index >= -sizes[i] && index < sizes[i] && "index out of bounds"` failed.

麻烦请问一下作者可能是什么原因呀，谢谢！

**Comment by shibing624** [comment]
base model 是啥，一般数组越界是词表问题，如果偶发可能是某条数据空值。

**Comment by charryshi** [comment]
base model是Ziya-LLaMA-13B-v1
用的您huggingface上reward数据
现在卡住了

**Comment by shibing624** [comment]
卡住是啥？显存爆了？

**Comment by charryshi** [comment]
就是数组越界的问题没发现解决方案，数据也是标准数据集，模型是Ziya-LLaMA-13B-v1，但看到set pad_token_id 设置了= 0

**Comment by dingxianzhong** [comment]
楼主 解决了Ziya-LLaMA-13B-v1 的问题吗？ 这个base model 能用了吗

**Comment by charryshi** [comment]
目前单GPU能跑，但跑一会就OOM，单机多卡还是有数组越界问题。
