### ISSUE TITLE
chatglm2-6b sft报错

### ISSUE THREAD

**Issue by zhangatao** [shibing624/MedicalGPT#59]
### Describe the bug
Please provide a clear and concise description of what the bug is. If applicable, add screenshots to help explain your problem, especially for visualization related problems.
za
你好，我在用你们的框架跑lora是ok的，但是在我执行全量微调的时候，报了下面的错误:
<img width="1130" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/28706321/329a526d-cb30-48a7-b5aa-46680ce9616e">

ValueError: Attempting to unscale FP16 gradients.

请问 这个是什么导致的

**Comment by shibing624** [comment]
报错是fp16, 可以看看bf16或者fp32

**Comment by shibing624** [comment]
same  https://github.com/shibing624/MedicalGPT/issues/125
