### ISSUE TITLE
chatglm, chatglm2的pretrain

### ISSUE THREAD

**Issue by calvinzhan** [shibing624/MedicalGPT#63]
### Describe the Question
请问对chatglm, chatglm2能用领域语料进行pretrain吗？

看代码，labels和input_ids是一致的，应该是用自回归的方法。不知有试过这对chatglm系列有效吗？我自己测过一下，貌似chatglm只能作不理解的回答了。

result["labels"] = result["input_ids"].copy()

**Comment by shibing624** [comment]
还没测，有空拿医疗数据测下
