### ISSUE TITLE
run_pt.sh: 42: run_pt.sh: --deepspeed: not found

### ISSUE THREAD

**Issue by yangzhipeng1108** [shibing624/MedicalGPT#66]
如果运行环境支持deepspeed，加上--deepspeed deepspeed_config.json

添加运行环境并为解决问题

**Comment by shibing624** [comment]
没懂

**Comment by yangzhipeng1108** [comment]
![image](https://github.com/shibing624/MedicalGPT/assets/33448441/f22b7e4e-4f35-4ae0-a3d5-f8e8f1445b0d)
![image](https://github.com/shibing624/MedicalGPT/assets/33448441/095fdc55-306e-4889-9ab1-5397a178deb4)
![image](https://github.com/shibing624/MedicalGPT/assets/33448441/ff174e3c-60ce-4dde-9362-41b32747eb51)

**Comment by shibing624** [comment]
少个 `\`
