### ISSUE TITLE
请教一下chatglm的PROMPT_TEMPLATE是否需要按照官方预测脚本的形式呢

### ISSUE THREAD

**Issue by MRKINKI** [shibing624/MedicalGPT#67]
chatglm官方的的promt格式是按照如下的，采用chatglm做sft是否要按照这种格式做转换呢？

  def build_prompt(self, query, history=None):
        if history is None:
            history = []
        prompt = ""
        for i, (old_query, response) in enumerate(history):
            prompt += "[Round {}]\n\n问：{}\n\n答：{}\n\n".format(i + 1, old_query, response)
        prompt += "[Round {}]\n\n问：{}\n\n答：".format(len(history) + 1, query)
        return prompt

**Comment by shibing624** [comment]
多轮对话是需要这样的，当前采用alpaca的template，sft只用了单轮对话
