### ISSUE TITLE
sft微调glm2，试图合并时报错

### ISSUE THREAD

**Issue by shawnlihst** [shibing624/MedicalGPT#68]
**### Describe the Question
sft微调glm2以后，试图合并时报错，请问要怎么处理？模型路径和lora路径都是没问题的，是需要把模型下面的文件拷贝到lora路径下吗？
使用的合并命令：**
python merge_peft_adapter.py \
  --model_type chatglm \
  --base_model_name_or_path models/chatglm2-6b \
  --peft_model_path outputs-sft-v1/ \
  --output_dir output/chatglm2-6b-sft

**报错信息:**
Namespace(model_type='chatglm', base_model_name_or_path='models/chatglm2-6b', peft_model_path='outputs-sft-v1/', output_dir='output/chatglm2-6b-sft')
Base model: models/chatglm2-6b
LoRA model: outputs-sft-v1/
Loading LoRA for causal language model
The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function.
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:19<00:00,  2.83s/it]
Could not locate the tokenization_chatglm.py inside outputs-sft-v1/.
Traceback (most recent call last):
  File "/mnt/d/tools/MedicalGPT/merge_peft_adapter.py", line 100, in <module>
    main()
  File "/mnt/d/tools/MedicalGPT/merge_peft_adapter.py", line 77, in main
    tokenizer = tokenizer_class.from_pretrained(peft_model_path, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained
    tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module
    final_module = get_cached_module_file(
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file
    resolved_module_file = cached_file(
                           ^^^^^^^^^^^^
  File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/utils/hub.py", line 388, in cached_file
    raise EnvironmentError(
OSError: outputs-sft-v1/ does not appear to have a file named tokenization_chatglm.py. Checkout 'https://huggingface.co/outputs-sft-v1//None' for available files.

**Comment by shibing624** [comment]
py 文件全部拷贝一遍

**Comment by weisliey** [comment]
> **### Describe the Question sft微调glm2以后，试图合并时报错，请问要怎么处理？模型路径和lora路径都是没问题的，是需要把模型下面的文件拷贝到lora路径下吗？ 使用的合并命令：** python merge_peft_adapter.py --model_type chatglm --base_model_name_or_path models/chatglm2-6b --peft_model_path outputs-sft-v1/ --output_dir output/chatglm2-6b-sft
> 
> **报错信息:** Namespace(model_type='chatglm', base_model_name_or_path='models/chatglm2-6b', peft_model_path='outputs-sft-v1/', output_dir='output/chatglm2-6b-sft') Base model: models/chatglm2-6b LoRA model: outputs-sft-v1/ Loading LoRA for causal language model The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function. Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:19<00:00, 2.83s/it] Could not locate the tokenization_chatglm.py inside outputs-sft-v1/. Traceback (most recent call last): File "/mnt/d/tools/MedicalGPT/merge_peft_adapter.py", line 100, in main() File "/mnt/d/tools/MedicalGPT/merge_peft_adapter.py", line 77, in main tokenizer = tokenizer_class.from_pretrained(peft_model_path, trust_remote_code=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module final_module = get_cached_module_file( ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file resolved_module_file = cached_file( ^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/utils/hub.py", line 388, in cached_file raise EnvironmentError( OSError: outputs-sft-v1/ does not appear to have a file named tokenization_chatglm.py. Checkout 'https://huggingface.co/outputs-sft-v1//None' for available files.

请问一下,peft_model_path='outputs-sft-v1/'这个里面的output-sft-v1这个模式是自己训练的吗？

**Comment by shibing624** [comment]
> > **### Describe the Question sft微调glm2以后，试图合并时报错，请问要怎么处理？模型路径和lora路径都是没问题的，是需要把模型下面的文件拷贝到lora路径下吗？ 使用的合并命令：** python merge_peft_adapter.py --model_type chatglm --base_model_name_or_path models/chatglm2-6b --peft_model_path outputs-sft-v1/ --output_dir output/chatglm2-6b-sft
> > **报错信息:** Namespace(model_type='chatglm', base_model_name_or_path='models/chatglm2-6b', peft_model_path='outputs-sft-v1/', output_dir='output/chatglm2-6b-sft') Base model: models/chatglm2-6b LoRA model: outputs-sft-v1/ Loading LoRA for causal language model The model weights are not tied. Please use the `tie_weights` method before using the `infer_auto_device` function. Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:19<00:00, 2.83s/it] Could not locate the tokenization_chatglm.py inside outputs-sft-v1/. Traceback (most recent call last): File "/mnt/d/tools/MedicalGPT/merge_peft_adapter.py", line 100, in main() File "/mnt/d/tools/MedicalGPT/merge_peft_adapter.py", line 77, in main tokenizer = tokenizer_class.from_pretrained(peft_model_path, trust_remote_code=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 676, in from_pretrained tokenizer_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 431, in get_class_from_dynamic_module final_module = get_cached_module_file( ^^^^^^^^^^^^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/dynamic_module_utils.py", line 247, in get_cached_module_file resolved_module_file = cached_file( ^^^^^^^^^^^^ File "/home/shawn/anaconda3/envs/work1/lib/python3.11/site-packages/transformers/utils/hub.py", line 388, in cached_file raise EnvironmentError( OSError: outputs-sft-v1/ does not appear to have a file named tokenization_chatglm.py. Checkout 'https://huggingface.co/outputs-sft-v1//None' for available files.
> 
> 请问一下,peft_model_path='outputs-sft-v1/'这个里面的output-sft-v1这个模式是自己训练的吗？

是
