### ISSUE TITLE
【SFT+DeepSpeed全量参数训练】推理结果异常，很奇怪！！！

### ISSUE THREAD

**Issue by yanqiangmiffy** [shibing624/MedicalGPT#69]
目前基于llama 13b+全量参数调优，测试出现下面的这样

![74ca56b127d537f59ae2ae98ceeb917b_](https://github.com/shibing624/MedicalGPT/assets/15925090/ee7f7440-b098-4564-8b3d-80fe8e360450)

**Comment by yanqiangmiffy** [comment]
![0353d46cdc5477cde39d02b147726118_](https://github.com/shibing624/MedicalGPT/assets/15925090/9b61f4a1-62eb-4d69-9966-3872f7c87ad2)

**Comment by yanqiangmiffy** [comment]
但是用lora训练效果是正常的：
![13e64fa3d374f5e517fcfa5201f54526_](https://github.com/shibing624/MedicalGPT/assets/15925090/8906c18d-3c93-4926-80e0-edead5bf4f2f)

**Comment by yanqiangmiffy** [comment]
现在不确定有两个事情：
- 是deepspeed保存的权重和save_pretrained是否一样可以直接加载用来做推理？
- 是否是全量参数调优对LLaMA大模型效果影响很大？

**Comment by shibing624** [comment]
正常训练结尾加个`model.save_pretrained(output_dir)` 保存模型，全参训练，应该保存没问题。你可以小数据集测试下，训练5个epoch看看

**Comment by elijah-hz** [comment]
什么是全参训练？就是指有监督微调吗？怎么控制是不是全量参数呢？

**Comment by yanqiangmiffy** [comment]
> 正常训练结尾加个`model.save_pretrained(output_dir)` 保存模型，全参训练，应该保存没问题。你可以小数据集测试下，训练5个epoch看看

好的也有可能，我测试的都是中间的checkpoint结果，还没试过测试过最终的效果。。

**Comment by yanqiangmiffy** [comment]
> 什么是全参训练？就是指有监督微调吗？怎么控制是不是全量参数呢？

通过use_peft参数来控制

**Comment by yanqiangmiffy** [comment]
我现在在全量训练7b模型，没有用deepspeed，到时候我都会对比下

**Comment by yanqiangmiffy** [comment]
![d72a50cda36a93bbd4e6a201770b07a](https://github.com/shibing624/MedicalGPT/assets/15925090/07f44e8a-bab2-4b42-8488-96f761e6d4a5)

基于stanford_alpaca项目微调之后效果是正常的

https://github.com/tatsu-lab/stanford_alpaca

**Comment by shibing624** [comment]
所以是数据问题还是代码原因？

**Comment by wu1143100799** [comment]
> > 所以是数据问题还是代码原因？
> 
> 目前看起来是全量参数训练的代码问题，:
> 
> * pt全量训练没有问题；
> * sft全量微调存在问题：
> 
> ```
> tokenizer.padding_side = "left"  # Set padding side equal to the collator's padding side
>     if model_args.model_type != "chatglm":
>         tokenizer.pad_token_id = 0  # Set pad token id to 
> ```
> 
> 这里tokenizer.padding_side = "left"，我看了下其他的为right,其他暂时还没发现，得调试下输入和输出是否存在问题

大佬请问找到原因了嘛？我也遇到了同样的问题，全参数微调推理结果很奇怪

**Comment by yanqiangmiffy** [comment]
> > > 所以是数据问题还是代码原因？
> > 
> > 
> > 目前看起来是全量参数训练的代码问题，:
> > 
> > * pt全量训练没有问题；
> > * sft全量微调存在问题：
> > 
> > ```
> > tokenizer.padding_side = "left"  # Set padding side equal to the collator's padding side
> >     if model_args.model_type != "chatglm":
> >         tokenizer.pad_token_id = 0  # Set pad token id to 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 这里tokenizer.padding_side = "left"，我看了下其他的为right,其他暂时还没发现，得调试下输入和输出是否存在问题
> 
> 大佬请问找到原因了嘛？我也遇到了同样的问题，全参数微调推理结果很奇怪

目前还是没解决，我换了其他代码了
