### ISSUE TITLE
如何测试reward model

### ISSUE THREAD

**Issue by lianzhaoy** [shibing624/MedicalGPT#7]
### Describe the Question
如何测试训练好的reward model

**Comment by shibing624** [comment]
用有人工评分的测试集测试，如qa pairs, compute reward score , good > bad is right, else is false.

**Comment by lianzhaoy** [comment]
感谢提供测试思路！
请问有相应的测试脚本吗？

**Comment by shibing624** [comment]
RM里面的evaluate 方法不是吗？

**Comment by lianzhaoy** [comment]
求教如何推理单个样本？
自己按照训练代码实现了单个样本推理脚本，对于相同数据，加载两次模型，推理结果不一致是什么问题？

**Comment by shibing624** [comment]
解码是有抽样的。
