### ISSUE TITLE
多机多卡

### ISSUE THREAD

**Issue by zhr0313** [shibing624/MedicalGPT#70]
感谢您项目的分享！
对于ChatGLM2的SFT，是否支持多机多卡的微调，我看到代码中有local_rank的信息，请问要如何调整代码，以支持多机微调。
谢谢！

**Comment by shibing624** [comment]
我测试可以，torchrun

**Comment by zhr0313** [comment]
有sh文件的示例嘛？源码需要修改吗？谢谢！

**Comment by shibing624** [comment]
训练细节wiki写了。

**Comment by wangzhonghai** [comment]
@shibing624 我想问一下，这种多轮对话的attention_ids是什么样的，应该是[1111,00000]只有第一句话是1是吧

**Comment by wangzhonghai** [comment]
@shibing624 torchrun --nproc_per_node 8 \
    --nnodes=2 \
    --node_rank=0 \
    --master-port= \
    --master_addr=  、除了rank不同，都是主机的端口ip，但是主机从机一直再等待，然后链接超时
