### ISSUE TITLE
gradio_demo 演示乱出问题

### ISSUE THREAD

**Issue by YuanEZhou** [shibing624/MedicalGPT#72]
感谢开源，学习一下，运行demo 出现内容乱出问题，并没有报错，请问会是什么问题呢？
![bad_result](https://github.com/shibing624/MedicalGPT/assets/17077323/a151b155-46f7-41ca-be79-b8b7f34f2410)

**Comment by shibing624** [comment]
使用错误了吧，你加载base model了没？

**Comment by YuanEZhou** [comment]
感谢回复，之前已加载 base_model 和  lora_model ,
![捕获](https://github.com/shibing624/MedicalGPT/assets/17077323/9e42b9c5-33ea-4380-a229-9fcd73b9ec21)

**Comment by shibing624** [comment]
ziya 的使用需要合并。
