### ISSUE TITLE
大佬，将你的代码单独摘出来，就报错了，求指点一下，谢谢！

### ISSUE THREAD

**Issue by xxm1668** [shibing624/MedicalGPT#75]
from transformers import Trainer
from transformers.trainer import TRAINING_ARGS_NAME
import torch
from typing import Any, List, Union, Optional, Dict
import os
from torch.utils.data import Dataset
from transformers import LlamaForSequenceClassification, LlamaTokenizer, PreTrainedTokenizerBase, \
    TrainingArguments, \
    HfArgumentParser
from peft import PeftModel
from data_processon import split_reward_data
from data_collator import preprocess_reward_function
from dataclasses import dataclass, field
from sklearn.metrics import mean_squared_error, mean_absolute_error
from transformers import DataCollatorWithPadding
from peft import LoraConfig, TaskType, get_peft_model, PeftModel

class RewardDataCollatorWithPadding(DataCollatorWithPadding):
    """We need to define a special data collator that batches the data in our chosen vs rejected format"""
    tokenizer: PreTrainedTokenizerBase
    padding: Union[bool, str] = True
    max_length: Optional[int] = None
    pad_to_multiple_of: Optional[int] = None
    return_tensors: str = "pt"

    def __call__(self, features: List[Dict[str, Any]]) -> Dict[str, Any]:
        features_chosen = []
        features_rejected = []
        for feature in features:
            features_chosen.append(
                {
                    "input_ids": feature["input_ids_chosen"],
                    "attention_mask": feature["attention_mask_chosen"],
                }
            )
            features_rejected.append(
                {
                    "input_ids": feature["input_ids_rejected"],
                    "attention_mask": feature["attention_mask_rejected"],
                }
            )
        batch_chosen = self.tokenizer.pad(
            features_chosen,
            padding=self.padding,
            max_length=self.max_length,
            pad_to_multiple_of=self.pad_to_multiple_of,
            return_tensors=self.return_tensors,
        )
        batch_rejected = self.tokenizer.pad(
            features_rejected,
            padding=self.padding,
            max_length=self.max_length,
            pad_to_multiple_of=self.pad_to_multiple_of,
            return_tensors=self.return_tensors,
        )
        batch = {
            "input_ids_chosen": batch_chosen["input_ids"],
            "attention_mask_chosen": batch_chosen["attention_mask"],
            "input_ids_rejected": batch_rejected["input_ids"],
            "attention_mask_rejected": batch_rejected["attention_mask"],
            "return_loss": True,
        }
        return batch

@dataclass
class PeftArguments(TrainingArguments):
    use_peft: bool = field(default=True, metadata={"help": "Whether to use peft"})
    target_modules: Optional[str] = field(default="all")
    lora_rank: Optional[int] = field(default=8)
    lora_dropout: Optional[float] = field(default=0.05)
    lora_alpha: Optional[float] = field(default=32.0)
    modules_to_save: Optional[str] = field(default=None)
    peft_path: Optional[str] = field(default=None)

class RewardTrainer(Trainer):
    """
    Trainer for reward models
        Define how to compute the reward loss. Use the InstructGPT pairwise logloss: https://arxiv.org/abs/2203.02155
    """

    def compute_loss(self, model, inputs, return_outputs=False):
        rewards_chosen = model(input_ids=inputs["input_ids_chosen"],
                               attention_mask=inputs["attention_mask_chosen"])[0]
        rewards_rejected = model(input_ids=inputs["input_ids_rejected"],
                                 attention_mask=inputs["attention_mask_rejected"])[0]
        loss = -torch.nn.functional.logsigmoid(rewards_chosen - rewards_rejected).mean()
        if return_outputs:
            return loss, {"rewards_chosen": rewards_chosen, "rewards_rejected": rewards_rejected}
        return loss

    def evaluate(
            self,
            eval_dataset: Optional[Dataset] = None,
            ignore_keys: Optional[List[str]] = None,
            metric_key_prefix: str = "eval",
    ) -> Dict[str, float]:
        if eval_dataset is None:
            eval_dataset = self.eval_dataset
        return super().evaluate(eval_dataset=eval_dataset, ignore_keys=ignore_keys, metric_key_prefix=metric_key_prefix)

    def prediction_step(self, model, inputs, prediction_loss_only, ignore_keys=None):
        # Prepare inputs for chosen and rejected separately
        device = model.device

        inputs_chosen = {
            "input_ids": inputs["input_ids_chosen"].to(device),
            "attention_mask": inputs["attention_mask_chosen"].to(device),
        }
        outputs_chosen = model(**inputs_chosen)
        rewards_chosen = outputs_chosen.logits.detach()

        inputs_rejected = {
            "input_ids": inputs["input_ids_rejected"].to(device),
            "attention_mask": inputs["attention_mask_rejected"].to(device),
        }
        outputs_rejected = model(**inputs_rejected)
        rewards_rejected = outputs_rejected.logits.detach()

        # Keep the compute_loss method
        loss = -torch.nn.functional.logsigmoid(rewards_chosen - rewards_rejected).mean()
        if prediction_loss_only:
            return (loss, None, None)

        return (loss, rewards_chosen, rewards_rejected)

    def save_model(self, output_dir=None, _internal_call=False):
        """Save the LoRA model."""
        os.makedirs(output_dir, exist_ok=True)
        torch.save(self.args, os.path.join(output_dir, TRAINING_ARGS_NAME))
        self.model.save_pretrained(output_dir)

class CastOutputToFloat(torch.nn.Sequential):
    """Cast the output of the model to float"""

    def forward(self, x):
        return super().forward(x).to(torch.float32)

def compute_metrics(eval_preds):
    preds, labels = eval_preds
    # Here, predictions is rewards_chosen and rewards_rejected.
    if isinstance(preds, torch.Tensor):
        preds = preds.detach().cpu().numpy()
    if isinstance(labels, torch.Tensor):
        labels = labels.detach().cpu().numpy()
    # MSE
    mse = mean_squared_error(labels, preds)
    # MAE
    mae = mean_absolute_error(labels, preds)

    return {"mse": mse, "mae": mae}

def save_model(output_dir, model, tokenizer, args):
    """Save the model and the tokenizer."""
    os.makedirs(output_dir, exist_ok=True)

    # Take care of distributed/parallel training
    model_to_save = model.module if hasattr(model, "module") else model
    model_to_save.save_pretrained(output_dir)
    tokenizer.save_pretrained(output_dir)
    torch.save(args, os.path.join(output_dir, TRAINING_ARGS_NAME))

def find_all_linear_names(peft_model, int4=False, int8=False):
    cls = torch.nn.Linear
    if int4 or int8:
        import bitsandbytes as bnb
        if int4:
            cls = bnb.nn.Linear4bit
        elif int8:
            cls = bnb.nn.Linear8bitLt
    lora_module_names = set()
    for name, module in peft_model.named_modules():
        if isinstance(module, cls):
            # last layer is not add to lora_module_names
            if 'lm_head' in name:
                continue
            if 'score' in name:
                continue
            names = name.split('.')
            lora_module_names.add(names[0] if len(names) == 1 else names[-1])
    return sorted(lora_module_names)

def main():
    print('------')
    # 加载超参数
    parser = HfArgumentParser(PeftArguments)
    training_args = parser.parse_args_into_dataclasses()[0]
    print('00000')
    # 加载模型model
    model_path = '/home/house365ai/xxm/chinese-alpaca-7b'
    ckpt_path = '/home/house365ai/xxm/LLaMA-Efficient-Tuning/output/alpaca_baichuan2'

    model = LlamaForSequenceClassification.from_pretrained(
        model_path,
        num_labels=1,
        cache_dir=False,
        trust_remote_code=True,
    )

    model = model.half()
    model.score = CastOutputToFloat(model.score)
    target_modules = find_all_linear_names(model)
    peft_config = LoraConfig(
        task_type=TaskType.SEQ_CLS,
        target_modules=target_modules,
        inference_mode=False,
        r=training_args.lora_rank,
        lora_alpha=training_args.lora_alpha,
        lora_dropout=training_args.lora_dropout,
        modules_to_save=None)
    model = get_peft_model(model, peft_config)
    # model = PeftModel.from_pretrained(model, ckpt_path, is_trainable=True)

    model.gradient_checkpointing_enable()
    model.config.use_cache = False
    model.enable_input_require_grads()
    # model = model.merge_and_unload()  # 合并lora权重
    tokenizer = LlamaTokenizer.from_pretrained(model_path, trust_remote_code=True)

    # 加载reward数据
    reward_filename = r'/home/house365ai/xxm/chatglm2_lora/data/estate_reward.json'
    ds_train, ds_val = split_reward_data(reward_filename)
    tokenized_dataset = ds_train.shuffle().map(
        preprocess_reward_function,
        batched=True,
        num_proc=2,
        remove_columns=ds_train.column_names,
        load_from_cache_file=False,
        desc="Running tokenizer on dataset",
    )
    train_dataset = tokenized_dataset.filter(
        lambda x: 0 < len(x['input_ids_rejected']) <= 2048 and 0 < len(
            x['input_ids_chosen']) <= 2048
    )

    tokenized_dataset = ds_val.shuffle().map(
        preprocess_reward_function,
        batched=True,
        num_proc=2,
        remove_columns=ds_val.column_names,
        load_from_cache_file=False,
        desc="Running tokenizer on dataset",
    )

    val_dataset = tokenized_dataset.filter(
        lambda x: 0 < len(x['input_ids_rejected']) <= 2048 and 0 < len(
            x['input_ids_chosen']) <= 2048
    )

    print(training_args)
    data_collator = RewardDataCollatorWithPadding(tokenizer=tokenizer, max_length=2048, padding="max_length")
    # 初始化reward model模型
    trainer = RewardTrainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=val_dataset,
        tokenizer=tokenizer,
        compute_metrics=compute_metrics,
        data_collator=data_collator,
    )
    print(iter(trainer.get_train_dataloader()))
    for i in iter(trainer.get_train_dataloader()):
        print(i)
    print(f"Train dataloader example: {next(iter(trainer.get_train_dataloader()))}")
    # training
    checkpoint = None
    if training_args.resume_from_checkpoint is not None:
        checkpoint = training_args.resume_from_checkpoint
    train_result = trainer.train(checkpoint)

    # saving
    metrics = train_result.metrics
    print(f"Training metrics: {metrics}")
    trainer.log_metrics("train", metrics)
    trainer.save_metrics("train", metrics)
    trainer.save_state()
    print(f"Saving model checkpoint to {training_args.output_dir}")
    save_model(training_args.output_dir, model, tokenizer, training_args)
    print('---------finsh--------')

if __name__ == '__main__':
    main()

def split_reward_data(filename):
    data = []
    with open(filename, 'r', encoding='utf-8') as f:
        lines = f.readlines()
        for line in lines:
            line = line.strip()
            line = json.loads(line)
            tmp = {}
            tmp['instruction'] = line['instruction']
            tmp['input'] = line['input']
            tmp['history'] = line['history']
            tmp['choose'] = line['output'][0]
            tmp['reject'] = line['output'][1]
            data.append(tmp)
    dftrain, dftest = train_test_split(data, test_size=0.01, random_state=42)
    ds_train = datasets.Dataset.from_list(dftrain)
    ds_val = datasets.Dataset.from_list(dftest)
    return ds_train, ds_val

报错信息：
Traceback (most recent call last):
  File "/home/house365ai/xxm/chatglm2_lora/reward_llama.py", line 291, in <module>
    main()
  File "/home/house365ai/xxm/chatglm2_lora/reward_llama.py", line 270, in main
    for i in iter(trainer.get_train_dataloader()):
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = self.dataset.__getitems__(possibly_batched_index)
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2796, in __getitems__
    batch = self.__getitem__(keys)
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2792, in __getitem__
    return self._getitem(key)
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/arrow_dataset.py", line 2776, in _getitem
    pa_subtable = query_table(self._data, key, indices=self._indices if self._indices is not None else None)
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 588, in query_table
    pa_subtable = _query_table_with_indices_mapping(table, key, indices=indices)
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 75, in _query_table_with_indices_mapping
    return _query_table(table, [indices.fast_slice(i, 1).column(0)[0].as_py() for i in key])
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/formatting/formatting.py", line 100, in _query_table
    return table.fast_gather(key % table.num_rows)
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/table.py", line 134, in fast_gather
    [
  File "/opt/anaconda3/envs/glm2/lib/python3.10/site-packages/datasets/table.py", line 135, in <listcomp>
    self._batches[batch_idx].slice(i - self._offsets[batch_idx], 1)
IndexError: list index out of range

**Comment by shibing624** [comment]
if name == 'main':  是啥？

**Comment by xxm1668** [comment]
main()函数

**Comment by xxm1668** [comment]
<img width="741" alt="image" src="https://github.com/shibing624/MedicalGPT/assets/129041904/96fae63e-efbc-48c8-aad5-f3e5fac5d0b2">

**Comment by shibing624** [comment]
报错是数据问题，检查数据。arrow_dataset.py

**Comment by xxm1668** [comment]
数据就是用的你项目reward文件下的test.json

**Comment by hhh12hhh** [comment]
请问最后怎么解决的呢

**Comment by xxm1668** [comment]
放弃了，用llama-factory

**Comment by shibing624** [comment]
摘出来的代码？啥意思，源代码不能跑吗？

**Comment by Factoryfromhere** [comment]
遇到同样的报错，这个报错之前有个warning:

**Comment by Factoryfromhere** [comment]
遇到同样的报错，这个报错之前有个warning：
<img width="1083" alt="error" src="https://github.com/shibing624/MedicalGPT/assets/44833391/23664ad5-3449-4715-b505-347e9dbc4006">
