### ISSUE TITLE
关于预训练的问题

### ISSUE THREAD

**Issue by xiaohengDa** [shibing624/MedicalGPT#79]
我在使用提供的医疗数据做增量预训练时，eval_loss纹丝不动，哪怕把参数配置除了模型路径外用的全是给定的参数也还是一样。这个是什么原因导致的呢？我测了llama-13b和chatglm2都是同样的结果
![af608881b9f7b5ee6c57077eea7edab](https://github.com/shibing624/MedicalGPT/assets/134503417/fae4b529-0958-4009-85f9-fb2152773082)

**Comment by shibing624** [comment]
245个epoch是什么鬼？你用的是几条数据吧？预训练一般要高质量数据集，万条以上，epochs<=3即可。

**Comment by xiaohengDa** [comment]
> 245个epoch是什么鬼？你用的是几条数据吧？预训练一般要高质量数据集，万条以上，epochs<=3即可。

我用的是https://huggingface.co/datasets/shibing624/medical这里的预训练数据集，epochs是因为在issue里看到类似的情况说多训练一会儿就行，但试过之后还是不行，从开始到最后eval_loss和eval_accuracy始终不变

**Comment by shibing624** [comment]
那一万条数据跑吧

**Comment by berton820** [comment]
> 那一万条数据跑吧

您好，这里有个疑问，虽然上面测试贴图的人用了小数据，跑了很多epoch，但是按照算法来说，哪怕是极端一点，一条数据循环10000epoch，模型训练loss应该也会下降才对。
所以我怀疑其实loss是下降的，只是在shell中看不到可视化，导致以为没有下降

**Comment by sevenandseven** [comment]
> 预训练一般要高质量数据集，万条以上，epochs<=3即可。

你好，这个一万条数据如果按行来说的话，也就一万行差不多吗？

**Comment by shibing624** [comment]
嗯
