### ISSUE TITLE
请问第一阶段的增量预训练需要的显存大小

### ISSUE THREAD

**Issue by charryshi** [shibing624/MedicalGPT#8]
感谢作者
请问第一阶段：PT(Continue PreTraining)增量预训练需要的显存是个什么规模呀？我测试了4*v100 32G，如果用Ziya-LLaMA-13B-v1直接爆显存了，参数
per_device_train_batch_size 1
block_size 512
有办法跑得了吗？
另外测试第一阶段：PT(Continue PreTraining)增量预训练在ChatGLM-6B上，我也只能设置参数为
per_device_train_batch_size 1
block_size 512
大概25G显存，这两参数大了也会爆显存。

还有个问题，关于HF上的pretrain是json格式的，那就不能用rain_file_dir 必须用dataset_name的方式加载吗？我使用dataset_name方式加载后基于ChatGLM-6B预训练时报错，不知道什么原因
  File "/home/xxx/.cache/huggingface/modules/transformers_modules/modeling_chatglm.py", line 682, in <listcomp>
    context_lengths = [seq.tolist().index(self.config.bos_token_id) for seq in input_ids]
ValueError: 130004 is not in list

**Comment by shibing624** [comment]
1. 爆显存问题，自己依据自己机器显存而定参数；如果显存不足，用lora训练；
2. 想用train_file_dir,可以把hf dataset 的数据集手动下载后，自己解析下json为txt格式就可。
