### ISSUE TITLE
关于ziya-llama-13b-medical-lora 模型权重如何获得

### ISSUE THREAD

**Issue by daimazz1** [shibing624/MedicalGPT#80]
您好，我在[shibing624/ziya-llama-13b-medical-lora]和[IDEA-CCNL/Ziya-LLaMA-13B-v1]分别下载了lora权重和Ziya-LLaMA-13B-v1的权重，问一下完整的这个ziya-llama-13b-medical-lora预训练权重模型怎么获得，是直接将这个两个链接中现在的权重使用merge_peft_adapter.py进行合并就可以获得吗？我看Ziya-LLaMA-13B-v1的readme有说给的不是完整权重，还需要把Ziya-LLaMA-13B-v1与LLaMA先合并然后再和ziya-llama-13b-medical-lora权重文件进行合并吗。

**Comment by shibing624** [comment]
https://huggingface.co/shibing624/ziya-llama-13b-medical-merged

**Comment by daimazz1** [comment]
> https://huggingface.co/shibing624/ziya-llama-13b-medical-merged

感谢~
