### ISSUE TITLE
Stage4 PPOtrainer logging问题

### ISSUE THREAD

**Issue by ymyjl** [shibing624/MedicalGPT#82]
### Describe the Question

llama第四阶段logging报错：
ValueError: Logging with `tensorboard` requires a `logging_dir` to be passed in.

run_training_pipeline.ipynb这个里面第四阶段有说
模型训练结果：
使用lora训练模型，则保存的lora权重是adapter_model.bin, lora配置文件是adapter_config.json，合并到base model的方法见merge_peft_adapter.py
日志保存在output_dir/trl目录下，可以使用tensorboard查看，启动tensorboard方式如下：tensorboard --logdir output_dir/trl --host 0.0.0.0 --port 8009

但我没有找到logging_dir在哪里配置，而且 我看accelerate库里也有这个问题
https://github.com/huggingface/accelerate/issues/1619
不知道您是通过这个pr里提到的 pip install git+https://github.com/huggingface/accelerate来解决的吗？我用这个命令装不上。
还是您没有遇到这个问题，通过其他方法可以饶过这个问题。但是我的环境和执行第四阶段的训练参数感觉和您一样。

**Comment by ymyjl** [comment]
好的，感谢 这个问题解决了 但是还有另外一个问题，第四阶段训练 采用llama 7B模型，batchsize=1跑几步也会OOM，还有什么可以调整的吗？用的双卡A100（32G）
![image](https://github.com/shibing624/MedicalGPT/assets/113601649/a83046ee-f9fe-45ba-b855-89e308f15392)

**Comment by shibing624** [comment]
max_source_length 和max_target_length 调小，reward模型（你用的llama）可以改为bert类，reward模型可以单独放一个显卡处理。
