### ISSUE TITLE
【chatglm2和Baichuan-13B】二次预训练和微调支持？

### ISSUE THREAD

**Issue by LouisHeck** [shibing624/MedicalGPT#84]
请问目前支持chatglm2和Baichuan-13B的二次预训练和微调支持？

**Comment by shibing624** [comment]
还没测试

**Comment by Zagreus-lzy** [comment]
我试了一下，baichuan-7b的二次预训练效果比chatglm好。

**Comment by songyq8888** [comment]
> 还没测试

我测试了，lora 4*A100显存也爆了

**Comment by valkryhx** [comment]
> 我试了一下，baichuan-7b的二次预训练效果比chatglm好。

是用的最新代码吗？是否使用了pretrain中的group_text?

**Comment by shibing624** [comment]
已经支持了。

**Comment by valkryhx** [comment]
> 已经支持了。

我想请问下，增量预训练在类似chatglm和baichuan-chat这种已经做过指令微调的模型上，效果是不是不好 甚至有副作用？增量预训练是否适合用在pretrain的模型上更合适呢？

**Comment by shibing624** [comment]
1. 效果好，需要自己增量预训练的数据少一些；
2. 有较多的领域数据（无监督的数据），建议用base model，训练专门模型，如果没有，就用chat类的。

**Comment by valkryhx** [comment]
> 2\. 领域数据（无监督的数据），建议用base model，训练专门模型，如

感谢指导！

**Comment by sevenandseven** [comment]
> 1. 效果好，需要自己增量预训练的数据少一些；
> 2. 有较多的领域数据（无监督的数据），建议用base model，训练专门模型，如果没有，就用chat类的。

你好，可以透漏下大概有多少的领域数据建议使用base model吗？

**Comment by shibing624** [comment]
百万以上
