### ISSUE TITLE
传参时load_in_8bit=True 为何显存占用没有减小呢？ 

### ISSUE THREAD

**Issue by valkryhx** [shibing624/MedicalGPT#85]
不设置load_in_8bit时， chatglm2-6B加载后是12.4GB左右，符合预期，因为原始模型是fp16精度保存的。所以6.2*4/2 =12.4GB，符合。
但是load_in_8bit 开启，模型加载完还是12.4GB显存。这是load_in_8bit没起作用吗？
还是说load in 8bit 对训练不生效？

**Comment by shibing624** [comment]
> load_in_8bit

1. chatglm 是自己做了量化，开启方法是手动量化，代码没有合入transformers官方库，load_in_8bit 只适用于用bnb量化的模型，llama等。

2. 是，few shot

**Comment by valkryhx** [comment]
> > load_in_8bit
> 
> 1. chatglm 是自己做了量化，开启方法是手动量化，代码没有合入transformers官方库，load_in_8bit 只适用于用bnb量化的模型，llama等。
> 2. 是，few shot

另外我想请教一下，在pretrain时我根据您data里面天龙八部的txt自己组织了txt文本 每行也是\n结尾 ，但是加载很奇怪，如下：
 train: Dataset({
        features: ['text'],
        num_rows: 44
    })
    validation: Dataset({
        features: ['text'],
        num_rows: 44
    })
})
Running tokenizer on dataset: 100%|███████████████| 1/1 [00:00<00:00,  4.30ba/s]
Running tokenizer on dataset: 100%|███████████████| 1/1 [00:00<00:00, 55.76ba/s]
Grouping texts in chunks of 1024: 100%|███████████| 1/1 [00:00<00:00, 96.22ba/s]
Grouping texts in chunks of 1024: 100%|██████████| 1/1 [00:00<00:00, 106.32ba/s]
2023-07-12 14:37:45.076 | DEBUG    | __main__:main:617 - Num train_samples: 2

明明是44行 但是 num_train_samples 值为2？

**Comment by valkryhx** [comment]
line breaks参数我使用默认值True
