### ISSUE TITLE
chatglm-6b的rm和rl阶段问题

### ISSUE THREAD

**Issue by daimazz1** [shibing624/MedicalGPT#86]
您好，我是用chatglm-6b跑第三阶段rm时报错，我看reward_modeling.py文件里没有处理chatglm类的model，问一下现在是rm、rl阶段没办法跑chatglm模型吗，近期会出这两阶段chatglm模型的测试吗，如果只使用pt、sft、阶段训练针对领域数据的话对模型的影响大吗？

**Comment by shibing624** [comment]
只用SFT就可以，其他方法是增分项
