### ISSUE TITLE
chatglm2-6b pt阶段num_train_samples

### ISSUE THREAD

**Issue by 535603775** [shibing624/MedicalGPT#89]
我用了chatglm2-6b二次训练了医疗领域的数据集，我的数据量是500，但是打印的num_train_samples是169，这样会不会对我的数据分割的不完整。并切将训练好的模型合并完成后，测试的时候发现，经常会出现回答重复的情况，且不会中断。

**Comment by shibing624** [comment]
看下代码里面block size的逻辑
