### ISSUE TITLE
二次预训练 语料准备问题

### ISSUE THREAD

**Issue by valkryhx** [shibing624/MedicalGPT#90]
我看到您在二次预训训练的样例语料中，例如tianlongbabu.txt中每一行只是正常句号结尾。没有做特殊处理。

问题1：我使用chatglm2-6b 以及这个语料的格式自己准备15行语料【都是QA句子】做二次预训练，发现输出是只有达到max_lengh值才会停下来，如果max_length。这样是符合二次预训练预期的吗？感觉这样的回答好像很破碎，有时候句子是半截的。

问题2：这种情况下，领域知识是加入到模型中了吗？我在这个二次预训练的模型上再拿领域语料SFT，会有效果吗？

问题3：有没有什么办法 让二次预训练时的语料中加入比如</s>标记  以这个标记作为段落或者句子结束，然后将完整的段落作为一个sample，而不是目前的block_size切分的做法？

谢谢！

**Comment by shibing624** [comment]
1. 自行了解下PT的训练方法和原理；
2. 会；
3. 那就不是PT了，是SFT
