### ISSUE TITLE
在利用deepspeed对chatglm2进行微调的时候，多机多卡的cuda问题

### ISSUE THREAD

**Issue by 1716649290** [shibing624/MedicalGPT#97]
![eff0e488a695dc561d6e46cba09acb4](https://github.com/shibing624/MedicalGPT/assets/58947669/e57986f6-474c-4ff8-9edf-4fb0593068ca)

**Comment by shibing624** [comment]
我不知道，没遇到过，好像是torch版本不对

**Comment by 1716649290** [comment]
我是在进行多机多卡训练时遇到的错误，这是其中一台机器上的日志，另外一台机器上的日志报错如下：（Some NCCL operations have failed or timed out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.）
![1689648191026](https://github.com/shibing624/MedicalGPT/assets/58947669/8f70608f-597d-49d6-b07a-fad73d72338d)

**Comment by shibing624** [comment]
单机有问题吗？
