### ISSUE TITLE
有什么效果评估吗？每个步骤PT， SFT， RM, PPO分别是怎样的效果？

### ISSUE THREAD

**Issue by ljch2018** [shibing624/MedicalGPT#98]
### Describe the Question
Please provide a clear and concise description of what the question is.

**Comment by shibing624** [comment]
用cEval评测集评估，主要是PT,SFT，PPO后的各评估下

**Comment by ljch2018** [comment]
@shibing624 当前有cEval的评估结论吗？

**Comment by zhaozhaoxia** [comment]
每个步骤都需要微调吗？

**Comment by shibing624** [comment]
主要测评SFT的模型结果就可以。
