### ISSUE TITLE
关于模型训练参数

### ISSUE THREAD

**Issue by daimazz1** [shibing624/MedicalGPT#99]
您好关于模型的训练参数，[shibing624/ziya-llama-13b-medical-lora]模型在进行4个阶段训练时的具体参数设置与代码中给出的默认参数是一至的吗，如果这个代码只是测试跑通数据的训练参数能麻烦您给出实际训练时的训练参数吗，4个阶段的num_train_epochs分别是多少方便告知吗，谢谢~

**Comment by shibing624** [comment]
写了呀："num_train_epochs": 10.0  ["num_train_epochs": 10.0](https://huggingface.co/shibing624/ziya-llama-13b-medical-lora)

**Comment by daimazz1** [comment]
> 写了呀："num_train_epochs": 10.0 ["num_train_epochs": 10.0](https://huggingface.co/shibing624/ziya-llama-13b-medical-lora)

你好麻烦问下是4个阶段模型的num_train_epochs": 10.0 都是10吗，还是说sft阶段为10，其他阶段epoch为多少呢？
